### ISSUE TITLE
N+1 Query Issues on Subscription Methods

### ISSUE THREAD

**Issue by shatterproof** [laravel/cashier-stripe#1008]
- Cashier Version: 12.4.0
- Laravel Version: 7.28.3
- PHP Version: 7.4.10

Pull request #1003 to simplify the subscription method causes N+1 query issues for me when accessing any of the subscription related methods on the User model in Cashier 12.4.0. I was able to solve the issue by reverting to 12.3.1 for now.

**Comment by driesvints** [comment]
Please share code to reproduce this.

**Comment by driesvints** [comment]
Preferable as well as examples of the N+1 problem.

**Comment by shatterproof** [comment]
As an example, for a Billing page I need to access information regarding the user's subscription using the following methods:

`auth()->user()->subscribed('plan');`
`auth()->user()->hasIncompletePayment('plan');`
`auth()->user()->subscription('plan')->onGracePeriod();`

With Cashier 12.3.1 this is no issue and the following queries are performed:
```
select * from `subscription_items` where `subscription_items`.`subscription_id` in (100)
select * from `subscriptions` where `subscriptions`.`user_id` = 59 and `subscriptions`.`user_id` is not null order by `created_at` desc
select * from `users` where `id` = 59 and `users`.`deleted_at` is null limit 1 
```

However, using the same exact code with Cashier 12.4.0 the following queries are performed:
```
select * from `subscription_items` where `subscription_items`.`subscription_id` in (100)
select * from `subscriptions` where `subscriptions`.`user_id` = 59 and `subscriptions`.`user_id` is not null order by `created_at` desc
select * from `subscription_items` where `subscription_items`.`subscription_id` in (100)
select * from `subscriptions` where `subscriptions`.`user_id` = 59 and `subscriptions`.`user_id` is not null order by `created_at` desc
select * from `subscription_items` where `subscription_items`.`subscription_id` in (100)
select * from `subscriptions` where `subscriptions`.`user_id` = 59 and `subscriptions`.`user_id` is not null order by `created_at` desc
select * from `users` where `id` = 59 and `users`.`deleted_at` is null limit 1
```

You can see the two queries regarding the subscription are duplicated every time the subscription methods are accessed, rather than simply being called once as expected.

While looping through invoices this duplication occurs on every loop as well, seriously compounding the issue.

**Comment by corsair** [comment]
I am also experiencing the same issue as @shatterproof upon upgrading from 12.3.1 to 12.4.0. The number of select queries essentially doubled, with the only code called being the following:

`if($this->subscribed('regular') && $this->subscription('regular')->recurring()) return true;`

Here's a graph (via CloudWatch) of the almost spontaneous increase in queries following upgrading.
![image](https://user-images.githubusercontent.com/1847891/95023604-d5cc4e80-0632-11eb-90c4-057619c5296c.png)

**Comment by driesvints** [comment]
Thanks all for the detailed replies. I've sent in a PR that fixes this: https://github.com/laravel/cashier-stripe/pull/1009
