### ISSUE TITLE
Capture a charge on lator is not mentioned and implemented in docs 

### ISSUE THREAD

**Issue by ameerbjs** [laravel/cashier-stripe#1011]
Capture the payment of an existing, uncaptured, charge. This is the second half of the two-step payment flow, where first you created a charge with the capture option set to false.
Uncaptured payments expire exactly seven days after they are created. If they are not captured by that point in time, they will be marked as refunded and will no longer be capturable.

**Comment by driesvints** [comment]
Please provide more info. What flow are you using? Can you share some code? What is it that you're expecting to happen and what happens at this moment instead?

**Comment by driesvints** [comment]
Please also resubmit this with a filled out issue template.
