### ISSUE TITLE
Adding seats to subscription always invoices customer

### ISSUE THREAD

**Issue by didac-adria** [laravel/cashier-stripe#1012]
- Cashier Version: 12.4.0
- Spark Version: 11.0.2 (this issue is linked to Spark as well)
- Laravel Version: 8.6.0
- PHP Version: 7.4.4

### Description:
Since our Laravel 8 update, each time one of our customers updates the seats of their subscription, they get invoiced directly despite of including `Spark::noProrate()` method in the `boot` method of `SparkServiceProvider`, as the [Spark documentation](https://spark.laravel.com/docs/11.0/billing#proration) suggests.

### Source of the problem:
I think that the source of the problem comes from the Billable class (`Billable.php`). The method `addSeat` includes:
```
if (Spark::prorates()) {
            $subscription->incrementAndInvoice($count);
        } else {
            $subscription->noProrate()->incrementAndInvoice($count);
       }
```
So, if `Spark::prorates()` is false, we should not make `incrementAndInvoice()` but calling the method `incrementQuantity()`, which sets the `prorationBehavior` of the Prorates trait to `'always_invoice'`.
Note: find out more about the 3 Stripe options on the proration_behavior parameter [here](https://stripe.com/docs/api/subscriptions/update#update_subscription-proration_behavior).

Thus, I think it should be like this in order to accomplish what the Spark documentation above says:
```
if (Spark::prorates()) {
            $subscription->incrementAndInvoice($count);
        } else {
            `$subscription->noProrate()->incrementQuantity($count);
       }
```
Similarly, in the `updateSeats` method of `Billable.php`:
```
if (! Spark::prorates()) {
            $subscription = $subscription->noProrate();
        }

        if ($count > $subscription->quantity) {
            $subscription->incrementAndInvoice($count - $subscription->quantity);
        } elseif ($count < $subscription->quantity) {
            $subscription->decrementQuantity($subscription->quantity - $count);
        }
```
If there is no prorate, `$subscription->noProrate()` should already set the `prorationBehavior` to `'none'`. Thus, we don't need to call `incrementAndInvoice`. Calling `incrementQuantity` will already use the `prorationBehavior` set in the Prorates trait:
```
if (! Spark::prorates()) {
            $subscription = $subscription->noProrate();
        }

        if ($count > $subscription->quantity) {
            $subscription->incrementQuantity($count - $subscription->quantity);
        } elseif ($count < $subscription->quantity) {
            $subscription->decrementQuantity($subscription->quantity - $count);
        }
```

If you find I have to report this on another project, I'll be happy to do it. I can also create a PR if we agree this is the source of the problem.

### Related issue:
The solution stated above should put the code according to [Spark's documentation](https://spark.laravel.com/docs/11.0/billing#proration) (not invoicing the customer if `Spark::noProrate()` is called in the `sparkServiceProvider`. However, [stripe's documentation](https://stripe.com/docs/api/subscriptions/update#update_subscription-proration_behavior) says that there are 3 possible values for `proration_behavior`: 'create_prorations', 'none' and 'always_invoice'. In our case, we would like to prorate upon subscription seats changed, but not invoice at the moment but wait until next billing day. As per Stripe's docs, I think this should be 'create_prorations' instead of 'none'.

If we analyse the Billable class **with the changes I suggest above**, when adding seats:
-> The `addSeat()` method will send Stripe as `proration_behavior` either 'always_invoice' or 'none', depending on the `Spark::prorates()`parameter.
-> While the `updateSeats()` method will send either 'none' or 'create_prorations' (because is the default value of the Prorates trait).

So, if we would like to send 'create_prorations' (to prorate but not send invoice to customer) we should not add `Spark::noProrate()`and use the `updateSeats()` method. This contradicts [Spark documentation's section of prorates](https://spark.laravel.com/docs/11.0/billing#proration). Thus, this leads me to think that maybe there should be more options in the sparkServiceProvider to deal with the 3 Stripe options.

Please, correct me if I'm mistaken.
Again, I can create another issue for this if you consider so.

**Comment by driesvints** [comment]
Waiting for @themsaid's input as this indeed seems a Spark issue.

**Comment by didac-adria** [comment]
@themsaid do you have any input about this? If you need, I can move this to any other repository. We are charging daily our customers for this issue, as they change quite a lot their seats these days.

Thanks guys!

**Comment by driesvints** [comment]
Spark should have been patched with this now in 11.0.4

**Comment by didac-adria** [comment]
Ok, great thank you for the update @driesvints . We'll check it asap!

**Comment by didac-adria** [comment]
Hello, @driesvints and @themsaid,

Thanks for your update on Spark. We appreciate it :)

I've checked your work and now works as expected. However, we have the problem that I mentioned in my original post, as a "Related issue". Let me give you more details:

[Spark's documentation](https://spark.laravel.com/docs/11.0/billing#proration) says: "However, you can disable proration so that no changes are made to the subscription until the beginning of the next billing cycle.". So this means that it should be possible to prorate but invoice the changes on the next billing cycle. In fact, this was the behaviour I think it was on the last major version of Spark.

However, with Spark 11 it's not happening. What is happening, in fact, is that if the `Spark::noProrate()` method is called on the `sparkServiceProvider`, the 'proration_behavior' sent to stripe has the value of 'none' (thus there is no prorate), and if `Spark::prorates()`is true, the value sent to stripe is 'always_invoice' (thus prorating but invoicing the customer).

Thus, right now there is no way to send stripe as 'proration_behavior' with a value of 'create_prorations' as [stripe's documentation suggests](https://stripe.com/docs/api/subscriptions/update#update_subscription-proration_behavior). This is in order to prorate, but not bill right now but wait until the next billing cycle.

How can we recover the previous behaviour? I'll be happy to discuss about the topic, provide more info or, if needed, report this problem in another place.

Thanks guys!

**Comment by driesvints** [comment]
@didac-adria that's a change in Stripe behavior actually. Previously if proration was enabled in Spark it'd apply proration and invoice immediately just like it does now. There was never a situation where proration was applied but invoicing was delayed. Or are you claiming it was?

**Comment by didac-adria** [comment]
Hi @driesvints!

I think it was, but you are totally right, it looks to be a Stripe's change. "The prorate parameter is deprecated in favour of proration_behavior.", says their [API changelog](https://stripe.com/docs/upgrades#api-changelog), with date of the 27th of August 2020.

I see in our logs that in the post body before the change we were sending:
```
{
  "quantity": "46",
  "prorate": "false"
}
```
While now we send:
```
{
  "quantity": "51",
  "payment_behavior": "allow_incomplete",
  "proration_behavior": "none"
}
```
Which makes me think that before the change, when sending `"prorate": "false"`would make stripe prorate but apply the changes in the next bill. I've asked information about this to Stripe to make sure.

In any case, I think it would be important for Spark to update to the new situation. In our particular case, this could potentially lead to customers removing all the seats just before re-subscribing, thus paying for 0 or just 1 seat for all the month and then add the seats again, among other problems happening currently.

Thanks team!

**Comment by driesvints** [comment]
Yeah that's the new behavior that's adopted in Cashier Stripe v12. See https://github.com/laravel/cashier-stripe/blob/12.x/UPGRADE.md#proration-changes. We're not using the old `prorate` parameter anymore.

I'm sorry but I still don't understand the problem you're facing. Can you please provide a detailed step by step list on how to reproduce your problem and clearly detail what it is that's happening and what you expect to happen?

**Comment by themsaid** [comment]
Same as @driesvints , I don't understand the problem.

With `Spark::prorates()`, you get `proration_behavior = create_prorations`
With `Spark::noProrate()`, you get `proration_behaviour = none`.

What change would you like to see here and why?

**Comment by didac-adria** [comment]
Hello guys!

Yeah sure no problem. As @themsaid mentions those are the two available values for `proration_behavior` that Spark allows with its configuration. `always_invoice` creates prorations and invoices them immediately. `none` doesn't create prorations. 

However we would like to create prorations but NOT invoice them immediately. This was the behaviour we had over the last years. In fact, this is pretty important for us because our customers change seats very often for certain business reasons and we don't want to invoice them each time, which creates hundreds of invoices and a problem for our accountants.

[Stripe's documentation](https://stripe.com/docs/api/subscriptions/update#update_subscription-proration_behavior) says that there is a third value for `proration_behavior`: `create_prorations`. This one allows you to create prorates but invoice them in the next bill. This is exactly what we need, advised also by Stripe's support.

I hope it'ts clearer now. Let me know if it doesn't.

**Comment by themsaid** [comment]
@didac-adria and how would this work for annual billing then? A customer can add seats on day 1 and won't get billed until the end of the year. So basically they are using your platform for free for a whole month/year.

**Comment by didac-adria** [comment]
Hi @themsaid!

We are not using annual billing, monthly instead. This is why I think that this should be something to be chosen in the `sparkServiceProvider`, where the teams should be able to choose which `proration_behavior` should be used.

In fact, we had that behaviour before, but I guess that with Stripe's new API this has changed and they divided it into those 3 values for the `proration_behaviour`.

Let me know if you need more details.

**Comment by didac-adria** [comment]
Hello @themsaid & @driesvints 

Do you have any new on this topic? It is causing us many problems. Right now we have to choose between:

1- Make prorates and invoice every seat change. This is a problem for us due to the huge amount of invoices created + our stripe charges increase a lot when we make a huge amount of small charges.
2- Do not prorate with the consequent problems for our customers (no balance updates when chaning seats, specially when they have paid for 200 seats and they remove all the seats the same day down to 5 seats).

**Comment by themsaid** [comment]
Does this PR solve your issue? https://github.com/laravel/spark-aurelius/pull/385

**Comment by didac-adria** [comment]
Hello @themsaid,

Sorry for my late reply. Yes, I think it solves it. I see that we will be able to choose the prorates behaviour from the SparkServiceProvider, right?

We wait for your new release and thank you once again.
