### ISSUE TITLE
Cannot pass proration_behavior option with swap() function

### ISSUE THREAD

**Issue by abdurrahmanriyad** [laravel/cashier-stripe#1013]
- Cashier Version: 10.7.1
- Laravel Version: 6.18.40
- PHP Version: 7.4.7
- Database Driver & Version: mysql 8

### Description:
in swap() method of subscription class, it always passes the prorate key.
So, if proration_behavior passed as an option stripe gives the following error message,

"Received both proration_behavior and prorate parameters. Please pass in only one."

### Steps To Reproduce:
Refer to this code example to reproduce.
$this->user->subscription('default')->swap('plan_id', [
   proration_behavior' => 'always_invoice'
])

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!
