### ISSUE TITLE
subscribedToPlan returns incorrect result

### ISSUE THREAD

**Issue by phillmorgan28** [laravel/cashier-stripe#1016]
- Cashier Version: 12.4.1
- Laravel Version: 8.8.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:
When passing a price ID and subscription name to subscribedToPlan the result is false despite the subscription status set to active and the plan field set correctly in the database.

For example:

```
$price_id = "price_1HdaBBAqS5YcaB9RDh400lv5";
$check = request()->user()->subscribedToPlan($price_id, 'membership'); // This returns false
```

Database Table:

id | user_id | name | stripe_id | stripe_status | stripe_plan | quantity | trial_ends_at | ends_at | created_at | updated_at
6 | 2 | membership | sub_IEWfoYzlxcKe9A | active | price_1HdaBBAqS5YcaB9RDh400lv5 | 1 | NULL | NULL | 2020-10-19 19:01:29 | 2020-10-19 19:01:29

**Comment by driesvints** [comment]
The only thing I can see going wrong here is if you have multiple subscriptions of the same name and the latest one has ended. Normally this cannot happen but just to confirm: is this the only record for this user with the name "membership"?

**Comment by phillmorgan28** [comment]
As an update for you I dug into the ManagesSubscriptions.php concern. If I change this function:

```
public function subscription($name = 'default')
{
     return $this->subscriptions->where('name', $name)->first();
}
```

To this:

```
public function subscription($name = 'default')
{
     return $this->subscriptions()->where('name', $name)->first();
}
```

Everything works as expected

**Comment by phillmorgan28** [comment]
For now I will override the function in my model to use my adjusted one so I can continue development of my app, however it would be great to have an explanation of why I'm experiencing this behaviour.

Thank you!

**Comment by driesvints** [comment]
The change from above was applied to solve a n+1 problem. What's probably happening is that you're modifying the subscription somehow before but not reloading the relation. What code are you executing before running the `subscribedToPlan` method?

**Comment by phillmorgan28** [comment]
This is the controller function where I am checking for each "tier" for an active subscription:

```
public function index() {
    $tiers = [];
    for($i=1; $i<=3; $i++) {
        $tiers[$i] = request()->user()->subscribedToPlan(env('TIER_' . $i .'_MEMBERSHIP_ID'), 'membership');
    }
    ....
```

As you can see there is no modification happening here, I am simply checking the subscription.

The only thing I can think of is that i am calling similar code in the models constructor:

```
public function __construct(array $attributes = [])
{
    parent::__construct($attributes);
    if ($this->subscribedToPlan ........
```

Do you think this could have an effect?

**Comment by phillmorgan28** [comment]
I've answered my own question there. Removing my code from the models constructor (and my override function) has got it working correctly. What an idiot I am! Thank you for your time!

**Comment by driesvints** [comment]
No problem. In general we don't recommend to modify a model's constructor ever. That could lead to unwanted side effects like this one. Glad you got it sorted 👍
