### ISSUE TITLE
Stripe taking a double payment on signup

### ISSUE THREAD

**Issue by treforcoster** [laravel/cashier-stripe#1018]
- Cashier Version: 12.4
- Laravel Version: 7.28.3
- PHP Version: 7.4

### Description:
I have an application using Spark version 11.0.1 that is sometimes taking double payments when a user signs up. Recurring payments are fine it's just sometimes when a user signs up stripe will take a double payment. Can any one shed some light on this?

**Comment by driesvints** [comment]
Seems like you also already contacted Spark support about this. We haven't received any report for both Cashier or Spark before this so this seems like a problem to you specific in your app. Please try a support channel instead:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by sammyaxe** [comment]
@treforcoster have you figured out why, seems we have same problem. It's a bit random
