### ISSUE TITLE
laravel/cashier webhook does not work properly on lumen

### ISSUE THREAD

**Issue by jhayg12** [laravel/cashier-stripe#1019]
- Cashier Version: 12.4
- Lumen Version: 8.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 5.7.22

### Description:
Hi there,

I'm trying to extend the WebhookController of the laravel/cashier package and listen to some events that were not included in the default events. But when I tried to test a webhook call from the Stripe Dashboard it returns the error below:

![image](https://user-images.githubusercontent.com/33854581/97378678-df796700-18fd-11eb-9cd1-143a142a3b2e.png)

```
<b>Fatal error</b>:  Trait 'Illuminate\Foundation\Events\Dispatchable' not found in <b>/var/www/html/vendor/laravel/cashier/src/Events/WebhookReceived.php</b> on line <b>8</b><br />
<!-- Trait 'Illuminate\Foundation\Events\Dispatchable' not found (500 Internal Server Error) -->
```

It seems it's looking for the `Dispatchable` trait on the Lumen Framework

### Steps To Reproduce:
1. Add the webhook URL on the stripe dashboard
2. Try to send some test webhooks and check the response.

**Comment by driesvints** [comment]
We don't support any of the 1st party packages on Lumen. Please see our support policy and use Laravel if you need Cashier.
