### ISSUE TITLE
Cashier implementation of Stripe Billing Portal causing CORS issues

### ISSUE THREAD

**Issue by mrpritchett** [laravel/cashier-stripe#1022]
- Cashier Version: 12.4.2
- Laravel Version: 8.11.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:
I'm trying to implement Stripe Billing Portal as described in the latest Cashier docs and Laravel w/ Jetstream & Inertia. Hitting the billing portal causes CORS errors that I can't seem to overcome. 

### Steps To Reproduce:
Install Laravel 8.x w/ Jetstream, Inertia. 
Setup Billing Portal controller and route.
Navigate to the route.
Nothing visible happens, but console tells a tale of CORS issues.

**Comment by mrpritchett** [comment]
Sometimes sleep make you see how stupid you are. 🤣

**Comment by earnestware** [comment]
i must still be asleep - what was the fix? :)

**Comment by alex-maereanu** [comment]
send it as an object @earnestware
