### ISSUE TITLE
Calling invoices() method returns an empty object

### ISSUE THREAD

**Issue by jhayg12** [laravel/cashier-stripe#1023]
- Cashier Version: 12.4
- Laravel Version: 8.0
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 5.7.22

### Description:
Hi there, I'm trying to retrieve the invoices for a particular user using the `invoices()` method as per the documentation but it returns an empty object.

```
$user = Auth::user();
$user->invoices();
```

The response looks like this:
`[
    {}
]`

### Steps To Reproduce:
1. Install laravel cashier package.
2. Create subscription for a user.
3. Retrieve invoices

**Comment by driesvints** [comment]
I doubt this is broken or we'd be flooded with support issues. Please try a support channel first:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!
