### ISSUE TITLE
withMetada bug

### ISSUE THREAD

**Issue by githetcouvert** [laravel/cashier-stripe#1026]
- Cashier Version: 12.5
- Laravel Version: 8
- PHP Version: 7.4.12
- Database Driver & Version:

### Description:

Unable to pass metadata with syntax ->withMetadata(['objet'=>'key'])

Below my syntax on subscriptionController create :

`$request->user()->newSubscription('default', $plan->stripe_id)
->withMetadata(['key' => 'value'])
->create($request->token);`

### Steps To Reproduce:

`
 public function create(Request $request) {

        
        $this->validate($request, [
            'token' => 'required'
        ]);

        $plan = Plan::where('identifier', $request->plan)
        ->orWhere('identifier', 'basic')
        ->first();

        

        Auth::user() //make sure your user is signed in and use the authenticated user
            ->newSubscription('default', $plan->stripe_id)
            ->withMetadata(['order_id'=>'8']) 
            ->create($request->stripeToken);

            return back();
        
    }
`

I am unable to find a solution i just need to pass metadatas to stripe but it bugs !

Any help really appreciated !

**Comment by driesvints** [comment]
What's the error you're getting?

**Comment by githetcouvert** [comment]
When i go to stripe, it didn't receive any metadata...

**Comment by githetcouvert** [comment]
i am trying everything but unable to send metadatas i tried unsuccessfully another method ... :

`
$request->user()->newSubscription('default', $plan->stripe_id)->create($request->stripeToken, [
                'email' => 'derg@tiol.com',
            ], [
                'metadata' => ['note' => 'Some extra information.'],
            ]);
`

**Comment by driesvints** [comment]
Apparently metadata was still untested in the test suite but I've added a test which verifies that this correctly works atm: https://github.com/laravel/cashier-stripe/commit/beabf549a37c766695395cc0c20efa9377dba859

It seems there's a specific thing on your side that's causing this. For this I'd like to forward you to a support channel: 

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
