### ISSUE TITLE
Throw IncompletePayment for quantity methods on subscription

### ISSUE THREAD

**Issue by AnthonyHexium** [laravel/cashier-stripe#1027]
Hi there,

First off all thanks for your the work done on Laravel Cashier. This is an amazing package.

- Cashier Version: 12.4.2
- Laravel Version: 7.28.4
- PHP Version: 7.4

### Description:
I have a `default` subscription which contains by default : 
- Global subscription
- 2 Options

Those are three different product in my stripe dashboard.

When I am trying to increment one option with a card who doesn't have funds (`pm_card_chargeCustomerFail`) I don't catch any exception but the payment declined on stripe.

```php
try {
   auth()->user()->owns->subscription('default')->incrementAndInvoice(1, config("subscription.{$option}_{$currentPlan}"));
} catch (Exception $exception) {
   dd($exception);
}
```

**Comment by driesvints** [comment]
I didn't get to this today. Hope to on Thursday or on Friday maybe.

**Comment by AnthonyHexium** [comment]
Hello @driesvints, I am going to make some feature test on my use case in the next 24 hours and will try to remember to come here give you an update. Thanks for your work on this lib !

**Comment by AnthonyHexium** [comment]
So, here is the result of the small researches I have made. The `incrementAndInvoice` method always increment the quantity, even when the card doesn't have funds. Is it the expected behavior ? Because the description of the method is `Increment the quantity of the subscription, and invoice immediately.`.

Here some code who may help to reproduce ?

```php
// Controller
    public function incrementOption(Request $request)
    {
        $option = $request->validate(['option' => 'required|in:company,user'])['option'];
        $currentPlan = current_plan(auth()->user()->owns->subscription());

        try {
            dump(auth()->user()->owns->subscription('default')); // Here the quantity is 1

            auth()->user()->owns->subscription('default')->incrementAndInvoice(1, config("subscription.{$option}_{$currentPlan}"));

            dump(auth()->user()->owns->subscription('default')); // Here the quantity is 2
        } catch (IncompletePayment $exception) {
            return response()->json([
                'message' => "IncompletePayment"
            ], 422);
        } catch (SubscriptionUpdateFailure $exception) {
            return response()->json([
                'message' => "SubscriptionUpdateFailure"
            ], 422);
        } catch (Exception $exception) {
            return response()->json([
                'message' => "Exception"
            ], 422);
        }

        return response()->json();
    }
```

```php
// Test
    public function an_owner_cannot_increment_a_subscription_quantity_when_his_card_doesnt_have_funds()
    {
        $user = User::find(1);
        $this->actingAs($user);

        $user->owns->createAsStripeCustomer();
        $user->owns->updateDefaultPaymentMethod('pm_card_visa');

        $user->owns->newSubscription('default', config('subscription.main_monthly'))
            ->plan(config('subscription.company_monthly'), 1)
            ->plan(config('subscription.user_monthly'), 1)
            ->add();

        $user->owns->updateDefaultPaymentMethod('pm_card_chargeCustomerFail');

        $response = $this->postJson(route('plan.incrementOption'), ['option' => 'user']);

        $response
            ->assertStatus(222);
    }
```

Here it results into a `200` status code. Maybe this has to be handled with webhooks ? It's kind of stange ...

**Comment by driesvints** [comment]
Hey @AnthonyHexium. So I finally managed to test this out. What happens with this scenario is that the subscription does get updated with the correct quantity but it becomes past due because the payment failed. In this scenario it would indeed be logic for Cashier to throw the `IncompletePayment` exception. 

Since adding this now would be a breaking change for anyone not expecting it, we'll need to do it the soonest in the next major version. Since there's no real bug here because you can still do this yourself after calling the method I'll mark this as an enhancement. 

I'll try to implement this eventually but we're accepting PRs of course. Thanks for raising it.

**Comment by driesvints** [comment]
This will land in v13
