### ISSUE TITLE
Subscription via Stripe Checkout does not get found

### ISSUE THREAD

**Issue by felixstoessel** [laravel/cashier-stripe#1030]
- Cashier Version: 12.5.0
- Laravel Version: 7.29.3
- PHP Version: 7.4.10

### Description:
When using Stripe Checkout via `Session::create()` and `mode: subscription`, I get a subscription inside Stripe for this customer. But using `$user->subscriptions` doesn't list this subscription. It seems to only list subscriptions created via `->newSubscription(...)`. This "initial" subscription also doesn't appear in the subscriptions/subscription_items tables.

```
$customer = $user->createOrGetStripeCustomer();

$session = Session::create([
  'payment_method_types' => ['card'],
  'line_items' => [[
    'price' => 'price_1Ho5mgGAnUQ2HSNI2kbH1nN5',
    'quantity' => 1,
  ]],
  'mode' => 'subscription',
  'customer' => $customer->id,
  'success_url' => url($nova.'/success?session_id={CHECKOUT_SESSION_ID}'),
  'cancel_url' => $body['url'],
]);
```

Thanks for your help!

**Comment by driesvints** [comment]
Stripe Checkout isn't supported yet. Please see the open PR and help us test it: https://github.com/laravel/cashier-stripe/pull/1007
