### ISSUE TITLE
Pause payment collection

### ISSUE THREAD

**Issue by daugaard47** [laravel/cashier-stripe#1031]
Curious if Cashier has plans to support Pausing and Resuming a Subscription.
Although I can implement this on my own, I would love to see this feature added via Cashier.

https://stripe.com/docs/billing/subscriptions/pause

**Comment by driesvints** [comment]
Hmm, yeah I think we can provide some nice API methods for that although you can of course already do this with the `updateStripeSubscription` method:

```php
$subscription->updateStripeSubscription([
     'pause_collection' => ['behavior' => 'mark_uncollectible'],
]);
```

Can you maybe tell a bit more on your use case for this? Why you'd like to do these things through the app instead of through the Stripe dashboard?

**Comment by daugaard47** [comment]
I personally feel most people cancel their subscriptions due to financial reasons. Giving customers the option to Pause over Cancel would most likely save businesses customers in the end.

**Use case scenarios:**
 1. If the user loves the subscription, but due to financial reasons cannot afford it right now a Pause would be a nice alternative to a full Cancelation. Rather an infinite Pause, use a Time Pause. Allow your customers to Pause their subscription for X amount of months. YouTube TV currently does this.

 2. By giving the customer the option to Pause, It gives businesses time to provide some Customer Care and find out if there's anything they could do better for them in an attempt to save the sale. Once they cancel, it's most likely they are not coming back.

 3. If for some unreason I couldn't fulfill my subscription boxes for my customers for a month. As an Admin, I would Pause all subscription for that month via the Stripe Dashboard. Though it would be nice to do this via my admin system through my website.

I didn't realize I could do this with the Cashier `updateStripeSubscription` method. I didn't see this in the Billable traits. Thanks for the tip!

**Comment by driesvints** [comment]
@daugaard47 thanks for the extra info. I think we can provide something small for this. I'll look into this eventually but we're open to PR's of course.

**Comment by driesvints** [comment]
I'm going to close this one as this is something we won't be working on ourselves. Feel free to send in a PR if you like.

**Comment by yaroslawww** [comment]
@driesvints 

Hello - [there](https://github.com/yaroslawww/laravel-cashier-subscription-pause) I created package what add support for pause/unpause. I use it for my own purposes currently, but is there way to add same or similar api to core package in future? 

If current package api is OK - I can create PR in future (if there will be free time :)) - but I am not sure about json field what currently used for new table field. Will laravel team  allow use json field in core package?

**Comment by driesvints** [comment]
Don't have time to digest the package but as I said we're open to PRs.
