### ISSUE TITLE
Stripe API Expand object supports

### ISSUE THREAD

**Issue by arivazhaganark** [laravel/cashier-stripe#1033]
Earlier Customer API returns with `sources` by default.

![image](https://user-images.githubusercontent.com/10572131/100242224-93e8c600-2f5a-11eb-81d3-312d2dfde52e.png)

From 2020-08-27 its not attached by default, If need that we have to expand in the resource url.
Ref : https://stripe.com/docs/api/expanding_objects

So our Billable $customer->sources returns as NULL.

Is any body updated the package for the issue?

**Comment by driesvints** [comment]
We don't recommend using the Sources API anymore because it's being deprecated by Stripe. Cashier has been using the new Payment Providers API for a while now.

**Comment by arivazhaganark** [comment]
- Cashier Version: 7.2.22
- Laravel Version: 5.5
- PHP Version: 7.3
- Stripe API Version: 2020-08-27

### Description:
My application user create subscription with Cashier 
```$user->newSubscription('default', $plan->plan_id)->create($TOKEN);```
While creating the subscription, update the card by given TOKEN. so call `updateCard` method in Billable.php
At line 415 `$card = $customer->sources->create(['source' => $token]);` fetching customer sources.
Now the customer -> sources returned NULL, so throw error, Called undefined method on NULL

**Comment by arivazhaganark** [comment]
Fixed that,
Replace in Billable.php @ 589

`return StripeCustomer::retrieve(['id' => $this->stripe_id, 'expand' => ['sources']], $this->getStripeKey());`
instead of
`return StripeCustomer::retrieve($this->stripe_id, $this->getStripeKey());`

**Comment by driesvints** [comment]
@arivazhaganark you're running a super old version of Cashier and I recommend that you upgrade to the latest version as soon as you can.

**Comment by arivazhaganark** [comment]
yep cool :) @driesvints , my client just update stripe API version from their dashboard, don't want update laravel & cashier.
Anyway all good thanks

**Comment by socialpilgrim** [comment]
arivazhaganark you have saved many lives, running old version ..... no other choice
