### ISSUE TITLE
Split with Subscription

### ISSUE THREAD

**Issue by Overx** [laravel/cashier-stripe#1038]
Hello guys, I have a question regarding the signature, when I call the method:

`auth()->user()->newSubscription ('main', $ user->plan)->create ();`

Within create I can pass the parameters below?

```
$stripe = new \Stripe\StripeClient($this->stripekey());

      return $stripe->paymentIntents->create([
        'amount' => 1000,
        'currency' => 'brl',
        'payment_method' => $this->formaPagamento(),
        'confirmation_method' => 'automatic',
        'application_fee_amount' => 200, //taxa da plataforma em R$
        'payment_method_types' => ['card'],
        'on_behalf_of' => 'acct_1HLUpJB1VXNRhg7I', //id da conta do Parceiro
        'transfer_data' => [
          'destination' => 'acct_1HLUpJB1VXNRhg7I', //id da conta do Parceiro
        ],

      ]);
```

THX

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
