### ISSUE TITLE
Invoice exception on PHP 8.0

### ISSUE THREAD

**Issue by jsondergaard** [laravel/cashier-stripe#1043]
- Cashier Version: 12.6
- Laravel Version: 8.20
- PHP Version: 8.0

### Description:
When trying to download an invoice with Cashier, this exception is returned:
_Invalid characters passed for attempted conversion, these have been ignored_

This is discussed in detail [here](https://github.com/dompdf/dompdf/issues/2003), which mentions it being fixed in Dompdf 0.8.4

**Comment by driesvints** [comment]
I guess we can bump the minimum to 0.8.4. I'll take care of that, thanks.
