### ISSUE TITLE
Subscription Cancel Related Issue

### ISSUE THREAD

**Issue by JayedHasan232** [laravel/cashier-stripe#1044]
I extended the cashier webhook and need to get a member/user's info by his Stripe id while a customer  subscription cancellation event occurs. But, cashier's build-in webhook method deleting user's stripe id from the database before i get. So, how can I find user's data from extended controller?

Please help me.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
