### ISSUE TITLE
Unable to add subscription from the Stripe panel.

### ISSUE THREAD

**Issue by swist666** [laravel/cashier-stripe#1057]
- Cashier Version: v12.7.1
- Laravel Version: v8.26.1
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.22

### Description:
If I want to add a new subscription (user with a populated stripe_id in database) from the stripe panel, I get the error:

```
Undefined index: name
/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php:82
```

I checked payload and there is nothing in $data['metadata'], but I did not found name anywhere in payload so I don't know how to fix this.

I extended WebhookController and fixed it temporarily as follows:

```php
'name' => $data['metadata'] ? $data['metadata']['name'] : 'my-name',
```

### Steps To Reproduce:
Connect a user to Stripe as a customer. Configure the API webhook. Try to create a subscription using the Stripe panel. Some time ago it worked fine. Maybe some change to the Stripe API?

**Comment by driesvints** [comment]
Heya, sorry. It's not possible to add subscriptions through the Stripe dashboard with Cashier. When you use Cashier it's expected that all subscriptions are created through the package.

**Comment by driesvints** [comment]
I've sent in a PR to the docs to clarify this: https://github.com/laravel/docs/pull/6830

**Comment by driesvints** [comment]
Hmm, it seems we can indeed fix this easily. I'm gonna send in a PR for this.

**Comment by j-dexx** [comment]
@driesvints Sorry for piggybacking here but I assume subscriptions via the stripe control panel would be created via a webhook in your PR?  Would that mean that an app using Stripe's Google/Apple pay functionality would work with cashier assuming stripe sent cashier the subscription.created webhook?

Essentially will cashier ever support google and apple pay via stripe?  It's fine if the answer's no, just would be useful to know for a current project.

**Comment by driesvints** [comment]
Atm Cashier Stripe only supports card payments. We're definitely going to look into more Payment Methods which Stripe supports at some point once we find the time for it. At the moment other things are keeping us from looking into with the proper attention that these things need.

**Comment by j-dexx** [comment]
Ok cool, thanks for the quick reply

**Comment by swist666** [comment]
https://github.com/laravel/cashier-stripe/pull/1058/commits/f05a3d808406f12abd0f7de6e63e180771bd4278 fixes this, thank you :)
