### ISSUE TITLE
Customer email cannot be passed with Team billable model to Stripe Checkout

### ISSUE THREAD

**Issue by enkota** [laravel/cashier-stripe#1078]
- Cashier Version: 12.9.1
- Laravel Version: 8.29.0
- PHP Version: 7.4.14

### Description:
When using Stripe Checkout with a different model (e.g Team), we can't seem to pass through the `customer_email` parameter as it seems the customer info has been passed in the session already.

Message when `customer_email` is passed inside `checkout()`:
`"message": "You may only specify one of these parameters: customer, customer_email.",`

Allowing us to pass the email will help prefill the email field on the checkout page.

### Steps To Reproduce:

Use a custom billable model (e.g Team)

```
$checkout = auth()->user()->currentTeam
    ->newSubscription("default", "price_XXXXX")
    ->checkout([
        'customer_email' => auth()->user()->currentTeam->owner->email,
        "success_url" => route("billing.index"),
        "cancel_url" => route("billing.index"),
    ]);
```

**Comment by driesvints** [comment]
That's correct. If you're creating a session for an existing customer in Stripe it'll use that customer to create the session for. If this is for a new customer you can use the second parameter of `checkout` to pass any customer specific options:

```php
$checkout = auth()->user()->currentTeam
    ->newSubscription("default", "price_XXXXX")
    ->checkout([
        "success_url" => route("billing.index"),
        "cancel_url" => route("billing.index"),
    ], [
        'email'  => auth()->user()->currentTeam->owner->email,
    ]);
```

**Comment by enkota** [comment]
Ahh brilliant, didn't think to pass it as a second param! Thanks for the speedy reply @driesvints 🙌
