### ISSUE TITLE
Quantity multiply the price that is charged and not only set the quantity on the subscription

### ISSUE THREAD

**Issue by rabol** [laravel/cashier-stripe#1081]
- Cashier Version: 12.9.1
- Laravel Version: 8.30.1
- PHP Version: 8.0.1
- Database Driver & Version:

### Description:
When using the quantity() the it does not only set the quantity on the subscription it also multiply price that is charged.

### Steps To Reproduce:
Create a product and a price of €50
```
$user->newSubscription('default', $request->price_id)
            ->quantity(15)
            ->create($request->paymentMethod);
```

then look at the Stipe dashboard and see that the customer was charged €750 and not €50

**Comment by driesvints** [comment]
That's how this works. 15 quantities of the requested €50 price = €750 in total.

**Comment by rabol** [comment]
https://laravel.com/docs/8.x/billing#subscription-quantities -  say that if you want to set the quantity on a subscription you should use the quantity - it does not say that the customer will be charged xx times the subscription.

**Comment by driesvints** [comment]
It's quantity based subscription billing. I don't really know what you expect to happen here?

**Comment by driesvints** [comment]
Also, stop downvoting replies. It's so discouraging to keep helping people with all this negativity going on.
