### ISSUE TITLE
Unique constaint error when trying to swap a plan to the same one twice

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/cashier-stripe#1089]
- Cashier Version: 12.9.1
- Laravel Version: 8.29.0
- PHP Version: 7.4.15
- Database Driver & Version: MySQL 5.7

### Description:
```
Integrity constraint violation: 1062 Duplicate entry '68-plan_0' for key 'subscription_items_subscription_id_stripe_plan_unique'
```

Shouldn't unique key be based on `subscription_id` and `stripe_id` rather than `subscription_id` and `stripe_plan`? It is currently possible to have that on the Stripe side, but isn't on cashier's.

### Steps To Reproduce:

1. Create a subscription of `plan1`
2. Swap the plan to `plan2`
3. Swap the plan to `plan1`
4. Swap the plan to `plan2`

**Comment by jameswilddev** [comment]
@oprypkhantc We've recently seen an error just like this but we're not exactly sure how it happened.  Did you find a workaround given the issue was closed?
