### ISSUE TITLE
Payments failed

### ISSUE THREAD

**Issue by Marcolino92** [laravel/cashier-stripe#1090]
- Cashier Version: 12.9
- Laravel Version: 8
- PHP Version: 7.3
- Database Driver & Version: MySQL

### Description:

Hi, I come to the point trying to explain myself better.
Premise: Let's assume that various attempts have been made to pay an invoice that a customer could not pay due to a credit card with insufficient balance has been stopped, removing the user's subscription and with a new attempt that will be carried out in a week.

The same user now makes a new subscription, paid successfully and therefore has an active subscription.

What happens with the other invoice that will have to retry if the user already has a new subscription?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
