### ISSUE TITLE
Receipt shows Subscription (1) and not the plan name

### ISSUE THREAD

**Issue by thomasrd1** [laravel/cashier-stripe#1097]
I have noticed this a few times. When a user subscribes to a plan. The plan name displays Subscription (1) in the receipt

https://imgur.com/a/km4SvSs

https://imgur.com/SZKURnF

But when the user changes plan, its correctly now shown the plan name

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.

**Comment by driesvints** [comment]
FYI, I sent in a PR for this: https://github.com/laravel/cashier-stripe/pull/1098

Please fill out the issue template next time, thanks.

**Comment by thomasrd1** [comment]
Thanks. 1st time poster.

**Comment by thomasrd1** [comment]
I'm still noticing the Subscription (1) text on new subscription receipts

Laravel v8.36.2
Laravel Cashier v12.11.0
Laravel Spark Stripe v1.0.11

![image](https://user-images.githubusercontent.com/48821914/114036220-3b8be280-98c3-11eb-8314-80e91df24838.png)

**Comment by driesvints** [comment]
Did you publish the template? You'll need to republish. It's working for me.

**Comment by thomasrd1** [comment]
Apologies. I didn't see that file.
Yes it is displaying the correct plan name now.
