### ISSUE TITLE
Cannot declare class error when using asStripeSubscription()

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [laravel/cashier-stripe#1101]
- Cashier Version: ^12.6
- Laravel Version: 8.22.1
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7.31

### Description:
I've asked about on various support forums and not gotten any help. I have a feeling it might be a bug. I might be missing something incredibly obvious, but I just cannot understand why I'd be having this issue.

I have a custom user model `Person` which is set up correctly (`CASHIER_MODEL: App\Models\Person`). Everything functions correctly until I try to do something using `asStripeSubscription()` and deploy. Locally everything works as expected, even with `asStripeSubscription()`, but as soon as it's deployed (even with **Travis CI** --  a totally standalone platform) then it fails. 

The error message is confusing:

> Cannot declare class App\Models\Person, because the name is already in use

It points to this line in the Person model:

    class Person extends Authenticatable
    {

I don't know why the presence of `asStripeSubscription()` and being deployed remotely would cause this error. Could it be that a new 12.6.x version of Cashier has introduced this issue?

**Comment by driesvints** [comment]
Please share the full stack trace.

**Comment by JohnnyWalkerDesign** [comment]
Hi, thanks. The weird thing is, that **is** the entire stack trace.

https://flareapp.io/share/Lm8OkBj5

**Comment by driesvints** [comment]
Tbh this doesn't seems like it has anything to do with Cashier. It just looks to me that there's another model in the same namespace with the same name.

**Comment by driesvints** [comment]
The only way to debug this is if you can reproduce this in a fresh Laravel repo. Otherwise I won't be able to help I'm afraid.

**Comment by JohnnyWalkerDesign** [comment]
I understand why you'd think that, but there's two things: It's only an error when deployed and when `asStripeSubscription()` is invoked. 

I can create subscriptions fine, whether deployed or on localhost. Everything works as expected in every way... until `asStripeSubscription()` is invoked on remote server.

I hope I'm missing something stupidly obvious here, but I cannot understand why only `asStripeSubscription()` would create this error.

**Comment by driesvints** [comment]
Did you define the env variable in all the environments which you're having issues with?

**Comment by driesvints** [comment]
And cleared config cache after changing the env variables?

**Comment by JohnnyWalkerDesign** [comment]
I believe so. In Laravel and Cashier works perfectly on the staging server and in Travis CI. I have 40 unit tests, all relating to being able to successfully register and subscribe via Cashier/Stripe. Everything functions perfectly. 

I've clear my caches deployed, still with the same error.

There's only a problem when `asStripeSubscription()` is called. I'm not even sure what ENV variable could result in the above error. If you remove `CASHIER_MODEL` all you get is a "Can't find App\Models\User", which is what you'd expect. How could an ENV variable lead to this particular error?

**Comment by driesvints** [comment]
I have no clue... I'm afraid I can't help you further here. I still believe this has nothing to do with Cashier. Perhaps try updating to the latest version of Cashier and Laravel to see if that helps? And try recreating this in a fresh app. If you can't then it's definitely something specific to the app you're developing. Sorry I couldn't be of more help here.

**Comment by JohnnyWalkerDesign** [comment]
Thanks for your help. The app itself is incredibly basic. It's primarily just a new Laravel install with Cashier added. Can you think of any fault in the code that would only lead to `asStripeSubscription()` thinking there was a duplicate model... whereas the rest of Laravel/Cashier (up to and including creating subscriptions) works fine without issue?

**Comment by JohnnyWalkerDesign** [comment]
@driesvints Could it be related to the following class?

`./vendor/stripe/stripe-php/lib/Person.php`
