### ISSUE TITLE
Add Support for canceling subscription at specific date and subscriptions with terms

### ISSUE THREAD

**Issue by OliverZiegler** [laravel/cashier-stripe#1105]
Use Cases: 
* We want to offer monthly payed subscriptions with different terms (3 Months, half year, year)
* different terms get different discounts (eg. different prices in stripe)
* subscriptions should only be cancelable term based (I cancel now but subscription needs to be active 2 more months with billings)
* Some subscriptions need to end automatically after one term

Technical:

Stripe offers the possibility to cancel a subscription automatically at a specific date via https://stripe.com/docs/api/subscriptions/object#subscription_object-cancel_at
and it would be nice to be able to use this in Cashier with all appropriate cashier subscription handling. 

What needs to be done (in my opinion, please amend):

* implement `cancelAt($date)` method to cancel a subscription at a specific predefined date
* add `term` method to define the term of the subscription
* handle `cancel` and `cancelNow` according to the defined term
* save the "cancel_at" in DB and set "ends_at" appropriate

If desired I could come up with a PR.

**Comment by driesvints** [comment]
Thanks, good suggestion. I've implemented this here: https://github.com/laravel/cashier-stripe/pull/1106. Cashier Paddle already had this functionality so it makes sense it makes it way to Cashier Stripe as well.

As for your "term" functionality that you required I'm not sure what you mean by that. Looks like you're requesting something similar as Subscription schedules? https://stripe.com/docs/billing/subscriptions/subscription-schedules
In any case this isn't something we're going to be implementing into Cashier directly, sorry.

**Comment by OliverZiegler** [comment]
Nice. Thanks for this fast response!

As for my "terms" it seems like this could be done with subscription schedules. 
Thanks for pointing this out, did not find it.
I will have a deeper look into that.

**Comment by ascentcreative** [comment]
Is it still the case that there's no plans to integrate with SubscriptionSchedules? I'm looking for something which would allow fixed term subscriptions, and this seems to be central to that.

**Comment by driesvints** [comment]
Not right now sorry.
