### ISSUE TITLE
Coupon for single charges

### ISSUE THREAD

**Issue by guianzollin** [laravel/cashier-stripe#1107]
It would be nice to be able to use the withCoupon method in single charges.

**Comment by driesvints** [comment]
Coupons for payment intents aren't supported by Stripe: https://support.stripe.com/questions/support-for-coupons-using-payment-intents-api

**Comment by guianzollin** [comment]
Can't we use Stripe Checkout for this?

https://stripe.com/docs/payments/checkout/discounts

**Comment by driesvints** [comment]
Hmm right. For Checkout it makes sense. I'll take a look at this at a later time but feel free to PR it if you want. I tink maybe moving the coupon/promotion code functionality from the `SubscriptionBuilder` into a concerns trait makes sense so it can be re-used in `PerformsCharges`.

**Comment by driesvints** [comment]
I've sent in a PR for this here: https://github.com/laravel/cashier-stripe/pull/1182
