### ISSUE TITLE
Cancel multiple subscription error

### ISSUE THREAD

**Issue by roman-briazgalov** [laravel/cashier-stripe#1108]
- Cashier Version: 12.10.0
- Laravel Version: 8.33.1
- PHP Version: 7.4.16
- Database Driver & Version: MongoDB 3.6.3

### Description:
I use Laravel framework, Cashier, MongoDB and Jenssegers/laravel-mongodb.
So i had to overwrite the Laravel\Cashier\Subscription and Laravel\Cashier\SubscriptionItem classes. But i don't think it could have influence, because it worked well before updating. After updating i have changed the overwritten classes.

I have updated Laravel framework from version 6 to 8 and Cashier from 10.5 to 12.8.
Cashier supports multiple subscriptions fron version 11. So the new collection subscription_items was created in DB.
I have not changed the process of subscription creration. But all the new subscriptions are created like the multiple: i mean that all records in _subscriptions_ collection looks like this:

```
{
    "_id": {
        "$oid": "XXXXXXXXXXXXXXXXXXX"
    },
    "name": "Premium",
    "stripe_status": "active",
    "trial_ends_at": null,
    "ends_at": null,
    "user_id": "XXXXXXXXXXXXXXXXXXX",
    "updated_at": {
        "$date": "2021-03-31T13:00:02.890Z"
    },
    "created_at": {
        "$date": "2021-03-31T13:00:02.890Z"
    }
}
```

As you see, here is no field _stripe_id_ as it was with Cashier version 10.
Related object was created in collection _subscription_items_:

```
{
    "_id": {
        "$oid": "XXXXXXXXXXXXXXXXXXX"
    },
    "stripe_id": "si_XXXXXXXXXX",
    "stripe_plan": "price_XXXXXXXXXXXXXXXXX",
    "quantity": 1,
    "subscription_id": "XXXXXXXXXXXXXXXXXXX",
    "updated_at": {
        "$date": "2021-03-31T13:00:02.891Z"
    },
    "created_at": {
        "$date": "2021-03-31T13:00:02.891Z"
    }
}
```
In _subscription_items_ we can find some _stripe_id_. But its not a subscription ID, it's ID of subscription item.
So when i try to cancel the current subscription i have error:
```
Stripe\Exception\UnexpectedValueException
Could not determine which URL to request: Stripe\Subscription instance has invalid ID:
```

If we see the stack trace we can find that the problem is in the Laravel\Cashier\Subscription class, in this function:
```
    public function asStripeSubscription(array $expand = [])
    {
        return StripeSubscription::retrieve(
            ['id' => $this->stripe_id, 'expand' => $expand], $this->owner->stripeOptions()
        );
    }
```

$this->stripe_id returns null, because the object of model Subscription doesn't have field _stripe_id_.
If i use $this->items->first->stripe_id, i get stripe ID  si_XXXXXXXXXX from collection, but i have another error:
```
Stripe\Exception\InvalidRequestException
No such subscription: 'si_XXXXXXXXXX'
```

So i have few questions:
1. How could i continue working with old subscribers, who have usual single subscriptions?
2. Can i continue working with usual single subscribtions instead of using multiple subscribtions (to not to use collection _subscription_items_)?

**Comment by driesvints** [comment]
Since you're using a DB engine which isn't supported by Laravel and have overwritten parts of the library we unfortunately cannot help you out. Please try a support channel instead:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.
