### ISSUE TITLE
No db record for one time price checkout

### ISSUE THREAD

**Issue by naumanzchaudhry** [laravel/cashier-stripe#1109]
- Cashier Version: 12.11.0
- Laravel Version: 6.20.22
- PHP Version: 7.3.23
- Database Driver & Version: MySQL

### Description:
I have got a product with two prices (recurring & one-time) defined in Stripe dashboard. I am using
 
`$user->checkout($priceId, $options)`

 After successful checkout, i can see data in my db for recurring price only but not for one time charge

### Steps To Reproduce:

0. Configure webhook endpoint in dashboard and necessary events. 
1. Add a Product in Stripe dashboard
2. Add 2 prices, one recurring and other one time
3. Use the `checkout($priceId, $options)` method on your billable model to get to the stripe checkout page
4. Do the recurring price checkout, after success, you will see your subscription data in database
5. Then, do the single price checkout, after success, **no record saved in db**

**Comment by driesvints** [comment]
Not sure what you're after here or why you'd want to save this into the database. Use the `invoices` method to see past one-time purchases.

**Comment by naumanzchaudhry** [comment]
@driesvints invoices only includes subscriptions

**Comment by driesvints** [comment]
I don't think so

**Comment by naumanzchaudhry** [comment]
> I don't think so

one time payments are listed in payments sections on dashboard but not under invoices section. only subscriptions are there
