### ISSUE TITLE
Subscription details do not get updated when changing subscription plan via customer portal

### ISSUE THREAD

**Issue by louis-l** [laravel/cashier-stripe#1111]
- Cashier Version: 12.10.0
- Laravel Version: 8.34.0
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:

Im not sure if this is a bug or something that is not supported. I try to test the subscription locally using Stripe CLI. New subscription works just fine (webhooks are sent and handled, new records are created in **subscriptions** and **subscription_items** correctly). But when I try to update subscription plan to a different plan (let say from plan A to plan B) via customer portal, everything works fine in Stripe GUI, but when I get redirected back to my app, my subscription plan is still A. I checked and nothing is changed in **subscriptions** and **subscription_items** table.

Here is the screenshot of the Stripe CLI webhooks that I received when changing the plan:
![Screen Shot 2021-04-03 at 5 34 35 pm](https://user-images.githubusercontent.com/10172565/113470826-1f8fd780-94a4-11eb-88ec-ef2cd3c16efd.png)

### Steps To Reproduce:

(described above)

---

I also checked the https://github.com/laravel/cashier-stripe/blob/12.x/src/Http/Controllers/WebhookController.php and it does not seem to handle any of the 3 events from the screenshot above.

Am I missing something or can you please point me to the right direction?

Thanks.

**Comment by driesvints** [comment]
Did you add all events to your webhook as detailed in the docs? https://laravel.com/docs/8.x/billing#handling-stripe-webhooks

![image](https://user-images.githubusercontent.com/594614/113472828-e6d10d80-9465-11eb-87a5-c4b8c551f26d.jpeg)

**Comment by louis-l** [comment]
Thanks @driesvints 

According to https://stripe.com/docs/webhooks/test 

> The Stripe CLI is the easiest and fastest method for testing your webhook endpoint. With the Stripe CLI you can begin listening for–and even triggering–events without any additional configuration.

So I thought we dont need to add any events in Stripe dashboard. That explains why when I first subscribed, it worked (e.g. new records got inserted in **subscriptions** and **subscription_items** tables)

**Comment by louis-l** [comment]
I also added 2 event listeners to listen to `WebhookReceived` and `WebhookHandled`, then log the entire payload to test if the webhooks are hitting my local app or not. And yes, its working, all the webhooks are received via Stripe CLI without any configuration.

**Comment by driesvints** [comment]
I'll need code to reproduce this. If you can give me that I'll try on Monday. Also tell me how you set up your products and prices.

**Comment by louis-l** [comment]
Here is the controller to generate checkout session (for new subscription):

```php
public function __invoke(Request $request)
{
    $checkout = $team
        ->newSubscription('default', 'price_xxx')
        ->allowPromotionCodes()
        ->checkout([
            'success_url' => 'my_url',
            'cancel_url' => 'my_url',
        ]);
    
    return response()->json([
        'sessionId' => $checkout->asStripeCheckoutSession()->id,
    ]);
}
```

Im using Vue for the front end, and here is where the session ID is used:

```js
redirectToStripeCheckoutUsingSessionId(sessionId) {
  const stripeKey = process.env.STRIPE_KEY

  window.Stripe(stripeKey)
    .redirectToCheckout({ sessionId })
    .then((result) => {
      if (result.error) {
        this.$alert(result.error.message, null, {
          confirmButtonText: this.$t('action.close'),
        })
      }
    })
},
```

This is the controlled to generate the Stripe Customer Portal url (for updating current subscription):

```php
public function __invoke(Request $request)
{
    return $this->response()->json([
        'url' => $team->billingPortalUrl('my_url'),
    ]);
}
```

And then in frontend app, just redirect to that `url` using `window.location.replace(url)`

---

For the setting up products and prices, basically I just follow Stripe docs:
- go to https://dashboard.stripe.com/test/products
- create 2 new products (called Business and Enterprise), each product has a standard price of fixed amount per month
- then update the settings in https://dashboard.stripe.com/test/settings/billing/portal (see screenshot below)

![Screen Shot 2021-04-04 at 8 03 10 am](https://user-images.githubusercontent.com/10172565/113492661-4a1d7700-951c-11eb-8a96-385ad02d6b6c.png)

Let me know if you need anything else.

**Comment by louis-l** [comment]
I do some more tests again and here is the Stripe webhooks that I received:

1. First subscribe to plan A
![1 - subscribe to plan A](https://user-images.githubusercontent.com/10172565/113522208-08ef9a80-95e2-11eb-8a65-840452d34678.png)

2. Update to plan B (higher price)
![2 - update to plan B](https://user-images.githubusercontent.com/10172565/113522215-1d339780-95e2-11eb-8698-1de373eac003.png)

3. Update back to plan A
![3 - update back to plan A](https://user-images.githubusercontent.com/10172565/113522216-245aa580-95e2-11eb-87ef-a8c9a380164f.png)

4. Cancel subscription
![4 - cancel plan A](https://user-images.githubusercontent.com/10172565/113522219-2ae91d00-95e2-11eb-8bc7-fd85d190f336.png)

---

All the steps worked just fine except for step 2.
Question is: should step 2 fire **customer.subscription.update** event?

**Comment by driesvints** [comment]
I just tested this myself and I can use the Stripe CLI's listen command just fine:

![Screenshot 2021-04-05 at 17 03 10](https://user-images.githubusercontent.com/594614/113588853-f2bcfb00-9630-11eb-9665-48b73177d1eb.jpg)

Since this isn't a support channel I can't help you out further. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks.

**Comment by louis-l** [comment]
Thanks @driesvints 

Im not sure how did you test this, but the issue here is not about testing Stripe CLI (e.g. receiving webhooks), its about updating subscription plan via Stripe Customer Portal and the change does not reflect in Cashier database.

If you have tested exactly the steps I described in https://github.com/laravel/cashier-stripe/issues/1111#issue-849595170 and it worked on your end, then please let me know and I will contact Stripe to see if they can help.

Cheers,

**Comment by driesvints** [comment]
Thanks for clarifying. I'll take another look later this week.

**Comment by driesvints** [comment]
I'm sorry but I can't reproduce this. Subscription record and item in the database are updated after switching plans. I'm using: `stripe listen --forward-to localhost:8000/stripe/webhook `

I'm afraid I can't help you out further here. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by louis-l** [comment]
Thanks @driesvints and appreciate you taking time testing this. I will contact Stripe to see if they can spot out anything.

Cheers
