### ISSUE TITLE
Calling latestInvoice() on a subscription with no invoice results in a type error

### ISSUE THREAD

**Issue by wsdimitri** [laravel/cashier-stripe#1112]
- Cashier Version: 12.11.0
- Laravel Version: 8.35.1
- PHP Version: 8.0.2

### Description:
If you have a Stripe subscription with a null `latest_invoice` (ie. by creating the subscription with a back dated start date), calling latestInvoice() will throw a TypeError. 

```
Laravel\Cashier\Invoice::__construct(): Argument #2 ($invoice) must be of type Stripe\Invoice, null given ...
```

I would think this should fail silently and return null?

### Steps To Reproduce:
1. Create a Stripe subscription with a `backdate_start_date`.
2. Load the subscription into your Cashier Subscription model. 
3. Call `latestInvoice()`.

**Comment by driesvints** [comment]
Thanks. I've sent in a fix here: https://github.com/laravel/cashier-stripe/pull/1115
