### ISSUE TITLE
Coupon label display in reciept

### ISSUE THREAD

**Issue by thomasrd1** [laravel/cashier-stripe#1117]
- Cashier Version: v12.11.0
- Laravel Version: v8.36.2
- Laravel Spark Stripe: v1.0.11
- PHP Version: 8.0
- Database Driver & Version: Mysql. 

### Description:

The receipt should show the friendly coupon discount details.

### Steps To Reproduce:

Create a coupon in Stripe
Create a subscription and apply a coupon in Laravel Spark Stripe
View receipt 

Cashier receipt 
![image](https://user-images.githubusercontent.com/48821914/114035322-56118c00-98c2-11eb-9f6e-4d47200cd942.png)

Stripe receipt
![image](https://user-images.githubusercontent.com/48821914/114035653-a557bc80-98c2-11eb-974e-f6198da9bf0c.png)

![image](https://user-images.githubusercontent.com/48821914/114035483-7b9e9580-98c2-11eb-80d8-dafaa82c1184.png)

**Comment by driesvints** [comment]
Thanks, I've sent in a PR for this here: https://github.com/laravel/cashier-stripe/pull/1118
