### ISSUE TITLE
Applying a coupon to a user (Customer) instead of a subscription

### ISSUE THREAD

**Issue by corsair** [laravel/cashier-stripe#1119]
I would like to request a way to apply a coupon directly to a Stripe customer account **instead of** being forced to do so directly to a singular subscription. This is vital for avoiding scenarios where a customer wants to upgrade from a monthly to an annual plan. If a coupon was previously applied and they attempt to change the subscription via different methods including Stripe's Customer Portal, it won't automatically transfer to the new plan.

As [documented](https://stripe.com/docs/billing/subscriptions/discounts#discounting-customers), the coupon can be applied either when [creating a user](https://stripe.com/docs/api/customers/create) or [updating](https://stripe.com/docs/api/customers/update) one.

This was suggested to me by their development team today.
![image](https://user-images.githubusercontent.com/1847891/114105940-951fed00-9882-11eb-89e7-423c5f567e15.png)

**Comment by driesvints** [comment]
```php
$user->newSubscription('default', 'your-price')->create('payment_method', [
     'coupon' => 'your coupon', // https://stripe.com/docs/api/customers/create#create_customer-coupon
     // other customer options
]);
```
