### ISSUE TITLE
Transaction is blocked in stripe but cashier subscription table not getting updated

### ISSUE THREAD

**Issue by poornimasudha** [laravel/cashier-stripe#1126]
- Cashier Version: 12.1
- Laravel Version: 7.0
- PHP Version: #.#.#
- Database Driver & Version:php myadmin -4.6.6deb5

### 
 I have created a daily billing price plan and subscribed for a user. After creating subscription I changed the default card to *4100000000000019* to test fraudulent transaction. In next billing cycle transaction is blocked in stripe but according to cashier subscription table this subscription is still active .

![billing](https://user-images.githubusercontent.com/33275075/114505774-7fc60c80-9c4e-11eb-8753-e9c214315db4.png)

**Comment by driesvints** [comment]
You might want to contact stripe about this as this isn't a Cashier issue. The subscription status is updated to whatever Stripe sends us in the subscription.updated webhook. We don't control what Stripe does to the subscription status for this.
