### ISSUE TITLE
Unexpected behaviour with onTrial method in Billable

### ISSUE THREAD

**Issue by benjamindoe** [laravel/cashier-stripe#1128]
- Cashier Version: 12.9.1
- Laravel Version: 7.30.4
- PHP Version: 7.4.16

### Description:

Not so much a bug as unexpected behaviour from the onTrial method.

I have a snippet of code that does something similar to the following:

```php
if ($user->onTrial()) {
    $trialEnd = $user->trialEndsAt()->format('d/m/y');
}
```
The behaviour I would expect is that the `onTrial` and `trialEndsAt` should both check and return the same date & time respectively. The issue in question arises when a user is on a generic trial and has a subscription that isn't on a trial.

`onTrial` first checks for generic trial *if* no arguments have been passed through. It then defaults to the subscription named `default` and checks that subscription for a trial.

`trialEndsAt` first checks the `default` subscription if there are no arguments passed through. If a trial doesn't exist there it falls back to generic trial.

The point I am trying to get across is that both `onTrial` and `trialEndsAt` should probably follow similar logic when it comes to checking for trials. Perhaps `onTrial` should call `trialEndsAt`?

**Comment by benjamindoe** [comment]
Happy to suggest a PR

**Comment by thomasrd1** [comment]
Are you also using Laravel Spark?

**Comment by benjamindoe** [comment]
No, custom build using Cashier directly

**Comment by driesvints** [comment]
So I first implemented this function here: https://github.com/laravel/cashier-stripe/pull/1000 and it was later fixed here: https://github.com/laravel/cashier-stripe/pull/1015

But it indeed seems to not account for your use case. I agree this should be fixed. Although I wouldn't immediately label this as a bug. Depending on the implementation this should got to either the current stable version or master.

**Comment by benjamindoe** [comment]
I'll send a PR to master then as  it's, although nuanced, a breaking change
