### ISSUE TITLE
Broader Extraction of Model Upserting

### ISSUE THREAD

**Issue by frankieeedeee** [laravel/cashier-stripe#1133]
Further to #1122 / #1124, I've been thinking about how we often see the same logic/code being reused in a few key places. Specifically, we see this code (or variants of it):

````php
// Taken from Laravel\Cashier\SubscriptionBuilder::createSubscription()

/** @var \Stripe\SubscriptionItem $firstItem */
$firstItem = $stripeSubscription->items->first();
$isSinglePlan = $stripeSubscription->items->count() === 1;

/** @var \Laravel\Cashier\Subscription $subscription */
$subscription = $this->owner->subscriptions()->create([
    'name' => $this->name,
    'stripe_id' => $stripeSubscription->id,
    'stripe_status' => $stripeSubscription->status,
    'stripe_plan' => $isSinglePlan ? $firstItem->plan->id : null,
    'quantity' => $isSinglePlan ? $firstItem->quantity : null,
    'trial_ends_at' => ! $this->skipTrial ? $this->trialExpires : null,
    'ends_at' => null,
]);

/** @var \Stripe\SubscriptionItem $item */
foreach ($stripeSubscription->items as $item) {
    $subscription->items()->create([
        'stripe_id' => $item->id,
        'stripe_plan' => $item->plan->id,
        'quantity' => $item->quantity,
    ]);
}
````

...used in:
- `Laravel\Cashier\SubscriptionBuilder::createSubscription()`
- `Laravel\Cashier\Http\Controllers\WebhookController::handleCustomerSubscriptionCreated()`
- `Laravel\Cashier\Http\Controllers\WebhookController::handleCustomerSubscriptionUpdated()`
- `Laravel\Cashier\Subscription::swap()`
- `Laravel\Cashier\Subscription::addPlan()`
- `Laravel\Cashier\Subscriptionitem::swap()`

Additionally in most of these cases, either a `Stripe\Subscription` or `Stripe\SubscriptionItem` instance is available. So given that, I'm wondering if there's any scope to extract this model logic into separate 'action' classes, like in other Laravel packages, or some other service class? I'd imagine this action class/contract would be generically focused on simply upserting the relevant models.

Not only would this logic be more testable, but this pattern would offer greater extensibility.

I.e, there could be scope for a consuming application to change the binding of the action contract, so that if the application wanted to track additional data locally in the database on changes to a subscription / subscription item, they could simply define their own implementation and register it with the container / Cashier.

Potentially looking at 13.x here, and would be happy to submit a PR for you guys to see what this might look like! Cheers!

**Comment by driesvints** [comment]
I don't think we're going to be making big changes here at the moment, sorry.
