### ISSUE TITLE
Add table name in scopeActive

### ISSUE THREAD

**Issue by mayken** [laravel/cashier-stripe#1138]
- Cashier Version: 12.12
- Laravel Version: 8
- PHP Version: 7.4
- Database Driver & Version:

### Description:
I want get all Active Subscriptions and joined another table but have error:
`Ambiguous column: 7 ERROR: column reference "created_at"`
in scopeActive the name of the table is not specified in class Laravel\Cashier\Subscription

**Comment by driesvints** [comment]
We don't have any plans for this atm. If you can provide a clean solution to this we're welcoming PRs.
