### ISSUE TITLE
Cashier payment confirmation page is not redirecting back.

### ISSUE THREAD

**Issue by Omar-Ess** [laravel/cashier-stripe#1139]
- Cashier Version: 12.12
- Laravel Version: 8.12
- PHP Version: 7.3
- Database Driver & Version:

### Description:
i don't know if i am missing something in the docs. but if i provided a redirect parameter to the **route('cashier.payment')** .  the user should be redirected to the given route once the payment is confirmed. but that actually does not happen the user keeps hanging in the confirmation page. a success message is shown tho . just the redirect that isn't working. 
and also the 'Go back button ' just redirects to the given route but without a success message appended to the url. so basically .  there is no way to detect for me if the payment went through successfully other than using webhooks which i am not intending to set up for this project.
** Edit the back button works . but i am wondering if the confirmation proccess should redirect back on it's own because i am depending on that message in the url . and the user after payment might not click the back button so i will never know if he's charged or not

### Steps To Reproduce:
return redirect()->route(
                    'cashier.payment',
                    [$this->order->payment_id, 'redirect' => route('home')]
                );

**Comment by driesvints** [comment]
Heya. It's intended that the redirect isn't done automatically. We want to show the success message to the user first.

**Comment by Omar-Ess** [comment]
yeah i get it . but it would be better if you added an option such as force redirect and leave the success message for the dev to do with it whatever he needs. because as i said the user might not even click the back button . thank you for your response tho
