### ISSUE TITLE
subscribed method fails if billable has more than one subscription

### ISSUE THREAD

**Issue by martinbean** [laravel/cashier-stripe#1140]
- Cashier Version: 12.13.0
- Laravel Version: 8.40.0
- PHP Version: 8.0.5
- Database Driver & Version: Postgres

### Description:
If a billable entity has more than one subscription (i.e. they were subscribed, subscription expires, they subscribe at a later date creating a new subscription) then the `subscribed` method fails.

Digging into the source code, it’s because the `subscribed` method calls upon the `subscription` method, which just naïvely fetches the first subscription with that name. In my case, the first subscription is the expired one.

This method should be changed to instead order subscriptions by newest first, so that the `subscription` (and in turn, `subscribed` method) are acting on the latest subscription for a billable entity; not the oldest.

### Steps To Reproduce:
1. Create an expired subscription for a billable entity.
2. Create an active subscription for a billable entity.
3. Call `subscribed` on the billable entity. Method should return `true` but in fact returns `false`.

**Comment by driesvints** [comment]
`$this->subscriptions` loads the eloquent models into a collection and right after the where condition is applied to that collection. Check the method right below the part you linked. That's the eloquent subscriptions relation with the created_at orderBy.

> This is causing an issue as the customer’s first subscription has ended, but their second one is active. However, Cashier is just checking the very first one.

This should really not be happening based on the current state of the code. The opposite should happen. Can you please check the created_at timestamps in the database like I asked? Thanks

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
