### ISSUE TITLE
Invoice.php: wrong discount

### ISSUE THREAD

**Issue by BubeDameKoenig** [laravel/cashier-stripe#1143]
- Cashier Version: 12.12.0

### Description:

On Stripe there is an option to create a coupon also only per plan. Currently, if you simply calculate the discount from the subtotal (as in the code), the discount on the receipt is too high. It would have to add the discount per line. All info is provided in the interface.

In the printscreen you can see that the promo code is actually only valid for the user plan and should be CHF 15.00.

Invoice.php - line 162
`if ($this->discountIsPercentage()) {
    return (int) round($this->invoice->subtotal * ($this->percentOff() / 100));
}`

![Bildschirmfoto 2021-05-10 um 07 17 06](https://user-images.githubusercontent.com/50578666/117609477-67b7af00-b160-11eb-9177-1d354608576b.png)
![Bildschirmfoto 2021-05-10 um 07 18 37](https://user-images.githubusercontent.com/50578666/117609483-68e8dc00-b160-11eb-8a26-8d0eb34c6c92.png)

**Comment by driesvints** [comment]
Stripe changed the way discounts work a bit. We can use this new field instead: https://stripe.com/docs/api/invoices/object

**Comment by driesvints** [comment]
Hmm, that won't work because we won't be able to display the percentages then. I'll need to check into multiple discount support.

**Comment by BubeDameKoenig** [comment]
for example: under "total_discount_amounts > amount" it shows you the total discount and you can take this field.

![Bildschirmfoto 2021-05-10 um 17 51 24](https://user-images.githubusercontent.com/50578666/117687976-a24d3600-b1b8-11eb-9bf9-a52f26c89962.png)

**Comment by driesvints** [comment]
We can't use that because we need to show the different discounts when there's multiple and the percentages etc. I'm checking into all this and hoping to have a solution soon.
