### ISSUE TITLE
STRIPE - Subscription plan only for 5 month - using Laravel Cashier (stripe).

### ISSUE THREAD

**Issue by brijesh1997** [laravel/cashier-stripe#1148]
- Cashier Version: "^12.13"
- Laravel Version: "^8.0"
- PHP Version: "^7.3"

Hi There!,

I have been wrote a code for create and active subscription plan using "Laravel cashier (stripe)" and It's working good but I want to add some conditions like "I want to active this plan only for 5 month". 

In the stripe documentation we can set "ITERATION" during create subscription plan, means If I want to create Subscription plan only for 5 month so I need to set "iteration : 5" (https://prnt.sc/12wnbez).

So here, in Laravel cashier how can I manage it?

Can you please give me any suggestion for this?

Thank you.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
