### ISSUE TITLE
noProrate() ignored in extendTrial()

### ISSUE THREAD

**Issue by quantumwebco** [laravel/cashier-stripe#1149]
Trying to reanchor subscription dates using a trial as per the stripe docs https://stripe.com/docs/billing/subscriptions/billing-cycle#using-a-trial-to-change-the-billing-cycle

In the extendTrial() method in the Laravel\Cashier\Subscription Model it would be nice if it respected the proration_behaviour property set with noProrate() so this could be done without having to replicate that method and add it manually

```$subscription->noProrate()->extendTrail($date);```
instead of
```
$subscription = Subscription::find(5);
$date = now()->addDays(35);
$stripeSub = $subscription->asStripeSubscription();
$stripeSub->proration_behavior = "none";
$stripeSub->trial_end = $date->getTimestamp();
$stripeSub->save();
$subscription->trial_ends_at = $date;
$subscription->save();
```

**Comment by driesvints** [comment]
Done: https://github.com/laravel/cashier-stripe/pull/1151

**Comment by quantumwebco** [comment]
Beast mode, thanks a lot!
