### ISSUE TITLE
Create customer without card token

### ISSUE THREAD

**Issue by aGervais** [laravel/cashier-stripe#115]
composer.lock:
- "name": "laravel/framework",
- "version": "v4.2.4",
- "name": "laravel/cashier",
- "version": "v2.0.4",

Following the docs @ http://laravel.com/docs/billing#no-card-up-front

When making the call to create the new customer without a credit card token:

```
$new_organization->subscription('my_base_plan')->create( null, [ 'email' => $admin_email ] );
```

I get the following exception:

```
exception 'Stripe_InvalidRequestError' with message 'Unrecognized request URL (GET: /v1/customers/cus_4gBqk967KwO5eJ/cards/).  Please see https://stripe.com/docs or we can help at https://support.stripe.com/.' in /vagrant/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php:153
Stack trace:
#0 /vagrant/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php(219): Stripe_ApiRequestor->handleApiError('{\n  "eerror": {\n....,404, Array)
#1 /vagrant/vendor/stripe/stripe-php/lib/Stripe/ApiRequestor.php(115): Stripe_ApiRequestor->_interpretResponse('{\n  "eerror": {\n....,404)
#2 /vagrant/vendor/stripe/stripe-php/lib/Stripe/List.php(33): Stripe_ApiRequestor->request('get', '/v1/customers/c...', NULL)
#3 /vagrant/vendor/laravel/cashier/src/Laravel/Cashier/StripeGateway.php(541): Stripe_List->retrieve(NULL)
#4 /vagrant/vendor/laravel/cashier/src/Laravel/Cashier/StripeGateway.php(481): Laravel\Cashier\StripeGateway->getLastFourCardDigits(Object(Laravel\Cashier\Customer))
#5 /vagrant/vendor/laravel/cashier/src/Laravel/Cashier/StripeGateway.php(106): Laravel\Cashier\StripeGateway->updateLocalStripeData(Object(Laravel\Cashier\Customer))
...
```

Of course; when I try with a valid token:

```
$new_organization->subscription('my_base_plan')->create( 'tok_14WpNK2aswUSbfJtwUIDDkYq', [ 'email' => $admin_email ] );
```

It works perfectly. Is there another method for creating a Stripe customer without the credit card token that I'm missing or is this a bug?

**Comment by coreation** [comment]
> Taylor's suggestion was to not create a subscription until the user is actually subscribing.
> 
> See the following issue he closed a while back.
> 
> #63

Thanks for the explanation, was wondering why some parts aren't in Cashier, always good to know the argumentation behind something.

**Comment by driesvints** [comment]
@coreation this is quite old and you're now able to create customers without a card up front: https://laravel.com/docs/5.7/billing#creating-customers
