### ISSUE TITLE
The payment attempt failed because additional action is required before it can be completed.

### ISSUE THREAD

**Issue by UndercoverNL** [laravel/cashier-stripe#1150]
- Cashier Version: 12.10
- Laravel Version: 7.30.4
- PHP Version: 7.2
- Database Driver & Version: MariaDB: 10.5.8

### Description:
I run into a problem when I am trying to make a 1 time charge of a saved card. Which is exactly the same issue as #743 
The system works when using a Stripe test card which is invalid or working in any way. But as soon as I try the cards which need a regulatory (3D Secure) it returns me this specific error in the console: 
_The payment attempt failed because additional action is required before it can be completed._

The situation is as followed:
I am saving a card input by using `stripe.confirmCardSetup(form.dataset.secret, {` which saves the card to Stripe. On a result.success a post requests get activated by using an ajax. I am passing the Payment Method ID true this ajax so this can be used to charge the card using ->charge

In the controller which gets activated by the POST ajax request I am charging the card by using

`$payment_id = $request->input('payment_id');
Auth::user()->charge($pricecents, $payment_id);`

But when I use 1 of [the following cards](https://user-images.githubusercontent.com/42718013/118402081-b4235300-b668-11eb-85c3-521f4c96a69a.png) (tried each one) it returns me the error above.

It asks me once to confirm the 3D Secure. When I fail the security check it returns me with an error, like it should. 
But when I do succeed the 3D Secure the process above fails and returns me the error.

This most likely happens because ->charge is used in a backend function which can't ask me to complete the 3D Secure. (At least that is what I guess).

Is there any way to fix this?

### Steps To Reproduce:
Using ->charge in a backend POST request on a card which needs 3D Secure confirmation.

**Comment by driesvints** [comment]
If you use an ajax request you need to indicate that the payment intent is created while being `off_session`. `->charge` is designed for a backend request upon form submission by default. 

```php
Auth::user()->charge($pricecents, $payment_id, ['off_session' => true]);
```

This isn't really meant to be part of Cashier docs or anything. Please read up with the Stripe docs: https://stripe.com/docs/api/payment_intents/create#create_payment_intent-off_session
