### ISSUE TITLE
Charge with Invoice quantity bug

### ISSUE THREAD

**Issue by ErnestStaug** [laravel/cashier-stripe#1153]
- Cashier Version: 12.13.1
- Laravel Version: 8.41.0
- PHP Version: 8
- Database Driver & Version: Mysql 8

### Description:
Cannot  single charge user with amount and quantity in same request.

I get error:
`You may only specify one of these parameters: amount, quantity.`

If `quantity` is specified there should be `unit_amount` as per stripe [documentation](https://stripe.com/docs/api/invoiceitems/create#create_invoiceitem-unit_amount). Therefore both things cannot exist in same array when we create "Tab"/"StripeInvoiceItem"

### Steps To Reproduce:

Just try second example in Laravel [documentation](https://laravel.com/docs/8.x/billing#charge-with-invoice)

**Comment by driesvints** [comment]
I'm checking into this with Stripe. These parameters are super confusing to me.

**Comment by driesvints** [comment]
I've sent in a fix for this: https://github.com/laravel/cashier-stripe/pull/1161
