### ISSUE TITLE
reportUsage rate limiting

### ISSUE THREAD

**Issue by mattkingshott** [laravel/cashier-stripe#1154]
Stripe imposes a rate limit (100 calls per second) on the create usage record endpoint used by Cashier’s `reportUsage` methods (see metered billing). 

For many applications, this limit is unlikely to be an issue. However, for larger applications that might experience surging, it is possible that this rate limit will be hit. 

While it is of course possible to get around this problem within our applications using a variety of approaches e.g. rate limited job middleware, storing usage records in the database and then chunking through them, etc… i’m curious if @driesvints feels there is a better way and whether it is something that should become part of Cashier itself. 

Thanks!

**Comment by driesvints** [comment]
Afaik rate-limiting is for the entire Stripe API, not just the create usage record endpoint: https://stripe.com/docs/rate-limits

I personally think this shouldn't be a responsibility of Cashier per-se. Although if anyone wants to work on a PR to propose something concrete they can send in a PR. 

The main difficulty lies in the fact that there would need to be some sort of way to count the requests sent to Stripe and handle them gracefully. See https://stripe.com/docs/rate-limits#handling-limiting-gracefully. This sounds like a complex problem to tackle and I don't think we'll be putting in time into this ourselves atm, sorry.
