### ISSUE TITLE
Trial end date exception with stripe checkout subscription when using 'trialDays(2)' methond on subscription 

### ISSUE THREAD

**Issue by mohsinaliryk** [laravel/cashier-stripe#1156]
- Cashier Version: 12.13.1
- Laravel Version: 8.41.0
- PHP Version: 7.4.6
- Database Driver & Version:  mysql 7.4.6

### Description:
I'm getting the following exception message when I try to use trialDays(2) on checkout subscription. 

> The `trial_end` date has to be at least 2 days in the future.

**After some research I find that there is 3s difference between API request timestamp in stripe error log and 'trial_end' parameter.**

### My code snippet that produces this error:

```
$trial_checkout = $user->newSubscription('default', config('app.stripe_price_id'))->trialDays(2)->checkout($redirects);
```

**Comment by mohsinaliryk** [comment]
> That's odd since there's a failsafe for this right here which provides exactly 2 days of trial time at a minimum: https://github.com/laravel/cashier-stripe/blob/12.x/src/SubscriptionBuilder.php#L373-L378
> 
> I wonder if we should add like a minute of extra time for the API request delay. Can you try to see if the following works for you?
> 
> ```
> $trial_checkout = $user->newSubscription('default', config('app.stripe_price_id'))
>     ->trialDays(Carbon::now()->addDays(2)->addMinute())
>     ->checkout($redirects);
> ```

Yes I managed to resolve the issue by adding 10  seconds. 

$trial_checkout = $user->newSubscription('default', config('app.stripe_price_id'))
             ->trialUntil(Carbon::now()->addDays(2)->addSeconds(10))->checkout($redirects);

**Comment by driesvints** [comment]
Sent in https://github.com/laravel/cashier-stripe/pull/1160 for this
