### ISSUE TITLE
hasIncompletePayment returns false for failing single charges

### ISSUE THREAD

**Issue by mattkingshott** [laravel/cashier-stripe#1159]
- Cashier Version: 12.13.1
- Laravel Version: 8.41.0
- PHP Version: 8.0.5
- Database Driver & Version: MySQL 8.0.23

### Description:

After making a single charge using a Stripe test card that requires [further payment confirmation](https://laravel.com/docs/8.x/billing#strong-customer-authentication), the `hasIncompletePayment` method returns `false`. In addition, the `latestPayment` method returns `null`. 

Evidently, the focus of these methods is on subscriptions, rather than single charges. Since this is the case, how do I check whether a single charge has succeeded or not e.g. within a controller or middleware.

### Steps To Reproduce:

Attempt to make a single charge using the following card `4000 0027 6000 3184`, then call `$user->hasIncompletePayment()`

**Comment by driesvints** [comment]
Hi Matt. `hasIncompletePayment` is only available for subscriptions like you pointed out.

> Since this is the case, how do I check whether a single charge has succeeded or not e.g. within a controller or middleware.

Single charges are already immediately checked when performing them, see https://github.com/laravel/cashier-stripe/blob/12.x/src/Concerns/PerformsCharges.php#L49

If you want to check for *any* failed payment that's a bit out of scope for Cashier. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

**Comment by driesvints** [comment]
Also, I believe it's obvious from the docs that `hasIncompletePayment` is only available for subscriptions. If it isn't for you then we welcome PR's to improve them 👍

**Comment by mattkingshott** [comment]
Thanks for the feedback.
