### ISSUE TITLE
Cashier methods trigger LazyLoadingViolationException

### ISSUE THREAD

**Issue by mattkingshott** [laravel/cashier-stripe#1172]
- Cashier Version: 12.14.0
- Laravel Version: 8.43.0
- PHP Version: 8.0.6
- Database Driver & Version: MySQL 8.0.23

### Description:

Laravel's recently released feature for [preventing lazy-loading](https://laravel.com/docs/8.x/eloquent-relationships#preventing-lazy-loading) of Eloquent models triggers a `LazyLoadingViolationException` when attempting to call `hasIncompletePayment()`.

There are undoubtedly other areas of Cashier, and other first-party Laravel packages, that will trigger similar exceptions. I'm curious what the strategy is to handle situations like this when the offending code is in a vendor package?

Thanks!

### Steps To Reproduce:

Call `hasIncompletePayment()` after setting `Model::preventLazyLoading()`

**Comment by themsaid** [comment]
I can't replicate this. Please share the full stack trace.

**Comment by mattkingshott** [comment]
Sorry, I can't figure out how to get Ignition to just print out the stack trace as text.

Here's a screenshot though...

<img width="1270" alt="Screenshot 2021-05-27 at 3 45 10 pm" src="https://user-images.githubusercontent.com/51963402/119847219-b4daa580-bf02-11eb-8943-8d57b8df0204.png">

**Comment by driesvints** [comment]
Add `protected $with = ['subscriptions'];` to your billable model. By default this isn't done because we can't add this through the trait.

**Comment by mattkingshott** [comment]
Great! Thanks @driesvints 👍🏻

**Comment by mattkingshott** [comment]
I may be wrong, but I'm not sure how you can eager load the 'owner' relationship method `Laravel\Cashier\Subscription` without creating an infinite loop.

**Comment by driesvints** [comment]
You indeed can't.

**Comment by mattkingshott** [comment]
So, does that therefore mean you cannot `preventLazyLoading` when using Cashier?

I did find a solution, but far from ideal:

```php
    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::retrieved(function($subscription) {
            $model = new User();

            $model->fill((array) DB::table('users')->where('id', $subscription->user_id)->first());

            $subscription->setRelation('owner', $model);
        });
    }
```

**Comment by driesvints** [comment]
I'm not sure what you're talking about? The owner isn't eager loaded on the subscription model.

**Comment by mattkingshott** [comment]
Correct, owner is not eager loaded, so when Cashier attempts to access it, Laravel throws a lazy loaded exception.

 If you try to eager load it from the Billable model e.g. protected $with = ['subscriptions.owner'];

then it loads the owner, which in turn tries to eager load the subscriptions, which then tries to eager load the owner, and you get an infinite loop. 

I hope that makes sense. Thanks!

**Comment by driesvints** [comment]
I'm sorry but I still don't understand. Can you give a practical code example to demonstrate what's going wrong for you?

**Comment by mattkingshott** [comment]
Sure thing...

Here's the `Billable` model:

```php
class User extends Model
{
    use Billable;
    
    protected $with = [
        'subscriptions',
    ];
}
```

Then within my application, I run the following code:

```php
$billing_date = User::first()->subscription()->asStripeSubscription()->current_period_end;
```

This results in the following exception:

```php
Illuminate\Database\LazyLoadingViolationException

Attempted to lazy load [owner] on model [Laravel\Cashier\Subscription] but lazy loading is disabled.
```

This makes sense as the `asStripeSubscription()` method is trying to lazy load the `owner` relationship:

```php
public function asStripeSubscription(array $expand = [])
{
    return StripeSubscription::retrieve(
        ['id' => $this->stripe_id, 'expand' => $expand], $this->owner->stripeOptions()
    );
}
```

If I try to eager load the `owner` relationship (by modifying the `Billable` model):

```php
class User extends Model
{
    use Billable;
    
    protected $with = [
        'subscriptions.owner',
    ];
}
```

Laravel gets stuck in an circular loop because eager loading `owner` triggers it to eager load `subscriptions` on the `Billable` model, which then tries to eager load `owner` again, and so on.

The only way I found to bypass this issue was to use the `retrieved` model event to manually set the relation for `owner`, so Laravel doesn't need to lazy load it:

```php
protected static function booted()
{
    static::retrieved(function($subscription) {
        $model = new User();

        $model->fill((array) DB::table('users')->where('id', $subscription->user_id)->first());

        $subscription->setRelation('owner', $model);
    });
}
```

However, as I mentioned before, this isn't a very clean way of solving the problem.

Hope that makes things clearer. I appreciate your time :)

**Comment by driesvints** [comment]
Thanks @mattkingshott, that was super helpful. I forgot about the internal owner calls. 

I think there's nothing we can do about this I'm afraid... Cashier was specifically designed this way and we can't change this. 

Taylor did add a new way to work with the lazy loading warning and that is to log instead of throwing an exception. Check out:

![image](https://user-images.githubusercontent.com/594614/119867257-fc225f80-bf1d-11eb-89d4-b274d8c6ff65.jpeg)

**Comment by mattkingshott** [comment]
Glad it helped.

Maybe then the solution is to use that handle method to only throw exceptions on my own models and silently ignore vendor models such as Subscription. 

That sounds like an acceptable way to do it. 

Thanks again!

**Comment by mattkingshott** [comment]
For anyone following along, here's the solution I came up with:

```php
Model::preventLazyLoading(! app()->isProduction());

Model::handleLazyLoadingViolationUsing(function($model, $relation) {
    $class = $model->$relation()->getRelated();

    if (Str::startsWith(get_class($class), 'App\\Models')) {
        throw new LazyLoadingViolationException($model, $relation);
    }
});
```

It works by checking if `$relation` refers to one of my application models (they all use the `App\Models` namespace). 

If it does, it throws an exception, as it means I've introduced lazy loading. By contrast, vendor models that exist outside of the `App\Models` namespace will be ignored.

**Comment by khalyomede** [comment]
Thanks @mattkingshott, I took inspiration from your suggestion, and modified it to still be able to detect these kind of issues for other packages, in order to be able to open issues for the packages maintainers and let them know (always useful to report if it can help improve performance for all users).

```php
Model::handleLazyLoadingViolationUsing(function ($model, $relation): void {
  if ($model instanceof Laravel\Cashier\Subscription) {
    return;
  }
});
```
