### ISSUE TITLE
Support for creating a metered subscription on an existing subscription.

### ISSUE THREAD

**Issue by kyranb** [laravel/cashier-stripe#1175]
Cashier currently has the `meteredPlan()` helper, although with the current documentation it's not clear that one can add a metered plan to an existing subscription by passing in `null` as the quantity.

`subscription('default')->addPlan('plan_price_id', null);`

Would it be worth adding an `addMeteredPlan()` method to make this more readable?

**Comment by driesvints** [comment]
Good call. I sent this in for the Cashier v13 release which will be released shortly: https://github.com/laravel/cashier-stripe/pull/1177. Thanks.
