### ISSUE TITLE
[13.x] Adding metered product to existing subscription fails due to quantity key being present

### ISSUE THREAD

**Issue by hailwood** [laravel/cashier-stripe#1187]
- Cashier Version: 13.0.0
- Laravel Version: 8.46.0
- PHP Version: 8.0.3
- Database Driver & Version: Mysql 8

### Description:
Seems like stripe doesn't like us sending across `quantity` as `null`. It wants either an integer or the key missing entirely.

If we [filter this array](https://github.com/laravel/cashier-stripe/blob/13.x/src/Subscription.php#L833-L840) to remove null values the subscription is updated as intended.

If we do not then we get a Stripe exception `Stripe\Exception\InvalidRequestException` with the message
> Invalid integer: 

#### Stacktrace

```
/app/vendor/stripe/stripe-php/lib/Exception/InvalidRequestException.php:35
--
/app/vendor/stripe/stripe-php/lib/ApiRequestor.php:189
/app/vendor/stripe/stripe-php/lib/ApiRequestor.php:151
/app/vendor/stripe/stripe-php/lib/ApiRequestor.php:489
/app/vendor/stripe/stripe-php/lib/ApiRequestor.php:120
/app/vendor/stripe/stripe-php/lib/BaseStripeClient.php:134
/app/vendor/stripe/stripe-php/lib/Service/AbstractService.php:59
/app/vendor/stripe/stripe-php/lib/Service/SubscriptionItemService.php:62
/app/vendor/laravel/cashier/src/Subscription.php:834
/app/vendor/laravel/cashier/src/Subscription.php:890
```

This is not an issue when creating a new subscription as [we only add the quantity key if the value is not null](https://github.com/laravel/cashier-stripe/blob/13.x/src/SubscriptionBuilder.php#L100-L102).

### Steps To Reproduce:
1. Create a subscription with an existing product
2. Attempt to update the subscription to add an additional metered product

```php
$billable->subscription()->addMeteredPrice('price_ab123');
```

**Comment by driesvints** [comment]
Urgh, should have added a test for that. Thanks @hailwood.
