### ISSUE TITLE
Swapping the price of a subscription explicitly removes the ends_at date of that subscription

### ISSUE THREAD

**Issue by anderscodes** [laravel/cashier-stripe#1192]
- Cashier Version: 12.8
- Laravel Version: 8.0
- PHP Version: 7.4
- Database Driver & Version: mysql

### Description:

When swapping a price for a subscription, the ends_at date is explicitly set to null. This has the effect of re-subscribing any customers who have previously unsubscribed. 

When swapping a plan the date that the customer has cancelled their plan should be preserved.

[Link to source code](https://github.com/laravel/cashier-stripe/blob/13.x/src/Subscription.php#L686)

```
  $this->fill([
            'stripe_status' => $stripeSubscription->status,
            'stripe_plan' => $isSinglePlan ? $firstItem->plan->id : null,
            'quantity' => $isSinglePlan ? $firstItem->quantity : null,
            'ends_at' => null,
        ])->save();
```

### Steps To Reproduce:

1. Subscribe a user
2. Cancel their subscription (set to cancel at the end of the period).
3. Swap their plan `$subscription->swap($newPlan)`
4. Check the stripe request, the `ends_at` field is updated to null

**Comment by driesvints** [comment]
Hey @anderscodes. I don't think I agree here. Swapping plans is a conscious choice made by the user and its intent is to re-subscribe the user when swapping plans while having previously cancelled. This has never come up before that it's not the intended behavior.

Can you maybe elaborate more about your use case?

**Comment by anderscodes** [comment]
Hi Dries, thanks for your speedy response. 

The scenario we have encountered here is one where the pricing model of our app has changed and therefore we needed to update all users subscriptions to be on the new pricing plan. We used the swap method which re-subscribed users who had previously cancelled.

I appreciate what you are saying about your intended use case but I feel this could be made more explicit, either by resubscribing only with the inclusion of an optional parameter or by separating it out into a `swapAndResubscribe()` method.  

At the very least I feel this should be added to the documentation as I don't think its obvious without looking at the source code.

**Comment by driesvints** [comment]
> The scenario we have encountered here is one where the pricing model of our app has changed and therefore we needed to update all users subscriptions to be on the new pricing plan. 

So, what I would do is not move the cancelled users to the new prices. If they're on an old legacy price you should simple implement a check to not allow them to resume their subscription when they want. They'll need to subscribe anew on one of the newer plans. The way Stripe works also assumes that you don't change anything to cancelled user's prices. The price objects don't go away on Stripe, you can always reference them in the dashboard. Also for historical purposes it's best to know on which legacy price a customer cancelled.

I'm sorry to say this but I think we won't be making any changes to the docs or the library itself as I believe this isn't a valid use case. If you still feel that this is something you need I think it's best that you fork the library and make the custom changes you need.

**Comment by anderscodes** [comment]
I appreciate what you are saying about the intended use case and your suggestion of not swapping the plan on cancelled user sounds like a good solution going forwards. However I would encourage you to re-consider updating the documentation. 

If I can draw a parallel to the trial end date, there is an explicit method to determine whether to skip the trial when updating to a new pricing plan. If the user is on a trial we do not assume whether we should skip the trial or not. If we are being explicit about updating the start date when swapping the plan, for consistency should we not be explicit about updating the end date?

The subscription start and end date should not be dependent on the price the customer pays or if that has been updated or not. These are separate concerns so if we are catering to a specific use case that combines the two we should explicitly state that.

**Comment by driesvints** [comment]
Hey @anderscodes. I'm sorry but I'm going to leave things be here. If you really believe anything should be adjusted feel free to attempt PR's but I can't promise those would get accepted.
