### ISSUE TITLE
Call to usageRecords returns error

### ISSUE THREAD

**Issue by mParkesy** [laravel/cashier-stripe#1194]
I have successfully changed my billable model from "User" to "Organisation" and I am now creating a page that shows usage for a subscription.

When I call on usageRecordsFor() or usageRecords() i receive this error:
https://flareapp.io/share/Vme63rrP#F51

Having debugged this for a while now and broken down the functions from the source code, but don't see for the issue could be.

Is it related to setting the correct billable model? I have set it to "Organisation" in my environment variables.

EDIT

See controller code below:
```
    public function create()
    {
        $user = auth()->user();
        $organisation_id = $user->organisations_id;
        $organisation = Organisation::findOrFail($organisation_id);

        
        $subscription = $organisation->subscriptions->first();
        
        // $owner = $subscription->owner();
        $usageRecords = $subscription->usageRecords([], "price_1J17KGCNdM1zhMQJrrCOPPTZ");
        
        // $item = $subscription->findItemOrFail("price_1J17KGCNdM1zhMQJrrCOPPTZ" ?? $subscription->stripe_price);
        // $usage = $item->usageRecords();
        return view('dashboard.myorganisation', [
            "organisation" => $organisation,
            "usage" =>$usageRecords,
        ]);
    }
```

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template
