### ISSUE TITLE
Call to usageRecords returns error

### ISSUE THREAD

**Issue by mParkesy** [laravel/cashier-stripe#1195]
- Cashier Version: 13.0
- Laravel Version: 8.40
- PHP Version: 8.0.6
- Database Driver & Version: 10.4.19-MariaDB

### Description:
I have successfully changed my billable model from "User" to "Organisation" and I am now creating a page that shows usage for a subscription.

When I call on usageRecordsFor() or usageRecords() i receive this error:
https://flareapp.io/share/Vme63rrP#F51

Having debugged this for a while now and broken down the functions from the source code, but don't see for the issue could be.

Is it related to setting the correct billable model? I have set it to "Organisation" in my environment variables.

EDIT

See controller code below:

### Steps To Reproduce:
```
    public function create()
    {
        $user = auth()->user();
        $organisation_id = $user->organisations_id;
        $organisation = Organisation::findOrFail($organisation_id);

        
        $subscription = $organisation->subscriptions->first();
        
        // $owner = $subscription->owner();
        $usageRecords = $subscription->usageRecords([], "price_1J17KGCNdM1zhMQJrrCOPPTZ");
        
        // $item = $subscription->findItemOrFail("price_1J17KGCNdM1zhMQJrrCOPPTZ" ?? $subscription->stripe_price);
        // $usage = $item->usageRecords();
        return view('dashboard.myorganisation', [
            "organisation" => $organisation,
            "usage" =>$usageRecords,
        ]);
    }
```

**Comment by driesvints** [comment]
Did you:

1. Set the custom model with `Cashier::useCustomerModel(Organisation::class);` in your app service provider? https://laravel.com/docs/8.x/billing#billable-model
2. Update the `subscriptions` table column to reference the new model with it's proper foreign key name as the note on the above link says? (see below)

![Screen Shot 2021-06-17 at 09 37 44](https://user-images.githubusercontent.com/594614/122352844-c5090200-cf4f-11eb-9e4e-7bf0f1bdd93c.jpg)

**Comment by driesvints** [comment]
> I have set it to "Organisation" in my environment variables.

This shouldn't be necessary with Cashier v13 any more. Did you read the upgrade guide for v13? https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#billable-model-customization-changes

**Comment by mParkesy** [comment]
Thanks for the reply and sorry for my vagueness.

1.  Yes I have done this and can confirm its working.
2. Yes, I have a subscription row in the database which has an organisation_id column and this correctly assigned from when a User and Organisation were saved. I can also get an organisations subscriptions fine via my model.

Looking into the code a little more it looks as though the usageRecords function in SubscriptionItem.php calls on a subscription owner:
```
public function usageRecords($options = [])
{
    return new Collection($this->subscription->owner->stripe()->subscriptionItems->allUsageRecordSummaries(
        $this->stripe_id, $options
    )->data);
}

```
for me "owner" does not return anything whereas "owner()" does when I call the method on a subscription object.

Thanks for your help so far.

**Comment by driesvints** [comment]
The thing is that we have a test that verifies that this works: 

https://github.com/laravel/cashier-stripe/blob/688204edc7567b5c6516512d61672b6921f1d01b/tests/Feature/MeteredBillingTest.php#L128

So there's something specific in your app that doesn't work. I'll need you to create a fresh app for me to reproduce this. Can you please create a repository with the command below, commit the code that reproduces the issue and share the repository here? Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com) properly set up.

```bash
laravel new bug-report --github="--public"
```

Please do not amend and create a separate commit with your custom changes. After you've posted the repository, I'll try to reproduce the issue.

Thanks!

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.
