### ISSUE TITLE
Extend from Cashier/Subscription throws error when using HasFactory trait

### ISSUE THREAD

**Issue by Muneeb-Ahmed-Khan** [laravel/cashier-stripe#1199]
- Cashier Version: 13.1
- Laravel Version: 8.12
- PHP Version: 8.0

### Description:

I created a new model called subscription, followed steps to add it into AppServiceProvider. 
![image](https://user-images.githubusercontent.com/49415395/122380161-05cd3f00-cf81-11eb-8798-81ddfd13c261.png)

After that I extended the model from Cashier/Subscription.
![image](https://user-images.githubusercontent.com/49415395/122381402-51341d00-cf82-11eb-928e-6bc1770c162a.png)

But when I run php artisan serve and the program gets to a point where it use this subscription model.
it throws this error.

Access level to Illuminate\Database\Eloquent\Factories\HasFactory::newFactory() must be public (as in class Laravel\Cashier\Subscription)
![image](https://user-images.githubusercontent.com/49415395/122381157-0a462780-cf82-11eb-8922-26d2f6314678.png)
The funny thing is that is says there is error on line 27 but there is no line 27 in my subscription model.

**Comment by Muneeb-Ahmed-Khan** [comment]
After removing HasFactory traits from both extended models, the error is gone.
Anyone, please confirm to me whether by removing HasFactory from both models is correct step or not ?

**Comment by driesvints** [comment]
Thanks. These methods indeed don't have the correct visibility.

**Comment by driesvints** [comment]
Will be in the next release. Thanks for reporting!
