### ISSUE TITLE
 when i make a plan in INR currency that that it work find but when i use USD currency that time this error comes The payment attempt failed because of an invalid payment method.

### ISSUE THREAD

**Issue by dhirajthakare** [laravel/cashier-stripe#1203]
and my code is like that 

  $plan = Plan::findOrFail($request->get('plan'));
        
        $user = $request->user();
        $paymentMethod = $request->paymentMethod;

        $user->createOrGetStripeCustomer();
        $user->updateDefaultPaymentMethod($paymentMethod);
        $user->newSubscription('default', $plan->stripe_plan)
            ->create($paymentMethod, [
                'email' => $user->email,
            ]);

i am not finding why this is happening please tell me solution if i  make a plan INR currency then it working find but when i make a plan on USD currency that time this problems comes

**Comment by driesvints** [comment]
Resubmit this with a filled out issue template
