### ISSUE TITLE
invoiceFor() fails when automatic tax calculation is enabled

### ISSUE THREAD

**Issue by josiasmontag** [laravel/cashier-stripe#1204]
- Cashier Version: master and 13.1.0
- Laravel Version: 8.47.0
- PHP Version: 8.0.3
- Database Driver & Version: 

### Description:

As soon as automatic tax calculation is enabled, the `invoiceFor()` method stops working.

This happens both with version `13.1.0` and the current master branch.

### Steps To Reproduce:

Add this test case to cashier-stripe (master):

```php
$user = $this->createCustomer('customer_can_be_invoiced');
$user->createAsStripeCustomer();
$user->updateDefaultPaymentMethod('pm_card_visa');


$invoice = $user->invoiceFor('Laracon', 49900);
// works
$this->assertInstanceOf(Invoice::class, $invoice);

Cashier::calculateTaxes();

$invoiceWithTax = $user->invoiceFor('Laracon', 49900);
// fails (returns false)
$this->assertInstanceOf(Invoice::class, $invoiceWithTax);
```

### Reason

When using automatic tax calculation, Stripe requires that `tax_behavior` for the invoice item price is set.
Instead of [using `amount`](https://github.com/laravel/cashier-stripe/blob/8ff63ccb31a06183ad7b14d46612aa401dd041d8/src/Concerns/ManagesInvoices.php#L38) for invoice items we should switch to use `price_data` ([Stripe docs](https://stripe.com/docs/api/invoiceitems/create#create_invoiceitem-price_data)):

```php
$options['price_data'] = [
   'unit_amount' => ...,
   'tax_behavior' => 'exclusive',
...
];
```

**Comment by driesvints** [comment]
@josiasmontag are you enrolled in the Stripe Tax program? It's currently invite only.

**Comment by driesvints** [comment]
Also: `Cashier::calculateTaxes();` isn't available in 13.1 yet. It's not yet released. Are you sure you're on the right version?

**Comment by josiasmontag** [comment]
Yes, I am. When you submit the form on the Stipe website you get invited within a few hours.

As mentioned the same happens with 13.1.

Steps to reproduce:

```php

$user = $this->createCustomer('customer_can_be_invoiced');
$user->createAsStripeCustomer();
$user->updateDefaultPaymentMethod('pm_card_visa');


$invoice = $user->invoiceFor('Laracon', 49900);
// works
$this->assertInstanceOf(Invoice::class, $invoice);

$invoiceWithTax = $user->withTax()->invoiceFor('Laracon', 49900);
// fails (returns false)
$this->assertInstanceOf(Invoice::class, $invoiceWithTax);

```

**Comment by driesvints** [comment]
Thanks for making me aware @josiasmontag. For now, in the short amount of time I have available, this is the best solution I can come up with: https://github.com/laravel/cashier-stripe/pull/1206

I'll need to think more thoroughly about the use of `tax_behavior` in combination with new API's. I've also updated the docs to warn about this: https://github.com/laravel/docs/pull/7145
