### ISSUE TITLE
[13.X] Issue with collectTaxIds() method

### ISSUE THREAD

**Issue by YannickYayo** [laravel/cashier-stripe#1208]
- Cashier Version: 13.2.0
- Laravel Version: 8.48.1
- PHP Version: 7.4.19
- Database Driver & Version: mariadb 10.6

### Description:
I am using the Stripe Checkout, and i want to allow companies to enter their Tax ID. Following the doc, i used the `collectTaxIds()` method :
``` php
auth()->user()
        ->collectTaxIds() // here
        ->allowPromotionCodes()
        ->checkout(
            [
                [
                    'price' => Price::find($this->stripePriceChoosen)->price_id,
                    'quantity' => 1,
                    'tax_rates' => [Tax::active()->french()->first()->tax_id],
                ],
            ],
            [
                'success_url' => route('stripe-payment', [
                    'advertisement' => $this->advertisement->id,
                    'status' => 'success',
                ]),
                'cancel_url' => route('stripe-payment', [
                    'advertisement' => $this->advertisement->id,
                    'status' => 'cancel',
                ]),
            ]
        );
```

After that, i'm receiving this error from Stripe : 
``` json
{
  "error": {
    "message": "Invalid object",
    "param": "tax_id_collection",
    "type": "invalid_request_error"
  }
}
```

Cashier, in the checkout session's data is making the `tax_id_collection` to true, but following those documentation : 
[Stripe Api](https://stripe.com/docs/api/checkout/sessions/create?lang=curl#create_checkout_session-line_items-tax_rates)
[Stripe doc](https://stripe.com/docs/tax/checkout/tax-ids)
`tax_id_collection` must be an associative array, with the key `enable` to true : 
``` php
// before 
[
  'success_url' => 'https://example.com/success',
  'cancel_url' => 'https://example.com/cancel',
  'allow_promotion_codes' => true,
  'payment_method_types' => ['card'],
  'line_items' => [
    [
      'price' => 'price_H5ggYwtDq4fbrJ',
      'quantity' => 2,
      'tax_rates' => ['txr_1J5Z0LB6GOVAU4psl08YX3r6']
    ],
  ],
  'mode' => 'payment',
  'tax_id_collection' => true // here
]

// after
[
  'success_url' => 'https://example.com/success',
  'cancel_url' => 'https://example.com/cancel',
  'allow_promotion_codes' => true,
  'payment_method_types' => ['card'],
  'line_items' => [
    [
      'price' => 'price_H5ggYwtDq4fbrJ',
      'quantity' => 2,
      'tax_rates' => ['txr_1J5Z0LB6GOVAU4psl08YX3r6']
    ],
  ],
  'mode' => 'payment',
  'tax_id_collection' => ['enable' => true] // here
]
```

### Steps To Reproduce:
Use the Stripe checkout to make a payment, and allow users to enter their Tax ID by using the method `collectTaxIds()`.

**Comment by driesvints** [comment]
Thanks! No idea how that happened... I sent in a PR here: https://github.com/laravel/cashier-stripe/pull/1209

**Comment by YannickYayo** [comment]
You are fast !
Thank you :D

**Comment by driesvints** [comment]
@YannickYayo tagged v13.2.1 for ya: https://github.com/laravel/cashier-stripe/releases/tag/v13.2.1
