### ISSUE TITLE
Clean way to pass `aggregate_usage` value to Metered Billing Subscription

### ISSUE THREAD

**Issue by indianajson** [laravel/cashier-stripe#1212]
Within Stripe's documentation on [Metered Billing](https://stripe.com/docs/billing/subscriptions/metered-billing#creating-metered-subscription) you can determine the way Stripe calculates usage by including the `aggregate_usage` parameter. As it stands, Laravel Cashier only seems to support using the default value of `sum`. 

As it stands it appears we have to use something like this (although I haven't tested it):

```php
$checkout = Auth::user()
        ->newSubscription('default', [])
        ->meteredPrice('price_metered')
        ->checkout(['aggregate_usage' => 'last_ever'); //<--- old way

return view('your-checkout-view', [
    'checkout' => $checkout,
]);
```

I would like to see us be able to perform a request like:
```php
$checkout = Auth::user()
        ->newSubscription('default', [])
        ->meteredPrice('price_metered')
        ->aggregateUsage('last_ever') //<--- new way
        ->checkout();

return view('your-checkout-view', [
    'checkout' => $checkout,
]);
```

**Comment by driesvints** [comment]
Hey @indianajson. Your `old way` was never supported. There's no such parameter available upon a checkout creation: https://stripe.com/docs/api/checkout/sessions/create

The parameter you describe is set upon a new price creation. This is best done in the dashboard. See:

![Screen Shot 2021-06-28 at 16 00 56](https://user-images.githubusercontent.com/594614/123649611-2ec7bc80-d82a-11eb-80c8-bf798f4055bf.jpg)

Then you can use the Price Identifier (`price_xxx`) to use with `meteredPrice` and it'll have the `aggregate_usage` value that you require.

**Comment by indianajson** [comment]
Aha! Thank you, @driesvints, appreciate your insight on this!
