### ISSUE TITLE
Confirming payment with status `requires_action` is broken in Cashier's frontend views (possible fix included...)

### ISSUE THREAD

**Issue by JackWH** [laravel/cashier-stripe#1221]
- Cashier Version: 13.4.1
- Laravel Version: 8.51.0
- PHP Version: 8.0
- Database Driver & Version: N/A

### Description:

Using Cashier's default `cashier::payment` view file, to authorise a 3D Secure payment, fails when the status is `requires_action` and a default payment method is already assigned to the customer.

On the payment screen, the payment intent is presented correctly, but clicking the submit button results in a JavaScript error in the console, and the form fails to submit:

> IntegrationError: Missing value for confirmCardPayment: payment_method.card should be an object or element.

### Steps To Reproduce:

1. Create a Stripe customer and subscription, using card number `4000002760003184` (and any expiry/ZIP combination). This test card requires 3D Secure confirmation after every payment.
2. When an invoice payment fails, confirm the 3D Secure payment through Cashier's default `cashier::payment` view.
3. The payment will not confirm. Check your browser console to see the error.

### Potential Fix:

I've done some digging into the code, and I *think* I've found a fix. It looks like it's down to [this section of the JS](https://github.com/laravel/cashier-stripe/blob/13.x/resources/views/payment.blade.php#L302). The `data.payment_method.card` property is only being set when `this.paymentIntent.status === 'requires_payment_method'`.

With Stripe's test card number `4000002760003184`, the status is `requires_action`. There does not seem to be any assignment of a payment method when this status is set.

I think the fix is to add an `else if` clause, like so:

```js
if (this.paymentIntent.status === 'requires_payment_method') {
  data.payment_method.card = this.paymentElement;
} else if (this.paymentIntent.status === 'requires_action') {
  data.payment_method = '{{ \Illuminate\Support\Arr::get($paymentIntent, 'payment_method.id') }}';
}
```

This fetches the payment method ID from the `$paymentIntent` variable, which is being set in `PaymentController::show()`.

I've tested it and it fixes it in my case, but I'm not well-versed enough in Stripe's JS APIs to know if this is the correct solution, so would appreciate another pair of eyes on this...

**Comment by adamjgriffith** [comment]
I can confirm that this has also broken for me since upgrading to v13.

Example:

```
use Laravel\Cashier\Exceptions\IncompletePayment;

try {
    $subscription = $user->newSubscription('default', 'price_monthly')
        ->create('pm_card_authenticationRequired');
} catch (IncompletePayment $exception) {
    return redirect()->route(
        'cashier.payment',
        [$exception->payment->id, 'redirect' => route('home')]
    );
}
```

After clicking "Confirm payment" there is a vue error in the console and the button gets stuck in "Processing..." state.

**Comment by driesvints** [comment]
Thanks! I've sent in a PR for this: https://github.com/laravel/cashier-stripe/pull/1226
