### ISSUE TITLE
Name of new subscription is set to 'default' even if other name is specified on creation

### ISSUE THREAD

**Issue by rabol** [laravel/cashier-stripe#1223]
- Cashier Version: 13.4.1
- Laravel Version: 8.51.0
- PHP Version: 8.0.3
- Database Driver & Version:
MySql

### Description:
The name of the subscription is not set to the name in the newSubscription() call

It seems like the
```
$data['metadata']['name']
```

is empty in the payload that comes back from Stripe and is handled in the webhook method
```
handleCustomerSubscriptionCreated
```

### Steps To Reproduce:

Create a new subscription like this:
```
$checkout = $user->newSubscription('My super plan', $stripe_price_id)
                ->checkout([
                        'success_url' => 'route('user.dashboard'),
                        'cancel_url' => route('user.dashboard.cancel'),
                        'allow_promotion_codes' => true,
                    ],
                    [
                        'email' => $user->email,
                    ]
                );

return redirect($checkout->asStripeCheckoutSession()->url);
```

when the payment is processed and after web hooks has been called to create the the subscription record, the name will be 'default'

**Comment by driesvints** [comment]
It seems to have worked fine for me:

```php
Auth::user()->newSubscription('other', 'price_xxx')->checkout()
```

![Screen Shot 2021-08-02 at 15 51 04](https://user-images.githubusercontent.com/594614/127872563-c7375494-5bac-4144-9823-9554e120d178.jpg)

Please note that you seem to be using an invalid name for the subscription (spaces in the name). The name of a subscription is an internal reference value and not something that should ever be visible to a user.

**Comment by rabol** [comment]
why is this needed if the metadata always work ?

in the we web hook controller, method, handleCustomerSubscriptionCreated
$data['metadata']['name'] ?? $this->newSubscriptionName($payload)
