### ISSUE TITLE
Add support for subscription schedules

### ISSUE THREAD

**Issue by James4645** [laravel/cashier-stripe#1224]
Documented here: https://stripe.com/docs/api/subscription_schedules

Subscription scheduled would allow us to define a subscription that starts on a future date or end on a predetermined date.

I specifically would use this to start a subscription on a future date. I offer no credit card required trials (generic trials in Cashier terms) to new users. If I could schedule the start date for a subscription then I could not wait until the trial period is over to try to convert them to paid customers.

I had considered just giving them a regular trial on their subscription equal to the time remaining on their generic trial, but because generic trials have the features of the highest plan, that would mean either a user who converts early looses some features if they don't subscribe to the highest plan or I have to write custom logic to just give full access to any trial user.

Given the potential use cases for subscription trials beyond mine though I think it would make sense to add to Cashier as that would support other usecases beyond just mine.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier-stripe/issues/693
