### ISSUE TITLE
Laravel cashier webhook is no called when I make a new subscription in the stripe dashboard.

### ISSUE THREAD

**Issue by awesome1128** [laravel/cashier-stripe#1225]
- Cashier Version: #.#.#
- Laravel Version: 5.5.43
- PHP Version: 7.3
- Database Driver & Version:

### Description:
I created a custom webhookcontroller and defined the route in the web.php file.
Route::post('stripe/webhook', '\App\Http\Controllers\WebhookController@handleWebhook');

I want to fetch responses from the stripe dashboard using webhook, but it seems like this route is not called when I create a new subscription in the stripe dashboard. I wasted 1 day, but I can't find any issues. Please let me know what I am wrong.

### Steps To Reproduce:
[WebhookController.zip](https://github.com/laravel/cashier-stripe/files/6910276/WebhookController.zip)

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by awesome1128** [comment]
Thank you for replying. But I tried several times and ways, but I haven't fixed an issue yet. Please guide me here.
Thank you again.

**Comment by awesome1128** [comment]
Thank you for replying. But I found / tried several times and ways from Laracasts, Stackoverflow, Disord, and etc, but I haven't fixed an issue yet. Please guide me here.
Thank you again.
