### ISSUE TITLE
downloadInvoice function returns an empty headers object on API

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1231]
- Cashier Version: 13.4.2
- Laravel Version: 8.14.0
- PHP Version: 7.4

### Description:

I'm using Laravel Cashier v13 in my Laravel 8 API project with a Nuxt JS front-end. I'm a customer, have subscribed to a plan and am trying to download my invoice as a PDF as per the [docs](https://laravel.com/docs/8.x/billing#generating-invoice-pdfs).

I've set up a `GET` route in my `api.php` file and have got my `SubscriptionInvoiceController` looking like the following:

```php
<?php

namespace App\Http\Controllers\Account\Subscriptions;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

use App\Models\User;

class SubscriptionInvoiceController extends Controller
{

    /**
     * Instantiate a new SubscriptionInvoiceController instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Show invoice
     *
     * @return Response
     */
    public function show(Request $request, $id)
    {
        $invoice = Auth::user()->downloadInvoice($id, [
          'vendor' => 'DM',
          'product' => 'Subscription'
        ]);

        return response()->json([
          'success' => true,
          'message' => 'Your invoice',
          'invoice' => $invoice
        ], 200);
    }

}
```

When I make a `GET` request to download an invoice on my `show1 function, the returned data is:

```
{
   "success":true,
   "message":"Your invoice",
   "invoice":{
      "headers":{
         
      }
   }
}
```

What am I missing?

My front-end implementation of the download function looks like:

```javascript
/*
** Download invoice
*/
downloadInvoice (invoice) {
  this.$axios.get(`${process.env.API_URL}/api/invoices/${invoice}`).then(res => {

    if (!res.data.success) {
      alert('something went wrong')
    }


  }).catch(err => {
    console.log(err)
  })
},
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
