### ISSUE TITLE
$request->getContent() return null, causes unit test failure.

### ISSUE THREAD

**Issue by j0eii** [laravel/cashier-stripe#1232]
I have experienced the same issue in this test case.

I believe this issue is occurred during the unit test only, the request/response object won't mock the getContent(); method in this case.

![image](https://user-images.githubusercontent.com/13985803/128627647-759d7bcf-5b91-47a7-b999-a93bc96626d0.png)

A temp fix to this issue is not to use the request/response->getContent() function.

```
namespace Laravel\Cashier\Http\Controllers;

class WebhookController extends Controller{

    public function handleWebhook(Request $request)
    {
//        dd($request->getContent()); // null
        dd($request->get('type')); // invoice.payment_succeed

        dd($request->get('type'));

        // Origin code
//        $payload = json_decode($request->getContent(), true);
//        $method = 'handle' . Str::studly(str_replace('.', '_', $payload['type']));

        // Temp fix
        $type = null;
        if ($request->get('type') !== null) $type = $request->get('type');
        else {
            $payload = json_decode($request->getContent(), true);
            $type = Str::studly(str_replace('.', '_', $payload['type']));
        }
        $method = 'handle' . $type;
...

}

```

_Originally posted by @j0eii in https://github.com/laravel/framework/issues/29210#issuecomment-894770687_

**Comment by j0eii** [comment]
Updated, the $payment getter should be fixed via the following code during unit test:

```
        $payload = null;
        if ($request->get('type') !== null) $payload = $request->attributes->get('payload', $request)->request->all();
        else $payload = json_decode($request->getContent(), true);
        $type = Str::studly(str_replace('.', '_', $payload['type']));
        $method = 'handle' . $type;

```

![image](https://user-images.githubusercontent.com/13985803/128628068-0272ed7a-21ec-4fd9-a49f-4788e70c3360.png)

**Comment by j0eii** [comment]
for the current version:, v13.4.2,

the unit test method (request->getContent()) is kind of not working and return null since the unit test is passing the parameter bag instead of the full original payload.

![image](https://user-images.githubusercontent.com/13985803/128628157-426833d1-0f33-411e-ac94-86f59209ed1c.png)

---
array:5 [
  "message" => "Trying to access array offset on value of type null"
  "exception" => "ErrorException"
  "file" => "/home/engineer/projects/quotation/src/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php"
  "line" => 42
  "trace" => array:58 [
    0 => array:5 [
      "file" => "/home/engineer/projects/quotation/src/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php"
      "line" => 42
      "function" => "handleError"
      "class" => "Illuminate\Foundation\Bootstrap\HandleExceptions"
      "type" => "->"
    ]
    1 => array:5 [
      "file" => "/home/engineer/projects/quotation/src/vendor/laravel/framework/src/Illuminate/Routing/Controller.php"
      "line" => 54
      "function" => "handleWebhook"
      "class" => "Laravel\Cashier\Http\Controllers\WebhookController"
      "type" => "->"
    ]
    2 => array:5 [
...

```

Therefore, by changing the getContent getter to `$request->attributes->get('existing_field', $request)->request->all()` can chain back the parameter bag in order to make it works under unit test.

**Comment by j0eii** [comment]
https://github.com/laravel/cashier-stripe/pull/1233

Here is the draft pull request,

It is just a dirty fix, I guess the real root case of casing $request->getContent() return null is because of the unit test module won't fully mock the request content object, only mocking the parameter bag.

**Comment by driesvints** [comment]
Re-open this with a filled out issue template.
