### ISSUE TITLE
`array_filter` removes `0` as the quantity value to `addPrice` function

### ISSUE THREAD

**Issue by jayan-blutui** [laravel/cashier-stripe#1237]
- Cashier Version: 13.4.4
- Laravel Version: 8.55.0
- PHP Version: 8.0.9
- Database Driver & Version: MySQL 8.0.26

### Description:

I noticed that when specifying `0` as the quantity for the second argument of `addPrice`, it is filtered out in the final result. Setting `0` as the quantity is committed to the database but not to Stripe, instead the default value of `1` is used in Stripe.

https://github.com/laravel/cashier-stripe/blob/137452fbb003cd1996c3c37994c389c3bd1f5676/src/Subscription.php#L840

I understand that this is the default behaviour of `array_filter` as `0` is equivalent to `false`.

**Comment by jayan-blutui** [comment]
Just read through the Stripe PHP library and it looks like `params` are formatted to convert `null` values to an empty string. 

A link to Stripe's function: [`formatParams` function](https://github.com/stripe/stripe-php/blob/c739cf6841bb3498e23bd52ecfadfcb21c521a14/lib/Service/AbstractService.php#L59). Would it make sense to remove the `array_filter` in favour of Stripe's `formatParams` function?

**Comment by driesvints** [comment]
Heya, thanks for reporting this. While I agree that the current implementation is faulty I must stress that zero isn't a correct value to pass here (I'm not sure why you'd want that?). I did however update our implementation to always use the Stripe returned quantity: https://github.com/laravel/cashier-stripe/pull/1238
