### ISSUE TITLE
Bug in incrementAndInvoice() / incrementQuantity()

### ISSUE THREAD

**Issue by BubeDameKoenig** [laravel/cashier-stripe#1241]
- Cashier Version: 13.4.4

### Description:
I created a "Multiplan Subscription" and wanted to increase the number with incrementAndInvoice(), but I always get the following error (see printscreen attached). I also tried with incrementQuantity() but I get the same error.

With **$stripeSubscriptionItem->subscription** I get the **subscriptions.stripe_id** and can't read a status here.

Thanks for the correction.

### Steps To Reproduce:

`$subscription->subscription('default')->incrementAndInvoice(2, 'price_monthly');`

![Bildschirmfoto 2021-08-22 um 15 43 07](https://user-images.githubusercontent.com/50578666/130357626-26e035a0-3125-4532-8ef2-6c51392669e9.png)

**Comment by driesvints** [comment]
This was already fixed here: https://github.com/laravel/cashier-stripe/pull/1240. Will be in tomorrow's release. Thanks
