### ISSUE TITLE
New multiprice subscription with array quantity()

### ISSUE THREAD

**Issue by BubeDameKoenig** [laravel/cashier-stripe#1242]
At the moment you always have to know exactly how many quantity methods are needed when creating a multiprice new subscription. It would help if you could create this more dynamically.

For example, if you could send an array to the ->quantity() (see code suggestion).

`$user->newSubscription('default', ['price_monthly', 'price_chat', 'price_user'])->quantity(['price_chat' => 5, 'price_user' => 2])->create($paymentMethod);`

This would give a lot of flexibility in the composition of the new subscription.

Best thanks.

**Comment by driesvints** [comment]
```php
$prices = ['price_monthly' => 1, 'price_chat' => 5, 'price_user' => 2];

$newSubscription = $user->newSubscription('default', array_keys($prices));

foreach ($prices as $price => $quantity) {
    $newSubscription->quantity($quantity, $price);
}

$newSubscription->create($paymentMethod);
```
