### ISSUE TITLE
`invoiceFor` should be able to bill for multiple items at once

### ISSUE THREAD

**Issue by Orrison** [laravel/cashier-stripe#1253]
Currently, unless I am looking at the code wrong, it seems that you can only bill for a single "item" using `invoiceFor`. It would be great if you could add multiple "Invoice Items" as Stripe calls them.

I would be more than willing to work on this feature if the community thinks it would be useful.

My thought is to either modify the current `invoiceFor` method to allow for this, while still remaining backwards compatible. Or to create a separate `invoiceForMultiple` method.

**Comment by driesvints** [comment]
I don't think a separate method makes sense since we already have the `tab` method:

```php
$customer->tab('Product 1', 5);
$customer->tab('Product 2', 5);
$customer->invoice();
```
