### ISSUE TITLE
Stripe notice about undefined property (quantity) with metered prices

### ISSUE THREAD

**Issue by adamthehutt** [laravel/cashier-stripe#1254]
- Cashier Version: 13.5.1
- Laravel Version: 8.61.0
- PHP Version: 8.0.10
- Database Driver & Version: MySQL 8

### Description:
When adding a metered price to an existing subscription, Stripe is emitting an error notice about an undefined property (quantity) on the SubscriptionItem object.

[Here's the problem line](https://github.com/laravel/cashier-stripe/blob/1a80ccb9b2a691aaa7478f9263e8dbb1eb2bf6f3/src/Subscription.php#L853).

### Steps To Reproduce:

Create a subscription, then:

```php
$user->subscription()->addMeteredPrice($priceId);
```

Null is (correctly) being passed as the quantity to the addPrice method, but then when Cashier tries to create a record of the subscription item it references the Stripe object's quantity property, which is undefined.

I believe a fix is as simple as:

```php
    'quantity' => $stripeSubscriptionItem->quantity ?? null
```

I can produce a PR if you'd like.

**Comment by mfauveau** [comment]
I was coming here to report the same thing. 

I see it show up in my unit tests as ```Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity```. This leads me to believe it's not a bug in Cashier (also because if you force the SubscriptionBuilder to pass a null quantity, the API call will fail).

**Comment by driesvints** [comment]
Thanks all. @mfauveau I think this is in fact a bug in Cashier. I've sent in that fix here: https://github.com/laravel/cashier-stripe/pull/1255

@adamthehutt always feel free to send in PR's with those fixes. Saves a bit of time ;)

**Comment by mfauveau** [comment]
@driesvints maybe I'm missing something but for me, the notice is triggered by https://github.com/laravel/cashier-stripe/blob/13.x/src/SubscriptionBuilder.php#L251

This is why I was saying this might be a Stripe bug. https://stripe.com/docs/api/subscriptions/create describes quantity as optional but:
- It's throwing the warning even though quantity is not sent by the payload 
- If I force quantity to be sent as null, the API call fails

**Comment by driesvints** [comment]
@mfauveau it's thrown in https://github.com/laravel/cashier-stripe/blob/1a80ccb9b2a691aaa7478f9263e8dbb1eb2bf6f3/src/Subscription.php#L853 and not in the subscription builder.

**Comment by mfauveau** [comment]
@driesvints I think it's a different bug them. This line is not called in my case.

This is what my code does:
```
$paymentMethod = $this->defaultPaymentMethod()->id;

$subscription = $this->newSubscription('default');

// Get the most recent metered prices set
$prices = Pricing::allMeteredPrices();

// Add each price to the subscription
foreach ($prices as $price) {
    $subscription->meteredPrice($price);
}

$subscription->create($paymentMethod, [], [
    'cancel_at_period_end' => false,
    'automatic_tax' => ['enabled' => true],
    'billing_thresholds' => ['amount_gte' => config('billing.billing_thresholds')]
]);
```

**Comment by mfauveau** [comment]
@taylorotwell @driesvints note that @adamthehutt is updating an existing subscription. My code creates a subscription from scratch with the subscription builder. In that particular situation, the notice will still show up.

**Comment by driesvints** [comment]
I'm sorry @mfauveau but we have tests for the exact code you're using. If you really believe there's a bug please provide a failing test for this library.

**Comment by mfauveau** [comment]
I get that @driesvints but look:

```
vagrant@homestead:~/Development/cashier-stripe$ phpunit --filter MeteredBillingTest
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
..Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity
.                                                            8 / 8 (100%)

Time: 00:54.945, Memory: 30.00 MB
```

**Comment by mfauveau** [comment]
> Here's for example a test that covers the behavior: https://github.com/laravel/cashier-stripe/blob/13.x/tests/Feature/MeteredBillingTest.php#L208-L210
> 
> I'm wondering what `Pricing::allMeteredPrices();` returns? Maybe the culprit lies there?

I'm guessing you posted that before seeing my previous comment?

It returns an array of prices:
```
array:4 [
  0 => "price_1JMejbIAQWEAWAnbTKgId72x"
  1 => "price_1JMelEIAQWEAWAnbmgXEHh0q"
  2 => "price_1JMeneIAQWEAWAnbI070LpsM"
  3 => "price_1JMen8IAQWEAWAnbwtDxsuGG"
]
```

**Comment by driesvints** [comment]
Hmm no. I'm very sorry @mfauveau but I just don't see an issue. We have tests which very the code is working. If you really think there's a bug please provide a PR.

**Comment by mfauveau** [comment]
This https://github.com/laravel/cashier-stripe/issues/1254#issuecomment-927959390 is a fresh clone of a cashier running the MeteredBillingTest and showing the error @driesvints. Not sure what you don't see here. But that's all good. It's just a notice after all.

**Comment by driesvints** [comment]
@mfauveau we don't get those notices in our test suite: https://github.com/laravel/cashier-stripe/runs/3720820913

No worries, I'm also just a bit confused here 😅

**Comment by mfauveau** [comment]
> https://github.com/laravel/cashier-stripe/runs/3720820913

I had a feeling you were referring to the test suite.

It's confused indeed. I wonder why a fresh clone is throwing that notice but not the test suite? I'm guessing the test suite doesn't silence notices.

Upon a quick inspection, it looks like the test suite pulls a different version of stripe-php (v7.97.0 vs 7.39). I'm gonna try to upgrade and run the test again.

**Comment by mfauveau** [comment]
Never mind, still throwing notices with v7.97.0 🤷‍♂️
