### ISSUE TITLE
createOrGetStripeCustomer() Fails during checkout

### ISSUE THREAD

**Issue by aalicki** [laravel/cashier-stripe#1260]
- Cashier Version: 13.5
- Laravel Version: 8.40
- PHP Version: 7.4.16
- Database Driver & Version: MySQL / 5.7.32

### Description:

When attempting to create or get a Stripe customer (under any circumstance), the server responds with an error `"Stripe\Exception\InvalidArgumentException"`
`The resource ID cannot be null or whitespace.`

This occurs when using the method `$user->createOrGetStripeCustomer()`.

### Steps To Reproduce:

Implement the Stripe Elements as instructed by Stripe Documentation.
Perform a test checkout with the form.
In your method to process a checkout, ensure you have the following:
```
$user = Auth::user();
$paymentMethod = $request->input('payment_method');

$user->createOrGetStripeCustomer();
```

Below is the full function that get's hit when the Stripe form is submitted:
```
public function processSubscription(Request $request)
    {
        $user = Auth::user();
        $paymentMethod = $request->input('payment_method');

        $user->createOrGetStripeCustomer();
        $user->addPaymentMethod($paymentMethod);

        try {
            $user->newSubscription('default', $this->monthlyId)->create($paymentMethod, [
                'email' => Auth::user()->email
            ]);

        } catch (\Exception $e) {

            return back()->withErrors(['message' => 'Error creating subscription. ' . $e->getMessage()]);
        }

        return redirect('dashboard');
    }
```

**Comment by driesvints** [comment]
We have several tests that verify the `createOrGetStripeCustomer` behavior. If you really believe there's a bug here feel free to provide a PR with a failing tests. Otherwise it's best that you try a support channel as there could be an issue specific to your codebase.
