### ISSUE TITLE
Query scope for users latest subscription

### ISSUE THREAD

**Issue by mhalseyperry** [laravel/cashier-stripe#1263]
I am trying to create a Nova filter that will allow me to view users whose subscription is currently cancelled. 

I am running into issues creating the filter as I can't see a way to query against _only_ the users latest/current subscription. The scopes cashier provides consider all of a users past subscriptions. Is there any way to scope queries against only the latest subscription?

For example a user who cancelled their subscription and then resubscribed will be returned when querying for users using the cancelled scope.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
