### ISSUE TITLE
Creating a subscription without a payment method

### ISSUE THREAD

**Issue by kyranb** [laravel/cashier-stripe#1275]
Stripe offers the ability to create a subscription without a payment method (and send it as an invoice) using the `collection_method` parameter.

https://stripe.com/docs/api/subscriptions/create

Would you be open to allowing Cashier to not mandate requiring a payment method?

The use case for this is creating subscriptions for customers that have to pay by purchase order/can't use a credit/debit card.

**Comment by driesvints** [comment]
The `create` method on the subscription builder already has the paymentMethod as nullable. There's also the `->add()` method. Any reason why that doesn't work for you or why that's not clear in the docs?

**Comment by kyranb** [comment]
I read this line in the docs and it wasn't clear to me that the payment method wasn't required by Cashier could be nullable. 

"The create method, which accepts a Stripe payment method identifier or Stripe PaymentMethod object, will begin the subscription as well as update your database with the billable model's Stripe customer ID and other relevant billing information."

I hadn't seen the `add()` method, but that should do the trick.

Perhaps a `createAndSendInvoice()` helper could also be added for some syntactic sugar to set the `collection_method` to `send_invoice`.

**Comment by driesvints** [comment]
Good idea. Just sent in a PR for that: https://github.com/laravel/cashier-stripe/pull/1276

I'll get the docs updated as well. Thanks!
