### ISSUE TITLE
Notifications should be sent only for off-session payments

### ISSUE THREAD

**Issue by mr-mmmmore** [laravel/cashier-stripe#1277]
Regarding incomplete payment notifications, the Cashier documentation states that:
> Notifications will be sent even when customers are manually making a payment that requires additional confirmation. Unfortunately, there is no way for Stripe to know that the payment was done manually or "off-session". 

I find this last sentence weird: how could Stripe not be aware that the payment was done off-session when it is their system that triggers it automatically (compared to triggered from the API by Cashier when it is manual)?

Furthermore the notification is sent by Cashier when handling the `invoice.payment_action_required`, where the `billing_reason` is available.

Couldn't the `billing_reason` be used and the notification sent only if its value is `subscription_cycle`?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by mr-mmmmore** [comment]
I think it is actually a bug:

- This notification is clearly dedicated to "off-session" payments (Documentation title: _"Off-Session Payment Notifications"_) but the behavior is different.
- The note in the doc recognizes that the behavior is contrary to the intent (_"Notifications will be sent even when customers are manually making a payment"_)
- To warn in the doc is not a solution to the problem.
- It seems that using `billing_reason` could actually solve the problem.

**Comment by driesvints** [comment]
If there's a bug then fill in the issue template please.

**Comment by mr-mmmmore** [comment]
- Cashier Version: 10.7.1
- Laravel Version: 6.20.35
- PHP Version: 7.2.34

### Description:
The off-session payment notifications are sent for on-session payment failures.

### Steps To Reproduce:
1. Collect a payment method using stripe.js, use the `4000 0027 6000 3178` card (that requires authentication on all transactions regardless of the setup)
2. Use the collected payment method to create a subscription 
  `$user->newSubscription('default', 'premium')->create($paymentMethod);`
3. The Stripe subscription is created with an `incomplete` status and `WebhookController::handleInvoicePaymentActionRequired` is triggered by Stripe.
4. The notification is sent although it was an on-session payment.

### Expected behavior
The notification should be sent only when the subscription is auto-renewing off-session. Using `Invoice.billing_reason` might help in doing so.

**Comment by driesvints** [comment]
Please post a new issue

**Comment by mr-mmmmore** [comment]
I can do it but why? All the information is here with a suited title.
