### ISSUE TITLE
Multiple products

### ISSUE THREAD

**Issue by amiltonsoares** [laravel/cashier-stripe#1279]
Hi! We are launching an app that has several functions that can be hired in a single subscription. Example:

- Basic / $10
- Chat (1 to 5 people) / $5 (per person)
- Blog (1 to 10 people) / $1 (per person)

The user can select the basic product and optionally the other products (choosing the quantities). In conversation with Stripe this documentation was given to us: https://stripe.com/docs/billing/subscriptions/multiple-products

Is it possible to do this with Cashier?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
