### ISSUE TITLE
Charge Billable user without Payment Method

### ISSUE THREAD

**Issue by MissaelAnda** [laravel/cashier-stripe#1289]
It would be nice to be able to create a PaymentIntent with the charge method without providing a PaymentMethod, this is possible with the Stripe SDK with the following code:
![imagen](https://user-images.githubusercontent.com/31199350/143622290-49dd787b-e4cf-47b0-acc9-708b8ee66a5a.png)

**Comment by driesvints** [comment]
Feel free to propose something through a PR 👍
