### ISSUE TITLE
If syncStripeStatus() returns canceled, update the 'ends_at' field in the db. so $user->subscription('main')->cancelled() returns true

### ISSUE THREAD

**Issue by sahilkashyap64** [laravel/cashier-stripe#1290]
- Cashier Version: 11.3.0
- Laravel Version: 6.0.0
- PHP Version: 7.1.3
- Database Driver & Version:MySQL

### Description:
I'm using syncStripeStatus to sync the status
 `optional($user->subscription('main'))->syncStripeStatus();`

### Steps To Reproduce:
1. Assume a userX's subscription was canceled from stripe dashboard
2. In laravel app, login with userX;we run
`optional($user->subscription('main'))->syncStripeStatus();`
3. It updates the db
`$this->stripe_status = $subscription->status; // as canceled`

4. Now let's check if subscription was cancelled
`$user->subscription('main')->cancelled(); //return false cuz it checks only 'ends_at' which is null right now`

###Possible solution
```php
public function syncStripeStatus()
    {
        $subscription = $this->asStripeSubscription();
        if(is_null($this->ends_at) && 
        $subscription->status==StripeSubscription::STATUS_CANCELED){
            $this->stripe_status = $subscription->status;
            $this->ends_at = Carbon::createFromTimestamp(
                $subscription->canceled_at
            );
        }else{
        $this->stripe_status = $subscription->status;
    }

        $this->save();
    }

```

- second possible solution
we can change the cancelled() function to check the status as canceled
```php
public function cancelled()
    {
       // return ! is_null($this->ends_at);
       return ! is_null($this->ends_at)||$this->stripe_status==StripeSubscription::STATUS_CANCELED;
    }
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
