### ISSUE TITLE
Keeping site database in sync with Stripe data through webhook command

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1291]
I'm currently developing a project using Cashier Stripe in my Laravel 8 project, I have a table called `users` which holds data such as the `stripe_id` and `pm_type` along with other tables that Cashier provides such as `subscriptions`.

I've got a webhook URL set up through ngrok right now for local development, and, after leaving the project for some time and making various changes in Stripe and then jumping back into the project today it was clear that the data in my Stripe account wasn't synced with my project, for example...

My webhook wasn't running, in my Stripe account I had canceled my customer's subscription, but the last time my project ran it obviously saw that the customer was subscribed.

This type of scenario would be quite typical in instances where the webhook may be temporarily unavailable in a production environment or may require restarting or updating, so there would be some downtime.

Ideally I'd like to be able to run something like:

```
php artisan cashier:webhook clean
```

or 

```
php artisan cashier:webhook sync
```

and running this would automatically trigger relevant webhook signals to go and update my database tables, since after making that change and restarting my webhook I had to cancel the customer's subscription again for the signal to come through and update my database.

I'm open to hearing what kind of flows or suggestions anyone has, or how you suggest I tackle a potential issue which would require me to run a command and effectively cleanup any table columns and sync the data?

**Comment by driesvints** [comment]
Unfortunately we can't help making sure your web hooks keep running, sorry. If you miss events, you're responsible for syncing the data back into your app in user land. There's quite a few edge cases that could go wrong if we tried doing that through cashier (triggering events, re-syncing unwanted stuff back into stripe, etc.). It's best that you research a custom solution to this for your use case.

**Comment by sts-ryan-holton** [comment]
@driesvints Okay, interesting to know, downtime does however happen with projects in a production environment, maybe you're able to implement a command to highlight what changes a system admin might need to do to their database or what commands to run then instead?

**Comment by driesvints** [comment]
Stripe offers webhook retries in their dashboard.
