### ISSUE TITLE
Listen for when a user's subscription has ended and do something

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1293]
I'd like to be able to automatically perform some actions, such as disabling features of a user account in my database once a user's subscription has ended or has been changed (downgraded), I was thinking about whether running a Laravel cron job via the task scheduler was appropriate for this, get all of the users, check if they're not subscribed and then do something but realised that this would put a lot of overheads on the database and once a user has been unsubscribed wouldn't want to keep performing these queries.

How's best for me to identify whether a user has unsubscribed and then disable certain features in their account?

For example:

A user has a maximum of 50 todos on a free plan, and 100 on a paid plan. A user subscribes to the paid plan and adds an additional 20 todos bringing their total now to 70/100. Then, after 2 months they decide to downgrade their account back to 50, I need to **detect this** and then update those 20 records and disable them so that they can't be edited etc, maybe even delete them.

What do I need to listen for and where to achieve this?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
