### ISSUE TITLE
"User is not a Stripe customer yet. See the createAsStripeCustomer method

### ISSUE THREAD

**Issue by diloabininyeri** [laravel/cashier-stripe#1294]
- Cashier Version: 13.6
- Laravel Version: 8.76.2
- PHP Version: 7.3
- Database Driver & Version:

### Steps To Reproduce:

**php code**
```php

  $user= $request->user();

  $user-> createAsStripeCustomer();
````

Error Response
```json
{
    "message": "User is not a Stripe customer yet. See the createAsStripeCustomer method.",
    "exception": "Laravel\\Cashier\\Exceptions\\InvalidCustomer",
    "file": "/var/www/html/restapi/vendor/laravel/cashier/src/Exceptions/InvalidCustomer.php"
}
```

**Comment by itvoland** [comment]
I don't have this error, the user was created.

**Comment by diloabininyeri** [comment]
run this code then try,you will see that you can't work
```php
 $user->stripe()->customers->delete($user->stripeId());
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
