### ISSUE TITLE
Resume a subscription that has no grace period

### ISSUE THREAD

**Issue by itvoland** [laravel/cashier-stripe#1295]
- Cashier Version: 13.4.0
- Laravel Version: 8.0.0
- PHP Version: 7.4.0
- Database Driver & Version: mysql 8

### Description:
I have an active subscription. It included a non-return payment. But over time, it was turned off. Through the cancel () method.
When I eat to renew the subscription, in terms of recurrent payments via resume (). I get the error "Unable to resume subscription that is not within grace period." but the fact is that I do not have a grace period in this subscription.

### Steps To Reproduce:

```
public function resume()
    {
        if ($this->onTrial() && !$this->onGracePeriod()) {
            throw new LogicException("Unable to resume subscription that is not within grace period.");
        }
        $stripeSubscription = $this->updateStripeSubscription([
            'cancel_at_period_end' => false,
            'trial_end' => $this->onTrial() ? $this->trial_ends_at->getTimestamp() : null,
        ]);
        // Finally, we will remove the ending timestamp from the user's record in the
        // local database to indicate that the subscription is active again and is
        // no longer "canceled". Then we shall save this record in the database.
        $this->fill([
            'stripe_status' => $stripeSubscription->status,
            'ends_at' => null,
        ])->save();

        return $this;
    }
```

**Comment by driesvints** [comment]
>  the fact is that I do not have a grace period in this subscription.

I think you misread that. You *need* a grace period to resume a subscription. If you don't have that then you need to start a new one for the customer.
