### ISSUE TITLE
Method subscription() does not retrieve the most recent subscription as expected

### ISSUE THREAD

**Issue by marcbelletre** [laravel/cashier-stripe#1296]
- Cashier Version: 13.6.1
- Laravel Version: 8.76.2
- PHP Version: 8.0.14
- Database Driver & Version: MySQL 5.7.18

### Description:
I have a user who has two subscriptions. The oldest one has been canceled and the most recent is active. 

id | user_id | name | stripe_id | stripe_price | quantity | stripe_status | trial_ends_at | ends_at | created_at | updated_at |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
100 | 534 | advisor | sub_***BIloe | price_***AbhD8 | 1 | canceled | NULL | 2022-01-05 19:38:22 | 2022-01-05 19:32:20 | 2022-01-05 19:38:22
101 | 534 | advisor | sub_***HTZrqh | price_***AbhD8 | 1 | active | NULL | NULL | 2022-01-05 19:56:42 | 2022-01-05 19:56:42

The documentation says that the most recent subscription should be returned when using the `subscription()` method on the user.

> If a user has two subscriptions with the same name, the most recent subscription will always be returned by the subscription method. For example, a user might have two subscription records named default; however, one of the subscriptions may be an old, expired subscription, while the other is the current, active subscription. The most recent subscription will always be returned while older subscriptions are kept in the database for historical review.

But when I try to retrieve the user's subscription with `$user->subscription('advisor')` I only get the oldest one with the id `100`.

### Steps To Reproduce:

1. Subscribe a user to a subscription plan
2. Cancel the subscription
3. Subscribe again to a new subscription plan
4. Retrieve the current subscription with `$user->subscription('name')`

**Comment by marcbelletre** [comment]
Closing the issue since the error was on my side. I had overwritten the `subscriptions` relationship in my Billable model and didn't set any order.

**Comment by liamseys** [comment]
@marcbelletre Do you have to overwrite the ```subscriptions```relationship?

**Comment by marcbelletre** [comment]
Hi, 
I'm not sure what you mean. This is issue is a year old so I can't remember precisely what I was doing at this time :) But as far as I remember I had a custom `Subscription` model that was conflicting with Cashier so that was the problem.
