### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry sub_XX for key subscriptions_stripe_id_unique insert into subscriptions

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1300]
- Cashier Version: 13.7.0
- Laravel Version: 8.79.0
- PHP Version: 7.4.27
- Database Driver & Version: 10.3.28-MariaDB - MariaDB Server, PHP My Admin interface

### Description:

I've recently deployed my subscriptions feature for my project, I initially tried everything in local development and everything working fine, but after deploying and subscribing to a plan, I'm getting a weird duplicate key error thrown upon subscribing to a plan. The payment was taken successfully by my card issuer, I can see my customer in my stripe dashboard along with the subscription. There's just a single subscription there which is correct, the whole process though appears to have worked, in that I'm susbcribed?

Just not sure why it didn't return my 200 response to the browser, how can I handle this?

For reference, I have:

- subscription_items table

```php
$table->bigIncrements('id');
$table->unsignedBigInteger('subscription_id');
$table->string('stripe_id')->unique();
$table->string('stripe_product');
$table->string('stripe_price');
$table->integer('quantity')->nullable();
$table->timestamps();

$table->unique(['subscription_id', 'stripe_price']);
```

- subscriptions table

```php
$table->bigIncrements('id');
$table->unsignedBigInteger('user_id');
$table->string('name');
$table->string('stripe_id')->unique();
$table->string('stripe_status');
$table->string('stripe_price')->nullable();
$table->integer('quantity')->nullable();
$table->timestamp('trial_ends_at')->nullable();
$table->timestamp('ends_at')->nullable();
$table->timestamps();

$table->index(['user_id', 'stripe_status']);
```

I have one item in my subscriptions table, and one item in my items table. The error:

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sub_1KI9GVKdz0z9mpUGLRavESNE' for key 'subscriptions_stripe_id_unique' (SQL: insert into `subscriptions` (`name`, `stripe_id`, `stripe_status`, `stripe_price`, `quantity`, `trial_ends_at`, `ends_at`, `user_id`, `updated_at`, `created_at`) values (default, sub_1KI9GVKdz0z9mpUGLRavESNE, active, price_1KHqULKdz0z9mpUGBih2NB1D, 1, ?, ?, 5, 2022-01-15 10:13:47, 2022-01-15 10:13:47))

And here's my function that creates the subscription:

```php
$frontendURL = $this->getSetting('api_frontend_url') != null ? $this->getSetting('api_frontend_url') : 'https://domain-monitor.io/';

$validator = Validator::make($request->all(), [
  'token' => 'required',
  'coupon' => [
    'nullable',
    new ValidCoupon()
  ],
  'plan' => 'required|exists:plans,slug'
]);

if ($validator->fails()) {
    return response()->json([
      'message' => "One or more fields appear to be missing, please check that you've filled everything in correctly.",
      'errors' => $validator->messages()
    ], 400);
}

$plan = Plan::where('slug', $request->input('plan', 'monthly-75'))
            ->first();

if (!$plan) {
    return response()->json([
      'message' => "The plan you're trying to subscribe to is either invalid or doesn't exist."
    ], 404);
}

// validate that the user is able to switch to this plan, typically
// if a user has more domains, monitors etc than the plan they're trying
// to switch to, we prevent the downgrade here.
if (!$this->isEligibleToSwitchToPlan(Auth::user(), $plan->slug)) {
    return response()->json([
        'message' => "You currently have more domains, monitors, status pages or notification contacts than the plan you're trying to subscribe to allows. Please choose a different plan or delete some of your domains, monitors, status pages or notification contacts first.",
        'isEligible' => false
    ], 404);
}

try {
  Auth::user()->newSubscription('default', $plan->stripe_id)
              ->withCoupon($request->input('coupon'))
              ->create($request->input('token'));
} catch (IncompletePayment $e) {

  // Check specific conditions...
  if ($e->payment->requiresAction()) {
    return response()->json([
      'message' => "We require some payment action from you, this usually means you need to open your banking app to approve this subscription.",
      'requiresAction' => true,
      'redirectTo' => route('cashier.payment', [
        $e->payment->id,
        'redirect' => $frontendURL . 'account/subscriptions/'
      ])
    ], 400);
  } else {
    return response()->json([
      'requiresConfirmation' => true,
      'message' => "We require you to confirm this payment.",
    ], 400);
  }

}

return response()->json([
  'message' => "You've successfully upgraded your account.",
  'complete' => true
], 201);
```

My project's app debug was set to **true** when this happened, and my Stripe webhook is working correctly.

**Comment by driesvints** [comment]
Please post the full stack trace and preferable the code in a repo that reproduces this. Please commit all your custom changes separately.

**Comment by sts-ryan-holton** [comment]
@driesvints with respect, I'm not sure a reproduction is appropriate in this case? Everything is provided above, the entire function responsible for creating a subscription, both database schemas provided by Laravel Cashier (not myself), along with the exact error message thrown? This is the only point in my web application where I've discovered this error.

Any suggestions or thoughtS?

**Comment by driesvints** [comment]
If there's not way to reproduce this then I'm afraid we cannot help out here. Normally, there should never be duplicate subscriptions in your app. The web hooks already account for this.

**Comment by mikewudev** [comment]
@driesvints the webhook does account for skipping a subscription if one exists, but `SubscriptionBuilder` doesn't handle the case where the webhook arrives before the eloquent subscription is created.

### From `SubscriptionBuilder::create()`

```php
 public function create($paymentMethod = null, array $customerOptions = [], array $subscriptionOptions = [])
    {
        // ...

        $stripeCustomer = $this->getStripeCustomer($paymentMethod, $customerOptions);

       // Request goes out to Stripe
        $stripeSubscription = $this->owner->stripe()->subscriptions->create(array_merge(
            ['customer' => $stripeCustomer->id],
            $this->buildPayload(),
            $subscriptionOptions
        ));

       // --- `customer.subscription.created` webhook arrives
    
 
        $subscription = $this->createSubscription($stripeSubscription); // Fail due to duplicate unique key on stripe_price
       
        // ...
    }
```

**Comment by driesvints** [comment]
@sts-ryan-holton looks like your issue might also get resolved with https://github.com/laravel/cashier-stripe/pull/1308

**Comment by sts-ryan-holton** [comment]
@driesvints Excellent news! Would that change be categorised as a new `minor` or `patch` release of Cashier?

**Comment by driesvints** [comment]
@sts-ryan-holton not sure yet. Depends on else gets in before Tuesday's release.
