### ISSUE TITLE
Linking plan to a subscription and user plan relationship returns original plan when swapping subscriptions

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1301]
In my application I've created a `plans` table which I query on my front-end to display a list of plans and also it's used alongisde `subscribedToPrice` to determine whether a customer is subscribed to a certain plan.

> :warning: Just to note, although I've got this listed at `stripe_id`, I'm storing the `price_XXX` value in the column, it's just called `stripe_id` as a legacy thing here, so wherever this is mentioned it's value is the price.

My schema for my plans table is:

```php
$table->id();
$table->string('title');
$table->string('slug')->unique();
$table->string('stripe_id')->unique();
$table->timestamps();
```

In my `User` model, I then have a relationship called `plan` which can be used to get the plan for a user, for example: `Auth::user()->plan`.

I wanted to find out whether there's a better way to do this in Cashier as I couldn't find any way, it's also worth noting that I've occasionally noticed that when a user swaps their plan, the joined plan from my `plans` table using this is sometimes returning the original plan that the user was subscribed to, is there something wrong here:

```php
/**
 * Return plan for the user
 */
public function plan()
{
    return $this->hasOneThrough(
      Plan::class, Subscription::class,
      'user_id', 'stripe_id', 'id', 'stripe_price'
    );
}
```

**Comment by driesvints** [comment]
We suggest creating a config file with Stripe Price ID's and then reference that in your app. We also do the same thing in Spark. It should also be noted that the concept of "plan" doesn't exists anymore in Stripe and you now use "price" and "product"/

**Comment by sts-ryan-holton** [comment]
@driesvints Some additional questions based on what you've mentioned: 

1. so is `subscribedToPrice` the recommended way to obtain whether a user is subscribed to a particular price/subscription?
2. I have a database of `plans` (my `Plan` model) with the `prices` in there, isn't what I've got above what you're suggesting? I've seen some strange behaviour with this though, an example from yourself or a member of the Cashier repo publishing a reply to this issue with the best way to link the two would be great!

**Comment by driesvints** [comment]
1. You could but I'd more recommend subscribedToProduct. A price could be a yearly or monthly price for a product. You'd use product to see if you're subscribed to a certain product (or plan or whatever you want to call it) within your app.
2. This seems more like a support question and this issue tracker isn't the right place for that. Please try a support channel from below to get advice from someone.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
