### ISSUE TITLE
Possible unexpected functionality around subscription trials

### ISSUE THREAD

**Issue by benjamindoe** [laravel/cashier-stripe#1306]
- Cashier Version: 13.8.0
- Laravel Version: 8.81.0
- PHP Version: 8.0.15

### Description:
Hi,

I wanted to check if this is expected functionality. If there is a subscription that has been cancelled, either immediately or before the trial end date, the `onTrial()` function still returns true for the cancelled subscription. Is this expected functionality? It has caused unexpected issues for us.

### Steps To Reproduce:
1. Create a subscription with a trial that ends any time in the future
2. Cancel the subscription immediately (or before the trial end date)
3. Call the `$subscription->onTrial()` from cashier. The result will be `true`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
