### ISSUE TITLE
Bug: Duplicate subscriptions being created

### ISSUE THREAD

**Issue by mikewudev** [laravel/cashier-stripe#1307]
- Cashier Version: v13.4.1
- Laravel Version: v8.62.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7

### Description:

Seeing duplicated subscriptions in the DB. Could this possibly be due to `customer.subscription.created` webhook arriving before `SubscriptionBuilder::createSubscription()` is called? 

### Steps To Reproduce:

Not sure how to reproduce, we think it's happening due to webhooks arriving before `SubscriptionBuilder::create()` has completed. Happens rarely for us: ~4% of subscriptions created.

**Comment by driesvints** [comment]
> Seeing duplicated subscriptions in the DB.

But this literally can't happen because of the unique index: https://github.com/laravel/cashier-stripe/blob/13.x/database/migrations/2019_05_03_000002_create_subscriptions_table.php#L20. Are the `stripe_id`'s the same? If so then you haven't applied the unique index.

Still, that's odd. Feel free to share some more info here.

**Comment by driesvints** [comment]
Wondering if https://github.com/laravel/cashier-stripe/issues/1300 by @sts-ryan-holton is a similar one like here.

**Comment by mikewudev** [comment]
> But this literally can't happen because of the unique index: https://github.com/laravel/cashier-stripe/blob/13.x/database/migrations/2019_05_03_000002_create_subscriptions_table.php#L20. 

We've actually extended the `Subscription` model. You're right, looks like we're missing the `unique` index.

Unfortunately it still wouldn't solve the issue, as we'd just end up with the same error as #1300. If it is due a webhook race condition, that would explain not being able to reproduce either.

Tried to write a test for this, but there really isn't a way to simulate a webhook arriving mid-request. If I create a subscription with the same `stripe_price` beforehand, well it'd only be verifying that the unique index works 🙁 

### Example Case

> Sorry in advanced, the following example is specific to our application, but it illustrates why we suspect a race condition.

- We're only creating a subscription in one place:

```php
    protected function createSubscription(
        string $priceId,
        $paymentMethodId = null
    ) {

        // Create subscription via Cashier
        $subscription = $this->newSubscription(Subscription::DEFAULT, $priceId)
            ->create($paymentMethodId, [
                'email' => $this->email,
            ]);

       // Append 'renews_at'
        $stripeSubscriptionData = $this->getStripeSubscriptionData($subscription);

        $renewDate = Carbon::parse($stripeSubscriptionData->current_period_end);

        $subscription->renews_at = $renewDate->toDateTimeString();
        $subscription->save();

        return $subscription;
    }
```

- Resulted in 2 subscriptions

2 Subscriptions with the exact same `created_at`, but the **first does not have `renews_at` set.**

![CleanShot 2022-01-28 at 18 38 37@2x](https://user-images.githubusercontent.com/11449462/151523630-3002f314-b1a4-4731-8a11-34bc694d2b10.png)

As we always set `renews_at` after a `newSubscription->create()` call, makes us believe the subscription was created somewhere else. 

The only other place we can find a subscription being created was in `WebhookController:handleCustomerSubscriptionCreated($payload)`

**Comment by driesvints** [comment]
@mikewudev this should normally solve the issue: https://github.com/laravel/cashier-stripe/pull/1308

I do suggest you add the unique index as there should never, under any circumstances be duplicate subscriptions in the subscriptions table as Cashier isn't designed to handle that and I cannot promise unforeseen errors.

**Comment by mikewudev** [comment]
Thanks @driesvints, that'd do it! Appreciate the quick fix.

**Comment by sts-ryan-holton** [comment]
Could this issue potentially cause such as issue like: https://github.com/laravel/cashier-stripe/issues/1301

**Comment by driesvints** [comment]
@sts-ryan-holton not sure since that's not part of Cashier.
