### ISSUE TITLE
defaultPaymentMethod returning null

### ISSUE THREAD

**Issue by fylzero** [laravel/cashier-stripe#1310]
- Cashier Version: 13.8.0
- Laravel Version: 8.81.0
- PHP Version: 8.1.1
- Database Driver & Version: mysql Ver 8.0.27 for macos12.0 on arm64 (Homebrew)

### Description:
The defaultPaymentMethod() method always returns null even if a user has a default payment method associated.

### Steps To Reproduce:
- Setup Laravel w/ Cashier
- Go to Stripe and create a customer + payment method (set as default), add stripe_id, pm_type, and pm_last_four to users table
- Attempt using `$paymentMethod = $user->defaultPaymentMethod();`
- Returns null

**Comment by fylzero** [comment]
hasDefaultPaymentMethod also returns false.  I've had this issue in multiple projects.

**Comment by fylzero** [comment]
It seems this only works if the default payment method is programmatically set via Cashier.  I couldn't figure out where this is reflected (in the project database or in Stripe).  This method does not reflect Stripe's tagging of a payment method as default.  This was super confusing and should definitely be clarified in the documentation.  I may not have read it close enough....  going to re-read and may submit a PR to Laravel -> Cashier (Stripe) docs, if useful.

**Comment by driesvints** [comment]
> Go to Stripe and create a customer + payment method (set as default), add stripe_id, pm_type, and pm_last_four to users table

I don't think we document doing this anywhere. You should always use Cashier methods to set payment methods and not do things manually.

**Comment by kyranb** [comment]
@driesvints 

What about the use case of using third party software for dunning/payment method updates, or even the default emails that Stripe can send out to customers?

I've seen cases as well where users are unable to swap plans, because their default payment method is `null` even after calling `updateDefaultPaymentMethodFromStripe()`.

**Comment by kyranb** [comment]
For what it's worth `$model->paymentMethods` returns the two payment methods listed for a Stripe Customer.

```
Illuminate\Support\Collection {#5697
     all: [
       Laravel\Cashier\PaymentMethod {#5632},
       Laravel\Cashier\PaymentMethod {#5598},
     ],
   }
```

**Comment by driesvints** [comment]
> I've seen cases as well where users are unable to swap plans, because their default payment method is null even after calling updateDefaultPaymentMethodFromStripe().

In what situation did this happen? The only reason that could be is that the customer is using a legacy source as their default payment method, something which isn't supported anymore (https://stripe.com/docs/api/customers/object#customer_object-default_source)

> Is there a way to look up a payment method from the default_source (which Stripe and others still seem to use) so that this can also be used with the updateDefaultPaymentMethodFromStripe()

This was possible in previous Cashier versions, however, we removed this support completely. It's not recommended to user the Source API anymore and if you have any customers that are on this you'll need to move them to the new payment methods API as recommended by Stripe. Also see the upgrade guide: https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#stripe-sources-support-removed

> if not, perhaps just a mention in the docs of this gotcha would save others some struggles :)

I'll send in a PR to the docs to explicitly note that the Source API is not supported anymore 👍

**Comment by kyranb** [comment]
@driesvints 

> In what situation did this happen?

1. A customer's payment had declined. 
2. They received a dunning email from Profitwell asking them to update their card details.
3. They updated their card details using the form that Proftwell provides.
4. Profitwell sent the following request body to update the customer in Stripe:

{
  "invoice_settings": {
    "default_payment_method": ""
  },
  "source": "tok_XXXXXXXXXXXXX"
}

Stripe's response shows an updated customer with the `default_source` now set/not null:

```
{
  "id": ["cus_XXXX"](https://dashboard.stripe.com/customers/cus_XXXX),
  "object": "customer",
  "account_balance": 0,
  "address": null,
  "balance": 0,
  "created": 1605462857,
  "currency": "usd",
  "default_source": "card_XXXX",
  ```
```

For what it's worth, if a support agent or anyone using the Stripe dashboard, clicks 'set as default payment method' on a customer in the Stripe Dashboard, it will also render set `default_source` as a non null value.

Given that Stripe's own dashboard and many third party tools use the `default_source` parameter despite it being deprecated, I still feel that Cashier should sync with this value if it is set.

Stripe's docs (https://stripe.com/docs/payments/payment-methods/transitioning#compatibility) state that:

> Compatible payment instruments that have been saved to a [Customer](https://stripe.com/docs/api/customers) are usable in any API that accepts a [PaymentMethod](https://stripe.com/docs/api/payment_methods) object. For example, you can use a saved card as a PaymentMethod when creating a PaymentIntent:

Is it possible that Cashier could use this as a fallback while the `default_source` is still present in Stripe's API?

**Comment by driesvints** [comment]
We indeed realize Stripe, under the hood, still uses the Sources API itself. However, this is their own note in their own docs: https://stripe.com/docs/sources/cards

<img width="911" alt="Screenshot 2022-06-21 at 15 53 26" src="https://user-images.githubusercontent.com/594614/174816792-b514d3f1-5db0-4a52-a023-7f53b8277dfe.png">

Therefor, regardless of what Stripe does, we don't consider usage of the Sources API anymore as a valid thing. It's up to Stripe to either move away from this API themselves or adjust their own recommendation in their docs if they still use this API themselves.

**Comment by kyranb** [comment]
@driesvints Gotcha. What would you recommend doing in this case then as a workaround while Stripe and & other apps continue to set this value?

Keeping in mind that while Cashier isn't aware of any other sources being present it continues to set these two values as null on the `CASHIER_MODEL`'s table: https://github.com/laravel/cashier-stripe/blob/a167e294b760159197c459a795c550f6ef31ac23/src/Concerns/ManagesPaymentMethods.php#L202

**Comment by driesvints** [comment]
> What would you recommend doing in this case then as a workaround while Stripe and & other apps continue to set this value?
>
> Keeping in mind that while Cashier isn't aware of any other sources being present it continues to set these two values as null on the CASHIER_MODEL's table:

Unfortunately there really isn't an ideal way right now. Your workaround from the above seems best and would also solve the above issue.

I do fully get the predicament you're in and the awkward situation created here. Trying to check in with Stripe myself to have their 2 cents on the matter.

**Comment by driesvints** [comment]
@kyranb we're going to re-add the basic support for Stripe Sources that we removed in v13. This is probably the most sensible thing to do. Stripe most likely won't be able to fully move away from it any time soon as so we should continue to (partially) support it.

See https://github.com/laravel/cashier-stripe/pull/1384

**Comment by kyranb** [comment]
@driesvints 

Thanks for re-considering this :) Indeed, given that Stripe have said publicly that they'll always support prior API versions this one is likely to be still widely used for a very long time time.
