### ISSUE TITLE
Stripe One Time payment is not working

### ISSUE THREAD

**Issue by 3gHub** [laravel/cashier-stripe#1313]
I am trying to setup Stripe one time payment in an application but getting this error. 

`As per Indian regulations, export transactions require a description. More info here: https://stripe.com/docs/india-exports`

I have added the description as per regulations provided by stripe in code but still I am facing this issue.

This is the code I am using:

```

        $user = auth()->user();
        $paymentMethod = $request->payment_method;
       

        try {
            $user->createOrGetStripeCustomer();
            $user->updateDefaultPaymentMethod($paymentMethod, [
                'currency' => 'INR',
                'description' => 'Software development services',
            ]);

            $user->charge($request->fees*100, $paymentMethod, ['off_session' => true]);

        } catch (\Exception $exception) {
            dd($exception->getMessage());

           
        }
```

First currency was in `USD`. I have changed currency from `USD ` to `INR` but still getting this.

Meanwhile this is my stripe dashboard. Payment is in incomplete mode.

![Screenshot_1](https://user-images.githubusercontent.com/85281650/152634185-d6ebe14d-1217-4d8c-bf96-c7d18ab97ba3.png)

I have used all possible fix but it is not working. Kindly help on this.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
