### ISSUE TITLE
"Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity" swapping metered prices in subscriptions

### ISSUE THREAD

**Issue by pietrantonio91** [laravel/cashier-stripe#1320]
- Cashier Version: 13.7.0
- Laravel Version: 8.73.2
- PHP Version: 7.4.27
- Database Driver & Version: MySQL 8

### Description:
When swapping a subscripton price with a metered price it retrieve this notice:

> Stripe Notice: Undefined property of Stripe\SubscriptionItem instance: quantity

I figured out this should be the problem line: [https://github.com/laravel/cashier-stripe/blob/1a80ccb9b2a691aaa7478f9263e8dbb1eb2bf6f3/src/Subscription.php#L695](https://github.com/laravel/cashier-stripe/blob/1a80ccb9b2a691aaa7478f9263e8dbb1eb2bf6f3/src/Subscription.php#L695)

As I've read in other issues and in docs metered prices must have "null" as quantity value.

So I solved this issue with a simple (similar to [this issue](https://github.com/laravel/cashier-stripe/issues/1254)):

`'quantity' => $item->quantity ?? null`

[Here's my pull request](https://github.com/laravel/cashier-stripe/pull/1319).

### Steps To Reproduce:

1. Create a subscription
2. `$user->subscription()->swap('price_meteredPriceID');`

**Comment by driesvints** [comment]
Thanks for the PR!
