### ISSUE TITLE
Mock the actual HTTP requires a partially re-implement Cashier's own behaviour

### ISSUE THREAD

**Issue by jpswade** [laravel/cashier-stripe#1321]
Reading the documentation for Cashier picks out it's own flaws:

> When testing an application that uses Cashier, you may mock the actual HTTP requests to the Stripe API; however, this requires you to partially re-implement Cashier's own behavior. Therefore, we recommend allowing your tests to hit the actual Stripe API. While this is slower, it provides more confidence that your application is working as expected and any slow tests may be placed within their own PHPUnit testing group.

It would be much better if there was an elegant way to achieve this, either by using swapping implementations, Http::Fake() or a StripeClient mock/fake. All of these would require a change to the implementation.

If there's a groundswell for one of these, I'd be tempted to put together a pull request. I'm not sure I understand why it hasn't been done already though, it seems like a pretty common requirement, especially when a "workaround" has been written in the documentation.

**Comment by driesvints** [comment]
We have no plans to change the API of cashier here. It's better to put Cashier's calls behind your own services and an interface so you can swap it out in tests. I've implemented such a system in one app which works well. Here's a blog post where one part highlights how you can do that: https://driesvints.com/blog/testing-cashier

**Comment by jpswade** [comment]
@driesvints thanks but that doesn't really work for when you're the `createSetupIntent` from the `ManagesPaymentMethods` trait for example.

It's no problem, I guess we'll see if there's any demand for it, I'll likely create a fork and fix it anyway.

Cheers.
