### ISSUE TITLE
Webhook Signature Verification not working

### ISSUE THREAD

**Issue by kumarhardeep01** [laravel/cashier-stripe#1322]
- Cashier Version: 12
- Laravel Version: 7
- PHP Version: 7.4
- Database Driver & Version:7.4.3

### Description:
I am trying to implement webhooks as given in the docs using event listners but it always give the below error
No signatures found matching the expected signature for payload
![image](https://user-images.githubusercontent.com/22958690/153373363-67b2ee4b-1e44-4797-9ce4-3299632601ea.png)
I have already setup the webhook secret in env file. Is their any special things to do in the package so that it can work?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by kumarhardeep01** [comment]
@driesvints thanks for reply but webhook verification does't work for the stated version
