### ISSUE TITLE
Stripe elements

### ISSUE THREAD

**Issue by quantumwebco** [laravel/cashier-stripe#1331]
Is there support coming for the new Elements? Or will this work with the current setup? 

https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements

**Comment by driesvints** [comment]
Yeah this should all just work with current Cashier.

**Comment by quantumwebco** [comment]
It doesn't

**Comment by driesvints** [comment]
What doesn't? Please post some code and more info
