### ISSUE TITLE
cancelNow doesnt cancel in the database

### ISSUE THREAD

**Issue by RemiHin** [laravel/cashier-stripe#1332]
- Cashier Version: 12.10
- Laravel Version: 8.12
- PHP Version: 7.4
- Database Driver & Version: MySQL8

### Description:
We're running a subscription based SAAS project. Customers get a 30 day free trial. After their trial ends, we want to continue only when they have added payment details, if they haven't, the subscription needs to be canceled.
So in the webhookcontroller we have handleCustomerSubscriptionUpdated which contains:
`if(Arr::get($payload, 'previous_attributes.status') === 'trialing'
            && Arr::get($payload, 'object.status') === 'active'
            && ! $user->hasDefaultPaymentMethod()
            && ! $user->hasPaymentMethod()) {
            $user->subscription()->noProrate()->cancelNow();
        }`

It checks if the subscription went from trialing to active (and thus a draft invoice is created), if there is no way to pay the invoice (because no payment details) cancel the subscription.

This succesfully cancels the subscription in Stripe, but in our database the subscription remains "active". Somehow Cashier does update Stripe, but not itself.

Are we doing something wrong? or is this a bug?

**Comment by driesvints** [comment]
This is because of the grace period: https://laravel.com/docs/9.x/billing#cancelled-subscription-status

Cashier takes over the trialing from Stripe. You can skip this with `cancelNow`. Please see: https://laravel.com/docs/9.x/billing#cancelling-subscriptions

**Comment by RemiHin** [comment]
@driesvints thanks, but that is what im doing. Im not using "cancel()", im using "cancelNow()"...

**Comment by driesvints** [comment]
@RemiHin I'm sorry but I only see now that you're overwriting the webhook with some custom code. I don't have time right now to provide support here so please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
