### ISSUE TITLE
Laravel Cashier not working in live mode in subscription Using 3d secure card

### ISSUE THREAD

**Issue by umerghori786** [laravel/cashier-stripe#1333]
- Cashier Version: ^12.4
- Laravel Version: ^8.0
- PHP Version: ^7.3|^8.0
- Database Driver & Version:

### Description:
Hi i am using Laravel cashier for subscription it works perfect on test mode but when it goes on live mode then 3d secure card make an issue.. after click payment button a secure popup open then after verification secure popup close and then nothing happens.. even it no goes further payment method still static the screen, no page load etc.. but in test mode it works. when i insert this 4000000000003220 card number then secore popup open and even it goes to the payment method also...

thanks for any help

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
