### ISSUE TITLE
You cant set the quanity for the prices individualy when you are setting mulitple prices per Subscription.

### ISSUE THREAD

**Issue by sprov03** [laravel/cashier-stripe#1334]
- Cashier Version: 13.8.3
- Laravel Version: 8.83.3
- PHP Version: 8.1
- Database Driver & Version: Mysql 8

### Description:
I am unable to set the quantity value for multiple prices.

### Steps To Reproduce:
Here is the exactly my use case
```
        $user = new User();
        $usageSubscription = $user
            ->newSubscription('usage', [
                ['price' => $this->getUserPriceId(), 'quantity' => 1],
                ['price' => $this->getPhoneNumberPriceId(), 'quantity' => 0]
            ])
            ->create();
```

The Stack Trace:
```
trait ManagesSubscriptions
{
    /**
     * Begin creating a new subscription.
     *
     * @param  string  $name
     * @param  string|string[]  $prices
     * @return \Laravel\Cashier\SubscriptionBuilder
     */
    public function newSubscription($name, $prices = [])
    {
        return new SubscriptionBuilder($this, $name, $prices);
    }
```
```

class SubscriptionBuilder
{
    /**
     * Create a new subscription builder instance.
     *
     * @param  mixed  $owner
     * @param  string  $name
     * @param  string|string[]|array[]  $prices
     * @return void
     */
    public function __construct($owner, $name, $prices = [])
    {
        $this->name = $name;
        $this->owner = $owner;

        foreach ((array) $prices as $price) {
            $this->price($price);   <-----------------  As you can see here the price data is passed in
                                                          Leaving no way to modify the quantity
        }
    }
```

No matter what i do i can not get the quantity to be Zero using cashier. But it is needed because our users get 10 free numbers, but they have to create set them up once their account is created.

Im suggesting a slight modification to \Laravel\Cashier\SubscriptionBuilder::price()

    /**
     * Set a price on the subscription builder.
     *
     * @param  string|array  $price
     * @param  int|null  $quantity
     * @return $this
     */
    public function price($price, $quantity = 1)
    {
        $options = is_array($price) ? $price : ['price' => $price];
        $quantity = $price['quantity'] ?? $quantity;           <---------------  Please Add This line. 
                                                                      It will allow passing in quantity.  
                                                                      Otherwise quantity will always be one.

        if (! is_null($quantity)) {
            $options['quantity'] = $quantity;
        }

        if ($taxRates = $this->getPriceTaxRatesForPayload($price)) {
            $options['tax_rates'] = $taxRates;
        }

        if (is_array($price)) {
            $this->items[] = $options;
        } else {
            $this->items[$price] = $options;
        }

        return $this;
    }

Below i have provided code that can be pasted into any TestCase in a Laravel project, that uses the User for the Stripe Model that shows the provided modification will work as expected.  I also verified it by checking the stripe customer in the stripe console.

    /**
     * @test
     */
    public function canCreateASubscriptionWithMultiplePricesAndDefineQuantityForEach()
    {
        $user = new User();

        $subscription = $user->newSubscription('usage', [
            ['price' => 'stripe_price_one'],
            ['price' => 'stripe_price_two_one', 'quantity' => 1],
            ['price' => 'stripe_price_id', 'quantity' => 0]
        ]);

        $items = self::privatePropertyAccessor($subscription, 'items');
        $expected = [
            ["price" => "stripe_price_one", "quantity" => 1],
            ['price' => 'stripe_price_two_one', 'quantity' => 1],
            ["price" => "stripe_price_id", "quantity" => 0]
        ];
        $this->assertEquals(json_encode($expected), json_encode($items));
    }
    public static function privatePropertyAccessor($object, $property)
    {
        $reflectedClass = new \ReflectionClass($object);
        $reflection = $reflectedClass->getProperty($property);
        $reflection->setAccessible(true);
        return $reflection->getValue($object);
    }

**Comment by driesvints** [comment]
Heya, thanks. I'm sending in a PR for this here: https://github.com/laravel/cashier-stripe/pull/1336.
