### ISSUE TITLE
Cancel immediately at stripe does not end trial in Cashier

### ISSUE THREAD

**Issue by AndyMillne** [laravel/cashier-stripe#1335]
- Cashier Version: 9.x
- Laravel Version: 9.3.1
- PHP Version: 8.1
- Database Driver & Version: MySQL 8

### Description:

If a subscription is cancelled at Stripe immediately when still in trial period, the trial end dates in Cashier are not updated. 

This is expected for cancelling in stripe while retaining the end date but  if you cancel using the "cancel immediately" option it would be expected this would also update in Cashier.

### Steps To Reproduce:

1. Subscribe a user using the trialDays() method.
2. Cancel subscription via stripe portal using the "cancel immediately" option.
3. Observe that the subscription record stripe_status in the database has updated to canceled but the trial_ends_at date is still in the future.
4. Observe that the Cashier user onTrial() method returns TRUE even though it has been cancelled with immediate affect.

Expected behavior would be that the onTrial method checked the stripe_status in addition to the end_date or the web hook customer.subscription.deleted event would reset the trial_ends_at date to NULL

**Comment by driesvints** [comment]
Hey @AndyMillne,

Cancelling a subscription has nothing to do with their trial dates. A customer can still use the remaining trial period when their subscription is cancelled immediately. I'm pretty sure that `trial_end` is still set into the future on your subscription even if you cancelled immediately. 

If you still feel that this is not correct, we'd welcome PR's to improve this as long as they don't break backwards compatibility.
