### ISSUE TITLE
Swapping prices on subscription

### ISSUE THREAD

**Issue by vwmoose** [laravel/cashier-stripe#1337]
- Cashier Version: 13.8
- Laravel Version: 9.4
- PHP Version: 8.1.3

### Description:
I'm using a model other than User with the Billable trait.  When I attempt to swap prices on an existing subscription attached to the model in questions I get an error "Trying to access array offset on value of type bool".  I've traced this back to a method in Subscription.php :-

```
    /**
     * Get the model related to the subscription.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function owner()
    {
        $model = Cashier::$customerModel;

        return $this->belongsTo($model, (new $model)->getForeignKey());
    }
```
To fix the issue I've simply replaced the "getForeignKey()"  on the (new $model) with "getKeyName()" which rather than returning a string eg "dealer_id" simply returns "id".

I guess what I'm asking here is this considered a bug as the majority of models attached to a subscription will probably have an "id" field and the generated foreign key returned by "getForeignKey" is simply the model name with the key field separated by an underscore eg "dealer_id"?

### Steps To Reproduce:

Use another model other than User with the Billable trait.
Add a subscription with a price to the model.
Use swap on the existing subscription to change to another price.

**Comment by driesvints** [comment]
Hi @vwmoose. `getForeignKey` is the correct method. It referenced indeed in your case to `dealer_id`. This needs to match the database column here: 

https://github.com/laravel/cashier-stripe/blob/eef3b68d498886a0d1e4d3c6194c55f4f5ba98ff/database/migrations/2019_05_03_000002_create_subscriptions_table.php#L18

You can't return `id` or it'll reference the subscription ID which isn't wanted. 

Is what your saying that the primary ID column of the model you're referring to not named `id`? What is it called in your database?

**Comment by vwmoose** [comment]
@driesvints thanks for you reply - my problem is that I will have multiple models using the Billable trait and therefor the foreign key could be _user_id_ or _dealer_id_.  Is there anyway that Cashier can handle that?

**Comment by driesvints** [comment]
Atm Cashier can only handle one type of model.
