### ISSUE TITLE
Laravel cashier swapping always taking immediate effect

### ISSUE THREAD

**Issue by santanubiswascispl** [laravel/cashier-stripe#1338]
- Cashier Version: 10.1
- Laravel Version: 6.x
- PHP Version: 7.2
- Database Driver & Version:

### Description:

As per the documentation `swap()` method swap the current subscription with the new one on the `next billing date`, means after end of current plan. And `swapAndInvoice()` will take immediate effect without waiting for the current plan to end.

But the `swap()` method is not working as described. It is taking immediate effect.

Below are the 2 different tries, but not working, it's always taking immediate effect.

`$subscription_result = $user->subscription('primary')->swap('new_price_id');`
`$subscription_result = $user->subscription('primary')->noProrate()->swap('new_price_id');`

example,

Plan A :- 3 days ($3)
Plan B :- 7 days ($7)
User subscribed to Plan A on 25th March, next billing cycle is on 28th March. User changed subscription to Plan B on 25th March, it should take effect on 28th (using swap() method). But it is taking effect immediately and showing next billing cycle is on 1st April.

I have tried using swapAndInvoice() instead of swap(), but both the methods are giving same output, no difference.

**Comment by driesvints** [comment]
> As per the documentation swap() method swap the current subscription with the new one on the next billing date,

I don't know why you seem to think that but that's not what the documentation says. It says:

> If you would like to swap prices and immediately invoice the customer instead of waiting for their next billing cycle, you may use the swapAndInvoice method:

This means that `swap` will swap the plan but only invoice the customer on the next billing cycle. The plan switch will still be immediately. `swapAndInvoice` will also switch the plan immediately but at the same time immediately invoice the customer as well.
