### ISSUE TITLE
`user()->stripe()` doesn't seems to be a function

### ISSUE THREAD

**Issue by TonnyORG** [laravel/cashier-stripe#1339]
- Cashier Version: v12.17.0
- Laravel Version: 9.x
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.x

### Description:

`$user->stripe()` function doesn't exists, maybe the documentation is out dated?

`Call to undefined method App\Models\User::stripe()` on `$checkoutSession = $request->user()->stripe()->checkout->sessions->retrieve($request->get('session_id'));`

I'm following this doc in specific: https://laravel.com/docs/9.x/billing#product-checkouts

### Steps To Reproduce:

My current setup involves Laravel Jetstream + Spark (Stripe).
I'm billing the user subscription through spark but I am also charging "addons" on demand to the user so I'm doing checkout on individual products as per user's request.

**Comment by driesvints** [comment]
It's available in Cashier 13, not cashier 12.
