### ISSUE TITLE
Call to undefined method Laravel\Cashier\Subscription::canceled()

### ISSUE THREAD

**Issue by khlewesamer** [laravel/cashier-stripe#1347]
- Cashier Version: 12.5
- Laravel Version: 8.*
- PHP Version: 7.3
- Database Driver & Version:

### Description:
there is no canceled method on cashier 
`if ($user->subscription('default')->canceled()) {
    //
}`

i check  the Subscription.php on Cashier and found the function called cancelled
`if ($user->subscription('default')->cancelled()) {
    //
}`

**Comment by driesvints** [comment]
You're reading the docs of the latest version v13 which have these and you're using v12.
