### ISSUE TITLE
Not sure if syncStripeStatus() is working with $user->subscribed()  

### ISSUE THREAD

**Issue by OlyRice** [laravel/cashier-stripe#1350]
Hello

I am trying to implement a check to see if a subscription is active after running `syncStripeStatus()` but even when the subscription is canceled `$user->subscribed() ` returns true. 

At the minute I have the following Middleware that runs the check

```
public function handle(Request $request, Closure $next)
    {

        $user = Auth::user(); 

        optional($user->subscription($this->subscription_name))->syncStripeStatus();

        // User already has an active subscription
        if (!$user->subscribed($this->subscription_name)) {

            return redirect('/subscribe?error='.urlencode("subscription not active"));

        }

        return $next($request);
    }
}
```

Now as a test I created the subscription and then within a few minutes I went into Stripe and did a cancel immediately. Checked the database and the subscription was changed to canceled 

<img width="1273" alt="Screenshot 2022-04-23 at 13 01 22" src="https://user-images.githubusercontent.com/347289/164958224-43ddd0d9-2cba-49ca-850e-0fa1abe98913.png">

However whenever I run the above `$user->subscribed($this->subscription_name)` always returns true.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
