### ISSUE TITLE
Bug on assigning stripe_price and quantity on subscription with multiple items

### ISSUE THREAD

**Issue by etaroza** [laravel/cashier-stripe#1351]
These lines seem to be contradicting. In one case we're setting NULL on the other non-null. What is the correct assignment?

https://github.com/laravel/cashier-stripe/blob/2147b8eb1249e94b36b95ad4ffff35b37eebe320/src/Subscription.php#L896

```
        if ($this->hasSinglePrice()) {
            $this->fill([
                'stripe_price' => null,
                'quantity' => null,
            ])->save();
        }
```

https://github.com/laravel/cashier-stripe/blob/2147b8eb1249e94b36b95ad4ffff35b37eebe320/src/Subscription.php#L720
```
         $this->fill([
            'stripe_status' => $stripeSubscription->status,
            'stripe_price' => $isSinglePrice ? $firstItem->price->id : null,
            'quantity' => $isSinglePrice ? $firstItem->quantity : null,
            'ends_at' => null,
        ])->save();
```

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template
