### ISSUE TITLE
Assigning stripe_price and quantity on subscription with multiple items

### ISSUE THREAD

**Issue by etaroza** [laravel/cashier-stripe#1352]
- Cashier Version: 13.8.6
- Laravel Version: 8.83.8
- PHP Version: 8.0
- Database Driver & Version:

### Description:
These lines seem to be contradicting. In one case we're setting NULL on the other non-null. What is the correct assignment?

https://github.com/laravel/cashier-stripe/blob/2147b8eb1249e94b36b95ad4ffff35b37eebe320/src/Subscription.php#L896

```
        if ($this->hasSinglePrice()) {
            $this->fill([
                'stripe_price' => null,
                'quantity' => null,
            ])->save();
        }
```

https://github.com/laravel/cashier-stripe/blob/2147b8eb1249e94b36b95ad4ffff35b37eebe320/src/Subscription.php#L720
```
         $this->fill([
            'stripe_status' => $stripeSubscription->status,
            'stripe_price' => $isSinglePrice ? $firstItem->price->id : null,
            'quantity' => $isSinglePrice ? $firstItem->quantity : null,
            'ends_at' => null,
        ])->save();
```

**Comment by driesvints** [comment]
The `addPrice` method checks if the subscription was a single price. If a new price was added, we'll need to clear those values because it's now a multiplan subscription. So the logic is the same.
