### ISSUE TITLE
Rendering an invoice causes a deprecation warning

### ISSUE THREAD

**Issue by oprypkhantc** [laravel/cashier-stripe#1355]
- Cashier Version: 13.9.0
- Laravel Version: 9.10.0
- PHP Version: 8.1.5

### Description:
`formatLocalized` Carbon method has been deprecated due to deprecation of `strftime` in PHP 8.1: https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/Date.php#L1836

This then causes a deprecation warning when trying to render an invoice of a subscription here: https://github.com/laravel/cashier-stripe/blob/9661eade4ae42fb0b0b7b351d2d1dc5f10cedb78/resources/views/receipt.blade.php#L217

```log
[2022-04-30 21:28:43] pipeline.WARNING: ErrorException: Function strftime() is deprecated in /app/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1851
[2022-04-30 21:28:43] pipeline.WARNING: ErrorException: Function strftime() is deprecated in /app/vendor/nesbot/carbon/src/Carbon/Traits/Date.php:1851
```

### Steps To Reproduce:
1. Configure [Laravel's deprecations log](https://laravel.com/docs/9.x/logging#logging-deprecation-warnings) as per docs
2. Create a subscription and an invoice, then render it:
```php
$user->subscription()->invoice()->view()->render();
```
3. See two deprecation warnings in the log

**Comment by driesvints** [comment]
Thanks for reporting this. I sent in a PR to fix that: https://github.com/laravel/cashier-stripe/pull/1356

**Comment by oprypkhantc** [comment]
Thank you!
