### ISSUE TITLE
Error: Class "App\Providers\User" not found

### ISSUE THREAD

**Issue by jurri** [laravel/cashier-stripe#1357]
- Cashier Version: 13.9
- Laravel Version: 9.2
- PHP Version: 8.0.18
- Database Driver & Version: MySQL 8.0.28

### Description:
if I call one cancelling-function from subscriptionit thtow the error: Class "App\Providers\User" not found.
`$user->subscription('default')->cancelNow();` or `$user->subscription('default')->cancel();`

Creating a Subscription worked fine.

### Steps To Reproduce:
Using Laravel 9 with Laradock Master, Jetstream 2.7, breeze 1.9 and cashier

Everytime this mistake comes if called the owner in one of method of class Subscription
` * @property \Laravel\Cashier\Billable|\Illuminate\Database\Eloquent\Model $owner`
`$this->owner->stripe()->subscriptions->cancel()` 

to cancel a subscription I can use `$user->subscription('default')->markAsCanceled()`
and than I cancel it on stripe with my own function which looks like this.
```php
$key = \config('services.stripe.secret');
$stripe = new \Stripe\StripeClient($key);
$stripe->subscriptions->cancel(
    $this->stripe_id,
    ['prorate' => $this->prorateBehavior() === 'create_prorations',]
);
```

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
