### ISSUE TITLE
Cashier uses default payment on invoice not customer

### ISSUE THREAD

**Issue by oscarmorrison** [laravel/cashier-stripe#1358]
- Cashier Version: ^13.8
- Laravel Version: ^9.2
- PHP Version: ^8.1
- Database Driver & Version: MySQL 5.6.10

### Description:
![image](https://user-images.githubusercontent.com/1651212/166336618-8a7538ca-7fc6-4022-aca6-e9e2c6874d99.png)

When using the method `defaultPaymentMethod()` and `updateDefaultPaymentMethod()` cashier-stripe pulls the default payment method from the customer invoice setting: `$customer->invoice_settings->default_payment_method`. This value is not set if using the stripe dashboard to set payment defaults on customers. 

We should be using the `default_source` on the customer. 

There can be a bug where you have a default payment method set on the customer (in stripe), and `hasDefaultPaymentMethod()` and `defaultPaymentMethod()` return false and null. 

### Steps To Reproduce:

- setup a customer 
- go into the stripe dashboard
- manually change the default payment
- this will trigger a `customer.updated` event
- laravel cashier will handle the webhook, and remove the `pm_type` and `pm_last_four` from the database

**Comment by driesvints** [comment]
That's correct. In Cashier v13 we dropped all legacy support for Stripe Sources/Tokens. Stripe itself recommends not using it anymore.

This was noted in the upgrade guide: https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#stripe-sources-support-removed

And this was noted in the upgrade guide of Cashier v10: https://github.com/laravel/cashier-stripe/blob/13.x/UPGRADE.md#cards-and-payment-methods

<img width="1090" alt="Screenshot 2022-05-03 at 09 34 09" src="https://user-images.githubusercontent.com/594614/166418360-c3460f4e-d466-4e0e-aa9b-ca697258dfe3.png">

We strongly recommend you to upgrade all of your customers to the new payment methods API as soon as you can.

**Comment by oscarmorrison** [comment]
Thankyou @driesvints 🙌
