### ISSUE TITLE
Tax rate can be string or object

### ISSUE THREAD

**Issue by joshhanley** [laravel/cashier-stripe#1362]
- Cashier Version: 13.10.0
- Laravel Version: 9.11.0
- PHP Version: 8.1.3
- Database Driver & Version: Mysql 8.0.28

### Description:
When trying to call `$user->downloadInvoice(...)` for customers subscribed to products with an Australian tax rate, the following error occurs:

![Screen Shot 2022-05-11 at 5 39 04 pm](https://user-images.githubusercontent.com/882837/167795112-efcc1d4d-b04f-4c36-bcb1-11cec4b73cb6.png)

For customers subscribed to a products with US tax rate it all works happily and the invoice downloads.

I did some digging and found that the issue is that an `InvoiceLineItem->tax_amounts->tax_rate` can actually be either a string or an object.

See this screenshot for an example of a product with an Australian tax rate:
<img width="616" alt="Screen Shot 2022-05-11 at 5 09 57 pm" src="https://user-images.githubusercontent.com/882837/167794579-ec9c3139-f0bb-47fc-a8a3-17dbb6a69ccd.png">

And see this screenshot for an example of a product with a US tax rate:
<img width="700" alt="Screen Shot 2022-05-11 at 5 10 35 pm" src="https://user-images.githubusercontent.com/882837/167794709-77334669-d149-405a-813b-386d904c7a69.png">

I also checked out the Stripe API and it turns out that the `tax_rate` can either be a string, or expanded into an object

https://stripe.com/docs/api/invoices/line_item#invoice_line_item_object-tax_amounts-tax_rate
![image](https://user-images.githubusercontent.com/882837/167794925-2b856540-110b-45b4-9814-4f137defddca.png)

### Steps To Reproduce:

Create a customer in Cashier and create a subscription to a product in AUD which has Stripe Tax enabled for Australia, then try to download the invoice using 

```php
$request->user()->downloadInvoice($invoiceId, [
        'vendor' => 'Your Company',
        'product' => 'Your Product',
]);
```

Not sure how best to handle this, but happy to look into PR'ing a fix if some guidance can be provided on how it should be handled if the `tax_rate` is only returning a string.

We could potentially iterate through all the `tax_rates` earlier and check if any of them are strings.

But then what should `calculateTaxPercentageByTaxAmount()` do? Should ignore any that are a string or should it try to fetch the full `tax_rate` object?

If you need any more information or an example repo, please let me know and I'll see if I can set one up.

Thanks in advance!

**Comment by driesvints** [comment]
That's odd because this data is always expanded when line items are used on the invoice: 

https://github.com/laravel/cashier-stripe/blob/9cbc29124cce741a436090d6813e20022cb99c26/src/Invoice.php#L400

Can you please post the full stack trace of the error? Or share the Flare report?

**Comment by driesvints** [comment]
I'll re-open this once you managed to post the full stack trace. Thanks

**Comment by joshhanley** [comment]
Sorry Dries! Went on holiday then got put on a different part of the project. Will see if I can create an isolated test and if so will let you know and link to it.

**Comment by vwmoose** [comment]
I've just today started getting this very same issue.  I'm currently running API version 2020-08-27.

The following line is attempting to access "percentage" on a string: https://github.com/laravel/cashier-stripe/blob/635f8b81cacdcc963dc55d124916a8a65553f639/src/InvoiceLineItem.php#L138 is totalling $tax_amount->tax_rate->percentage when $tax_amount->tax_rate is defined as a string in the API reference below.  

Looking at the API reference https://stripe.com/docs/api/invoices/line_item, "tax amounts" don't have a child attribute of "percentage" but "tax_rates" do.

Hope this helps fix the problem?

**Comment by driesvints** [comment]
@vwmoose "tax_rate" is expandable on the tax amount. We do this before calling any invoice line item method on the invoice object: https://github.com/laravel/cashier-stripe/blob/14.x/src/Invoice.php#L581

So as far as I know, there's no issue here. You also seem to be using an outdated API version as v14 uses 2022-08-01. If you provide the exact code that triggers this I could have a look.
