### ISSUE TITLE
laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at 

### ISSUE THREAD

**Issue by People-Sea** [laravel/cashier-stripe#1364]
- Cashier Version: #.#.#
- Laravel Version: 9.12.2
- PHP Version: PHP 8.0.18 (cli) (built: May 13 2022 10:02:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.18, Copyright (c) Zend Technologies
- Database Driver & Version:

### Description:
[2022-05-13 02:57:06] laravel.WARNING: Required parameter $id follows optional parameter $list in /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Support/Tree.php on line 250  
[2022-05-13 02:57:06] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [deprecations] is not defined. at /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:207)
[stacktrace]
#0 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(132): Illuminate\\Log\\LogManager->resolve()
#1 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(119): Illuminate\\Log\\LogManager->get()
#2 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(108): Illuminate\\Log\\LogManager->driver()
#3 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(122): Illuminate\\Log\\LogManager->channel()
#4 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(71): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleDeprecationError()
#5 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#6 /www/wwwroot/ylsk/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#7 /www/wwwroot/ylsk/vendor/composer/ClassLoader.php(571): include()
#8 /www/wwwroot/ylsk/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()
#9 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Controller/AuthRule.php(120): Composer\\Autoload\\ClassLoader->loadClass()
#10 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Larke\\Admin\\Controller\\AuthRule->indexTree()
#11 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#12 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#13 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#14 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#15 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/AdminCheck.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\AdminCheck->handle()
#17 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/Permission.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\Permission->handle()
#19 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/CheckLoginType.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\CheckLoginType->handle()
#21 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/Authenticate.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\Authenticate->handle()
#23 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/CheckLang.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\CheckLang->handle()
#25 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#27 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#28 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#29 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#30 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#31 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#32 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/RequestOptions.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\RequestOptions->handle()
#34 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#37 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#40 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#42 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#44 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#46 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#48 /www/wwwroot/ylsk/vendor/lake/larke-admin/src/larke/admin/Middleware/JsonExceptionHandler.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Larke\\Admin\\Middleware\\JsonExceptionHandler->handle()
#50 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#52 /www/wwwroot/ylsk/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#53 /www/wwwroot/ylsk/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#54 {main}
"}

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
