### ISSUE TITLE
Investigate Changes Needed To Support Link Payment

### ISSUE THREAD

**Issue by timleland** [laravel/cashier-stripe#1371]
Stripe has a new [Payment Element called **Link**](https://stripe.com/docs/payments/link) that is currently in beta. I attempted to get it to work within Cashier but ran into a few issues. 

The first is that the "Last 4" is not returned from the Stripe API when using **Link**. This causes an error when trying to call [fillPaymentMethodDetail()](https://github.com/laravel/cashier-stripe/blob/a167e294b760159197c459a795c550f6ef31ac23/src/Concerns/ManagesPaymentMethods.php#L220-L226)

There could be other issues that I am not aware of. Additional info on [How to accept a payment with Link](https://stripe.com/docs/payments/link/accept-a-payment?platform=web#web-create-intent)

Let me know if additional information is needed. Thanks!

**Comment by driesvints** [comment]
How are you trying to call `fillPaymentMethodDetails`? Please share the code you're using.

**Comment by timleland** [comment]
The ```fillPaymentMethodDetails``` method is called when a webhook comes in from Stripe and calls ```pdateDefaultPaymentMethodFromStripe()``` 
 https://github.com/laravel/cashier-stripe/blob/3e8f1e60b153452e10a9ac35c913c6356face7d4/src/Concerns/ManagesPaymentMethods.php#L194

**Comment by driesvints** [comment]
Do you perhaps have a content of the payload that arrives that I can check?

**Comment by timleland** [comment]
I was able to debug my issue and found the problem. I don't think any fix is needed in cashier. Thanks for looking at this.

**Comment by driesvints** [comment]
What was the problem? Would help the next time someone's posting anything similar 🙂

**Comment by timleland** [comment]
I wish I knew. Either Stripe made a change to their API that changed the response or I had something configured wrong on my end. I wasn't able to reproduce the issue to provide you with the logs. If anyone runs into a similar issue, please reach out and I would be happy to help.
