### ISSUE TITLE
Support for applies_to attribute in coupon object

### ISSUE THREAD

**Issue by rgbaman** [laravel/cashier-stripe#1372]
- Cashier Version: 13.11.0
- Laravel Version: 9.14.1
- PHP Version: 8.1.6
- Database Driver & Version: MySQL

### Description:
Not sure if this is a bug or a feature request.

The Stripe docs refer to an attribute named `applies_to` in the coupon object (https://stripe.com/docs/api/coupons/object#coupon_object-applies_to) which doesn't appear when I `dd` the response from `$user->findPromotionCode('MYCODE')->coupon()`. It's quite important as it allows me to validate whether a customer has selected a qualifying subscription production and then handle the outcome.

### Steps To Reproduce:
```
$coupon = $user->findPromotionCode('TEST')->coupon()
dd($coupon)
```
Response:
```
#_opts: Stripe\Util\RequestOptions {#1348 ▶}
    #_originalValues: array:15 [▶]
    #_values: array:15 [▶]
    #_unsavedValues: Stripe\Util\Set {#1346 ▶}
    #_transientValues: Stripe\Util\Set {#1347 ▶}
    #_retrieveOptions: []
    #_lastResponse: null
    +saveWithParent: false
    id: "[redacted]"
    object: "coupon"
    amount_off: null
    created: 1653990191
    currency: "gbp"
    duration: "once"
    duration_in_months: null
    livemode: false
    max_redemptions: null
    metadata: Stripe\StripeObject {[#1349 ▶](http://192.168.1.68:8000/subscribe#sf-dump-471138211-ref21349)}
    name: "TEST"
    percent_off: 50.0
    redeem_by: null
    times_redeemed: 0
    valid: true
```
Any help appreciated.

**Comment by driesvints** [comment]
Could maybe implement an `appliesTo` method that calls a `refreshWithExpandedData` method like in the invoice object: https://github.com/laravel/cashier-stripe/blob/13.x/src/Invoice.php#L391

We'd accept a PR for that if you're willing to send one in. Thanks
