### ISSUE TITLE
name of subscription cannot be changed on swapping subscription

### ISSUE THREAD

**Issue by Cluster2a** [laravel/cashier-stripe#1385]
- Cashier Version: 13.5
- Laravel Version: 8.54
- PHP Version: 8.1
- Database Driver & Version: mysql:8.0.28

### Description:
In the WebhookController.php is the following line:
```php
$subscription->name = $subscription->name ?? $data['metadata']['name'] ?? $this->newSubscriptionName($payload);
```

Since the field _name_ is not nullable $subscription->name will be empty, but never null.
So $subscription->name ?? will never evaluate any code that comes afterward, if the table is once created.

If you are swapping a subscription the name can never be changed. Not sure if this is meant to be like this.

### Steps To Reproduce:
- create a subscription
- remove name of subscription ($activeSubscription->update(['name' => null]);)
- swap subscription
- field will be empty, even though $data['metadata']['name'] is set

**Comment by driesvints** [comment]
You can never rename a subscription. A subscription name is intended to stay the same always.
