### ISSUE TITLE
In the webhook the subscriptions name is always default 

### ISSUE THREAD

**Issue by JimmyBillan** [laravel/cashier-stripe#1390]
Hello,

When we add a subscription to a user from stripe dashboard, the subscription name save in database is always 'default'.
You try to find the product id in data['metadata']['name'] instead of  $firstItem['price']['product']
https://github.com/laravel/cashier-stripe/blob/3c9b2ed1a799be79a52e449c5aea1512b8b939e3/src/Http/Controllers/WebhookController.php#L84

And in newSubscriptionName the payload is declared but not used : 
https://github.com/laravel/cashier-stripe/blob/3c9b2ed1a799be79a52e449c5aea1512b8b939e3/src/Http/Controllers/WebhookController.php#L115

The table subscriptions is not clean.
The one created from cashier with $user->newSubscription("prod_XXXX", "price_XXXX")  got a name ("prod_XXXX")
The one created from the stripe dashboard have "default" 

![image](https://user-images.githubusercontent.com/7822743/177419035-acca9ccb-e990-4cc1-a71b-180027055895.png)

**Comment by driesvints** [comment]
You're mis-using the `newSubscription` method. It needs to be `$user->newSubscription('default')`. The `newSubscriptionName` method on the webhook controller exists to be overwritten in case you're using a different name than the default one. You can then use the event payload to determine which name you need to give your subscription.

Please also fill out the issue template next time and try a support channel if you need to ask questions. This issue tracker is only for bugs.
