### ISSUE TITLE
Incomplete payment hosted page error

### ISSUE THREAD

**Issue by bscrap** [laravel/cashier-stripe#1394]
- Cashier Version: 13.12.0
- Laravel Version: 8.83.6
- PHP Version: 8.0
- Database Driver & Version: MySQL

### Description:

I am using Cashier's hosted confirmation page for incomplete payments handling.
Recently, the page stopped working and ends up endlessly processing once the `Confirm xx` button is clicked.

It seems the `payment_method` is empty and that's what causes the issue.

I also got bunch of js errors too : 

```
TypeError: undefined is not an object (evaluating 'this.paymentMethod.element')
configureStripeElements — payment_intent:260
configureStripeElements
mounted — payment_intent:206
He — vue.min.js:6:11402
Yt — vue.min.js:6:25342
(anonymous function) — vue.min.js:6:68323
(anonymous function) — vue.min.js:6:33045
wn — vue.min.js:6:30374
Global Code — payment_intent:188
```

Payment intent data: 
`            data() {
                return {
                    paymentIntent: {"id":"payment_intent","client_secret":"client_secret","payment_method_types":["acss_debit","card"],"status":"requires_payment_method"},
                    paymentMethod: null,
                    name: 'Admin',
                    email: 'admin@admin.admin',
                    paymentElement: null,
                    remember: false,
                    isPaymentProcessing: false,
                    errorMessage: ''
                }
            },`

**Comment by bscrap** [comment]
I can produce the issue with `4000 0000 0000 3063` card and `requires_payment_method ` action. For some reason you have to be a first time customer.

**Comment by bscrap** [comment]
Hello @driesvints, thank you very much for such a fast reply! I really appreciate it.

It does happen in real-life situations though. We have first discovered this issue in production, i can provide more information. I am able to reproduce the issue right now with all users whose subscription is in `incomplete` state.

Please let me know how can i assist you.

**Comment by driesvints** [comment]
I'll need exact steps to reproduce.

**Comment by bscrap** [comment]
I can dump the response from Stripe if you wanna.

**Comment by driesvints** [comment]
Yes please share the response.

**Comment by bscrap** [comment]
<img width="456" alt="Dump" src="https://user-images.githubusercontent.com/109102629/179014935-6f7d9b85-69db-4e52-8fc8-1d1f336f95de.png">

**Comment by driesvints** [comment]
Sorry, only getting back to this now. Can you please provide a repo that reproduces this?

```bash
laravel new bug-report --github="--public"
```

**Comment by driesvints** [comment]
If you can provide that repo I'll reopen this. Thanks
