### ISSUE TITLE
Stripe is not able to process SCA

### ISSUE THREAD

**Issue by ruppphilipp** [laravel/cashier-stripe#1398]
- Cashier Version: 13.8
- Laravel Version: 8.83.16
- PHP Version: 8.0
- Database Driver & Version:

### Description:
I am creating a stripe user and set up a subscription in the backend. The flow is successful whenever no SCA is required. When I test the application with card number 4000002500003155 (which always requires SCA), I route to stripe's cashier.payment to handle the SCA. When I click on the "confirm payment" button, the javascript throws an error ' `TypeError: Cannot read properties of undefined (reading 'id')`' and is not able to process the data.
It appears that `$e->payment->payment-method` is null, but `$user->paymentMethods()->first()` is not. Why is `payment-method ` not attached to `$e->payment`?

### Steps To Reproduce:
```
        $user = auth()->user();
        $token =  $request->stripeToken;
         Stripe::setApiKey(env('STRIPE_SECRET'));
         $user->createAsStripeCustomer();

            Customer::createSource(
                $user->stripe_id,
                ['source' => $token]
            );

        try {
            $user->newSubscription('default', env('STRIPE_PRODUCT'))
                ->create($user->paymentMethods()->first()->id, [
                    'email' => $user->email,
                ]);



            return redirect('/dashboard')->with('success', 'Subscription is completed.');

        } catch (Exception $e) {
            //forward to sca authenticate payment

            // dd($e->payment);
            if ($e instanceof IncompletePayment) {
                return redirect()->route(
                            'cashier.payment',
                            [$e->payment->id, 'redirect' => route('dashboard')]
                        );
            }
        }
```
### Where the route goes

![Screenshot 2022-07-15 at 13 28 22](https://user-images.githubusercontent.com/72299616/179215331-e83ac7f7-718f-4ea5-b3f7-0d29a8848ee3.png)

### Where the page is stuck

![Screenshot 2022-07-15 at 13 28 28](https://user-images.githubusercontent.com/72299616/179215326-c5ebd534-5e40-4613-a621-8a4ba167a1a3.png)

### Javascript error from console
![Screenshot 2022-07-15 at 13 28 33](https://user-images.githubusercontent.com/72299616/179215351-4f40c635-80b3-4b23-be65-194ec88b7f3d.png)

### Javascript where the error refers to
![Screenshot 2022-07-15 at 13 28 47](https://user-images.githubusercontent.com/72299616/179215403-305ea247-f28f-4fbf-b9e9-f4f6eccc3deb.png)

### snippet of dd($e->payment); which shows that payment_method is actually null
![Screenshot 2022-07-15 at 14 29 11](https://user-images.githubusercontent.com/72299616/179223121-6705c9bf-2b99-4449-8791-4aba7fa1b350.png)

**Comment by ruppphilipp** [comment]
A possible solution to the mentioned problem is to add the payment_method manually to the paymentIntent as in 
```
if ($e instanceof IncompletePayment) {
                $stripeClient = new StripeClient( env("STRIPE_SECRET"));
                $stripeClient->paymentIntents->update(
                    $e->payment->id,
                    ['payment_method' => $user->paymentMethods()->first()->id,]);

                return redirect()->route(
                            'cashier.payment',
                            [$e->payment->id, 
                            'redirect' => route('dashboard')]
                        );
            }
```
I could not find any documentation on that or anything similar. Is this considered good practice?

**Comment by driesvints** [comment]
I couldn't reproduce this. Please provide a repo with the following command and I'll re-open this issue to try again.

```bash
laravel new bug-report --github="--public"
```
