### ISSUE TITLE
Issue setting up webhook route "Route [cashier.webhook] not defined."

### ISSUE THREAD

**Issue by n1cklarosa** [laravel/cashier-stripe#1402]
- Cashier Version: v13.13.0
- Laravel Version: v9.21.3
- PHP Version: v8.1.8
- Database Driver & Version: Mysql 8

### Description:

While following the setup instructions I get the following error when I try and run `php artisan cashier:webhook` 
I have made stripe customers for all my users without issue. I am using JWT authentication with Laravel acting as a backend for a number of front ends - no front code is handled in the laravel project itself.

I am sorry if I have posted this in the wrong place. If so, please let me know where I should look for a hand. It feels extreme logging this as a bug, as I am sure it is something I am doing wrong. Thanks 

```Symfony\Component\Routing\Exception\RouteNotFoundException 

  Route [cashier.webhook] not defined.

  at vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:467
    463▕         if (! is_null($route = $this->routes->getByName($name))) {
    464▕             return $this->toRoute($route, $parameters, $absolute);
    465▕         }
    466▕ 
  ➜ 467▕         throw new RouteNotFoundException("Route [{$name}] not defined.");
    468▕     }
    469▕ 
    470▕     /**
    471▕      * Get the URL for a given route instance.

      +15 vendor frames 
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()```

### Steps To Reproduce:

This is a project for a client I am unable to share, but I am happy to share anything that may help me figure out what is happening.

<!-- laravel new bug-report --github="--public" -->

**Comment by n1cklarosa** [comment]
I believe I have got around this by adding the following to the routes/web.php file

```Route::get('stripe/payment/{id}', 'Laravel\Cashier\Http\PaymentController@show')->name('cashier.payment');
Route::post('stripe/webhook', 'Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook')->name('cashier.webhook');
 ```

Does anyone see a reason who this would not be ideal?
thanks in advance.

**Comment by driesvints** [comment]
On a default Laravel installation I did not experience this. It seems that the command can't find the default webhook route shipped with cashier.

Please make sure to only run this on production.

If you need further info please try:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

**Comment by Binozo** [comment]
My solution was to refresh the routes cache by executing `php artisan route:cache`
