### ISSUE TITLE
Call to undefined method Laravel\Cashier\Cashier::stripe()

### ISSUE THREAD

**Issue by metallurgical** [laravel/cashier-stripe#1403]
- Cashier Version: 12.17.1
- Laravel Version: 8.74.0
- PHP Version: 7.4.
- Database Driver & Version:

### Description:
Try to invoke stripe client using below snippet but getting undefined method instead, is there any parts that i missed:

```
use Laravel\Cashier\Cashier;
 
$prices = Cashier::stripe()->prices->all();
```

### Steps To Reproduce:
Include use statement and directly call above statement.

**Comment by driesvints** [comment]
You're using v12 which doesn't have this. Please upgrade to v13.

**Comment by metallurgical** [comment]
i see,, thanks a lot!
