### ISSUE TITLE
Cashier Webhook issue

### ISSUE THREAD

**Issue by pratikshap31** [laravel/cashier-stripe#1406]
- Cashier Version: 13.5.3
- Laravel Version: 8
- PHP Version:7.4.3
- Database Driver & Version:8.0.29-0ubuntu0.20.04.3

Description:
laravel cashier Receive Multiple Webhook for the same event(cancel at end of current period) for same subscription Id 
Using laravel cashier we have created a subscription
we have canceled subscription using cancelAt method.
When we cancel a subscription receive multiple webhook for this event (customer.subscription.update).
In all webhook requests payload got the same subscription id with status 200.
We have asked this query also in stripe support. stripe technician said this issue not from the stripe side this issue came from your side by looking at the 'Source' Stripe/v1 PhpBindings/7.128.0 Laravel Cashier/13.5.3 (https://laravel.com/)
Please guide me in laravel cashier what issue occurred so got multiple webhook.

**Comment by driesvints** [comment]
> Receive Multiple Webhook for the same event

Honestly this isn't a Cashier issue. We don't control how many times a webhook is sent in. Please try a support channel or contact Stripe support again:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
