### ISSUE TITLE
v14 - upgrading webhook doesn't use new stripe api version

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1427]
- Cashier Version: 14.0.0
- Laravel Version: 9.26.1
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 5.7

### Description:

I'm migrating my Laravel app from version 8 to version 9. I've just upgraded Cashier from the latest v13 to exactly 14.0.0. I'm following the exact upgrade guide described in the Cashier documentation and, have updated my Stripe API version to the latest in my Stripe dashboard to `2022-08-01`.

Now, I'm trying to update the webhook, and I already have an existing webhook on the old `2020` api version set up, so after updating the stripe api version I expect running the webook command to disable the old webhook and create a new one with te new api version, it isn't and is still creating it with the old version:

Docs say:

```
php artisan cashier:webhook --disabled --url "http://example.com/stripe/webhook"
```

I then tried specifying my api version 

```
php artisan cashier:webhook --disabled --api-version="2022-08-01" --url "http://example.com/stripe/webhook"
```

But this continues to create a webhook on the old stripe version, not the one one.

**Comment by driesvints** [comment]
> so after updating the stripe api version I expect running the webook command to disable the old webhook and create a new one with te new api version, it isn't and is still creating it with the old version

Heya. So this isn't exactly what happens. When you run the command it'll only create a new webhook. It'll never influence existing webhooks. When I try it, it'll properly create a webhook with the new API version and disable it automatically:

<img width="648" alt="Screenshot 2022-08-26 at 10 10 01" src="https://user-images.githubusercontent.com/594614/186855358-ac750280-e932-426e-94ac-e3f72db2ab08.png">

The guide says:

> This will create a new webhook with the same Stripe API version as Cashier [in your Stripe dashboard](https://dashboard.stripe.com/webhooks). The webhook will be immediately disabled so it doesn't interfere with your existing production application until you are ready to enable it.

Where are you running the command? It's intended to be run on production after deploying the update. If you run it locally with a testing key it'll create the webhook in your test account.

Let me know if anything is still unclear and I'll try to update the guide.

**Comment by sts-ryan-holton** [comment]
@driesvints thanks for this, I've just changed it again, I got confused with this one, yeah, the one it creates is the disabled one which uses the new api version, and I have to disable the current one and enable the disabled new one, I'll close this issue :)
