### ISSUE TITLE
v14 - allowPaymentFailures() error thrown on subscription creation

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1430]
- Cashier Version: 14.0.0
- Laravel Version: 9.26.1
- PHP Version: 8.1.0
- Database Driver & Version: MySQL 5.7

### Description:

I've taken a look at the [new subscription behaviour](https://github.com/laravel/cashier-stripe/blob/master/UPGRADE.md#new-subscription-behavior) and the section implies that I should add `allowPaymentFailures()` to my subscription creation, and in places where I update my subscription.

Previously, in Cashier 13 I was using:

```php
try {
    Auth::user()->newSubscription('default', $plan->stripe_id)
              ->withCoupon($coupon)
              ->create($request->input('token'));
} catch (IncompletePayment $e) {

}
```

And now, I've changed it to:

```php
try {
    Auth::user()->allowPaymentFailures()->newSubscription('default', $plan->stripe_id)
              ->withCoupon($coupon)
              ->create($request->input('token'));
} catch (IncompletePayment $e) {

}
```

When I do this though, an error is thrown saying that the method is undefined?

> Call to undefined method App\Models\User::allowPaymentFailures() {"userId":8,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method App\\Models\\User::allowPaymentFailures() at C:\\Users\\Ryan\\Desktop\\web-projects\\domain-monitor\\domain-monitor-api\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php:71)

I'm not sure this is expected behaviour from Casier 14 if attached to the user?

**Comment by driesvints** [comment]
Ah sorry about that. The method was misplaced in the upgrade guide. Fixed now. Try:

```php
$request->user()->newSubscription(
    'default', 'price_monthly'
)->allowPaymentFailures()->create($request->paymentMethodId);
```

Btw, the section doesn't implies you *need* to add it. Most likely, the upgrade should go smoothly for you without it. Only if you were specifically relying on the `allow_incomplete` behavior you should add it.
