### ISSUE TITLE
Invoice Item period ignored whilst generating invoices

### ISSUE THREAD

**Issue by nicko170** [laravel/cashier-stripe#1431]
- Cashier Version: 14.0.0
- Laravel Version: 9.25.1
- PHP Version: 8.1.9
- Database Driver & Version:

### Description:
When adding an invoice item using the `tabPrice()`, `invoiceFor()` methods, you can pass a `period` to stripe, and it will render the dates on the invoices when downloading from the Stripe dashboard.

Cashier is not rendering these dates, though there is a spot for them.

Ref: https://stripe.com/docs/api/invoiceitems/object#invoiceitem_object-period
```
The period associated with this invoice item. When set to different values, the period will be rendered on the invoice.
```

### Steps To Reproduce:
Create a one off invoice, then download the PDF.
```php
$user->tabPrice('price_service', options: [
    'description' => 'A cool service',
    'period' => [
        'start' => $this->service->created_at->unix(),
        'end' => $this->service->next_bill_at->unix(),
    ],
]);

$user->invoice();
```

PR Incoming, issue is being opened to track.

**Comment by driesvints** [comment]
Thanks. This is more of a feature request so gonna close this as there's an open PR. I'll have a look.
