### ISSUE TITLE
Import Existing Stripe Subscriptions

### ISSUE THREAD

**Issue by myregistration** [laravel/cashier-stripe#1440]
It would be great if we could import existing Stripe subscriptions into our Laravel db with a Cashier function.  Thanks!

**Comment by driesvints** [comment]
Unfortunately this isn't possible as there's no way to know to which users to attach the customer id's.

**Comment by myregistration** [comment]
Why not associate them with the email address?

**Comment by driesvints** [comment]
Because those aren't unique in stripe. You can have multiple customers with the same email address.

**Comment by surtic86** [comment]
oh thats a shame... 

@myregistration how have you don it now? export on stripe and imported it?
