### ISSUE TITLE
Disable automatic tax at runtime

### ISSUE THREAD

**Issue by bjarn** [laravel/cashier-stripe#1441]
Currently, to enable Stripe Tax, you have to enable it in the `boot` of `AppServiceProvider`.

However, if you do not have an address available for a client but do want to start a trial period (with no address or payment method attached to the customer) it is not possible to create a subscription.

Is it possible to make i.e. the `automaticTaxPayload` function to not only check for the global `isAutomaticTaxEnabled()` but also for a parameter when creating the actual subscription so you can make exceptions on this rule?

**Comment by driesvints** [comment]
Can't you use a generic trial for this? https://laravel.com/docs/9.x/billing#without-payment-method-up-front

**Comment by bjarn** [comment]
@driesvints generic trials are a great alternative indeed, will do the job.

Using those instead :) Thanks!
