### ISSUE TITLE
When customer starts a subscription 3D check show 0 amount

### ISSUE THREAD

**Issue by mpapado3** [laravel/cashier-stripe#1451]
- Cashier Version: 14
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version:

### Description:
When customer starts a new subscription, the 3D security check from the bank shows 0€ instead of the subscription amount. 
since this is the confirmation from the setup intent it should present other notification or the correct amount. 
Is there any way to change this?
From stripe they wrote me to use payment intent instead of setup intent.

**Comment by driesvints** [comment]
I'll need way more info about this. Please show the code to reproduce this or create a repo with:

```bash
laravel new bug-report --github="--public"
```

**Comment by mpapado3** [comment]
There is an older discussion about the same issue and it is currently closed without any info about the solution. 
it is the discussion in [This](https://github.com/laravel/cashier-stripe/issues/929)  thread.

**Comment by driesvints** [comment]
I’ll review that issue when I’m back from vacation. Thanks

**Comment by mpapado3** [comment]
Is there any update.
I have checked all stripe documentation and cannot sort out this issue.
