### ISSUE TITLE
Option to keep incomplete subscriptions active

### ISSUE THREAD

**Issue by anthonycreek** [laravel/cashier-stripe#1454]
I've run into an issue where a user could have an existing subscription and then change the credit card to one that requires SCA. When the subscription renews and Stripe billing charges the card, the subscription status will be updated to `incomplete` since they need to complete the SCA. The same could happen when swapping subscriptions as well. 

At that point, the model is no longer subscribed according to Cashier since the [active method](https://github.com/laravel/cashier-stripe/blob/1a86a6ccc141c8321763eb02cbfb24fc58ca3fa0/src/Subscription.php#L227) returns `false`. 

In our case, that means the entire team immediately loses access to the workspace. Ideally we'd have the option to treat this like we do a `past_due` subscription using `Cashier::keepPastDueSubscriptionsActive()`. 

So my suggestion is the addition of `Cashier::keepIncompleteSubscriptionsActive()` so that we can give the user time to complete SCA - especially if it happens when they aren't actively using the app (upon renewal with a new card). If they don't complete SCA then the subscription will cancel in a few days based on the Stripe settings. 

I can create a PR for this if it is of interest and there aren't any gotchas I should be aware of here.

**Comment by driesvints** [comment]
I thought about this one quite a bit but I understand your predicament. Even with the thought that I'd never go down this path myself I can see others doing it. Just be mindful with this because activating it means your customers are basically using your product for free.

See https://github.com/laravel/cashier-stripe/pull/1466

**Comment by anthonycreek** [comment]
Nice, thank you! We have Stripe rules set up to cancel the subscription after 7 days if they don't get the payment made so we'll grab the webhook and cut off access at that point. Appreciate the update here though. Cleans up our code a bit where we were working around it.
