### ISSUE TITLE
cancelNow method still treats user as being subscribed if they subscribed via trial

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1456]
- Cashier Version: 14.2.1
- Laravel Version: 9.35.1
- PHP Version: 8.1.9
- Database Driver & Version: MySQL

### Description:

When calling the `cancelNow` method on a user that subscribed to a trial using `trialUntil`, the subscription, despite being marked as cancelled, still retains the `trial_ends_at` value which is causing the subscription to still be marked as active.

### Steps To Reproduce:

This is how I'm cancelling the subscription:

```php
$user = User::where('id', $redemptionCode->user_id)->first();
$user->subscription('default')->cancelNow();
```

And here's how I'm checking if a user is subscribed, which continues to return **true** even after calling `cancelNow`

```php
**
 * Determine if the user is currently subscribed or not
 *
 * @return bool
 */
public function getIsSubscribedAttribute()
{
    // customer subscribed with payment method
    try {
        return $this->subscribed('default') ? $this->subscribed('default') : false;
    } catch (\Exception $e) {
        return false;
    }
}
```

What am I missing?

Would I need to manually set the `trial_ends_at` on my `User` model to null so that it's truly revoked?

![Capture](https://user-images.githubusercontent.com/25177538/197350578-084580a0-69e2-457a-9fd0-b11997f3a974.PNG)

![Capture](https://user-images.githubusercontent.com/25177538/197350589-f0b2f1d9-a80a-4a30-bc78-e3daf3b69dc8.PNG)

**Comment by driesvints** [comment]
Heya. You can achieve this with the `skipTrial` method:

```php
$subscription->skipTrial()->cancelNow();
```

In the next major version we're going to apply this behavior by default: https://github.com/laravel/cashier-stripe/pull/1465
