### ISSUE TITLE
Subscription paid via bank transfer

### ISSUE THREAD

**Issue by f00bar** [laravel/cashier-stripe#1457]
Hello,

We have some subscription clients that do not have debit cards for their bank accounts so they pay us via direct bank transfer. Obviously the payment doesn't go through Stripe so my question is - is it possible to accommodate this case with Cashier (i.e without going through Stripe for the payment)

Thanks!

**Comment by driesvints** [comment]
Heya. I think it does. Judging from Stripe's guide: https://stripe.com/docs/billing/subscriptions/bank-transfer

It should be as simple as creating the subscription and sending an invoice to the customer by mail which they can then pay with a bank transfer. See https://laravel.com/docs/9.x/billing#collecting-recurring-payments-via-invoice-emails on how to do that.
