### ISSUE TITLE
"Remember payment method for future usage" checkbox doesn't set new payment method to default

### ISSUE THREAD

**Issue by ralph10D** [laravel/cashier-stripe#1469]
- Cashier Version: 13.5
- Laravel Version: 8.12
- PHP Version: 8.0
- Database Driver & Version: mysql 8

### Description:

Hey, not sure if this is a bug or intended but we've had a number of customers confused when confirming a 3DS payment and checking the "Remember payment method for future usage" checkbox as they think Stripe will then use this payment method in the future but it doesn't as it only adds the payment method, but does not set it as the default. This means that the following month they are having to come back to confirm the payment again as it's still using the previous payment method.

Is it possible during the payment confirmation endpoint, that it can set the payment method as default if they check the "remember" checkbox?

### Steps To Reproduce:

- Use a 3DS card that requires confirmation when creating a test subscription. 
- Go to the endpoint that cashier creates for completing an outstanding payment. 
- Check the checkbox saying "Remember payment method for future usage" and submit with new details.
- The new payment method will be added to the customer but is not set to default so will not be used.

Thanks!
Ralph

**Comment by driesvints** [comment]
Hi there, thanks for sharing this. I realise this isn't ideal but the remember functionality really was to only save the payment method to the customer object for future usage. Having to built in a way to make it the default would be a bit of work I'm not willing to pick up right now, sorry.

I just want to note that the hosted Stripe invoice page right now also does not provide a way to save the payment method as the default: https://stripe.com/docs/invoicing/hosted-invoice-page

**Comment by driesvints** [comment]
Not yet sorry. I currently don't have the time to look into that. Would appreciate any PR for this.
