### ISSUE TITLE
Testing trials end scenario with Stripe's Test Clock simulation causes a still trialing subscription.

### ISSUE THREAD

**Issue by dpetrovaliev** [laravel/cashier-stripe#1470]
- Cashier Version: 14.2.1
- Laravel Version: 9.36.3
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.27

### Description:

I'm testing the trial ends scenario with Stripe's Test Clock feature and found out that moving the time in the future to cause a Trial End is updating the user and subscription to the new billing cycle successfully but it isn't updating the `trial_ends_at` column on `subscriptions` table which could be an issue.

Is there a scenario when the subscription is renewed for the new billing cycle after the trial period and the trial period is still active?
Shouldn't the webhook update the `trial_ends_at` column when the user renews his plan?

### Steps To Reproduce:

1. Create a test clock in Stripe. (https://stripe.com/docs/billing/testing/test-clocks)
2. Create a new user from the dashboard.
3. Associate Stripe's user with a new user in your DB by copying Stripe's user ID and pasting it into your local DB user's `stripe_id` column.
4. Subscribe the user through Stripe's dashboard or your local implementation of subscribing for a recurring subscription with a trial period.
5. Advance the time by Stripe's dashboard Test clock(https://stripe.com/docs/billing/testing/test-clocks)

**Comment by driesvints** [comment]
I'm not sure tbh. I've never tried trialing subscriptions with the clock feature and Cashier Stripe. I'm not even sure if the clock feature works well with cashier stripe all together. Right now we don't plan on working on support for that feature but if there's something you spot that can be done to make that integrate better then feel free to send in a PR 👍
