### ISSUE TITLE
Cannot install cashier

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [laravel/cashier-stripe#1474]
- Cashier Version: #.#.#
- Laravel Version: 9.14.1
- PHP Version: 8.1.2
- Database Driver & Version: mysql 8.0.31

### Description:
Got this trying to install cashier:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/cashier ^14.3 -> satisfiable by laravel/cashier[v14.3.0, v14.3.1, 14.x-dev].
    - laravel/cashier[v14.3.0, ..., 14.x-dev] require illuminate/console ^9.21 -> found illuminate/console[v9.21.0, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel/cashier:*" to figure out if any version is installable, or "composer require laravel/cashier:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Steps To Reproduce:
run: composer require laravel/cashier

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
