### ISSUE TITLE
Eager load subscription owner

### ISSUE THREAD

**Issue by jradtilbrook** [laravel/cashier-stripe#1477]
- Cashier Version: 13.13
- Laravel Version: 9.40.1
- PHP Version: 8.1
- Database Driver & Version: pgsql

### Description:
I'm running into a `Illuminate\Database\LazyLoadingViolationException` when trying to use `Illuminate\Database\Eloquent\Model::shouldBeStrict()` in my project and asking to see if this package could be updated to eager load the `owner` relationship.
It's occurring on https://github.com/laravel/cashier-stripe/blob/cd2533517a943c7b964184fcb1b918bc753934ca/src/Subscription.php#L1211 which is executed after a subscription has been created (and possibly other paths I haven't hit yet).

I'm also using Laravel spark v2.6.2 which is locked to version 13 of this package. But is also looks like this would be present in the v14 line.

I found issue #1172 but thought since it is closed and quite old that perhaps a new issue would be best.

I know there are ways around this problem like what is suggested in #1172 but I'd prefer to not do them of course, if they could be changed here instead.  
I also note that there is [mention](https://github.com/laravel/cashier-stripe/issues/1172#issuecomment-849793831) of not being able to add eager loading to the Subscription model. But I'm not sure the reasoning behind that and I can see that it does in fact eager load the `items` relationship. So I'm wondering if it could be updated to eager load the `owner` as well?
I'm not sure if that would be a breaking change but it could possibly do lazy eager loading instead which might be quite messy but at least its hidden in this library code.

![2022-11-24_20:37:02](https://user-images.githubusercontent.com/6128798/203786319-01cebb9f-4995-4f5a-aa38-374c079bb7a7.png)

**Comment by driesvints** [comment]
Unfortunately there's nothing we can do right now, sorry. Cashier is too brittle and we've had lots of issues in the past when trying to modify this behavior. Since this package involves things like payments we're not reluctant to make any changes here, sorry.

**Comment by jradtilbrook** [comment]
No worries, thanks for the explanation! It was worth asking for just in case but the reasoning makes sense.

---

For any future travellers, instead of going this route: https://github.com/laravel/cashier-stripe/issues/1172#issuecomment-955205422
I decided to extend the Subscription class to override the lazy loading and configure cashier to use that instead.

```php
<?php

namespace App\Models;

use Laravel\Cashier\Subscription as CashierSubscription;

class Subscription extends CashierSubscription
{
    /**
     * The relations to eager load on every query.
     * Override the parent eager loading to include `owner`.
     *
     * @var array
     */
    protected $with = ['items', 'owner'];
}

```

And in AppServiceProvider.php
```php
Laravel\Cashier\Cashier::useSubscriptionModel(CustomSubscriptionModel::class);
```
