### ISSUE TITLE
Setting CASHIER_LOGGER=slack causes ServiceProviders to be booted multiples times in PHPUnit tests

### ISSUE THREAD

**Issue by Gnative** [laravel/cashier-stripe#1480]
- Cashier Version: 14.5.0
- Laravel Version: 9.43.0
- PHP Version: 8.1.10
- Database Driver & Version: nil

### Description:
When using `CASHIER_LOGGER=slack`, ServiceProviders seem to be booted multiple times when running PHPUnit tests.

**This causes many issues such as registering multiple event listeners etc.**  

I've spent quite a few hours trying to understand why as it is breaking my tests but I wasn't able to derive why. Sorry. I got so far as to think loading the SlackProvider is having an effect on the [array_walk](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Application.php#L913) function in [/Illuminate/Foundation/Application.php](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Foundation/Application.php#L913)

### Steps To Reproduce:
1. Clean install of Laravel `composer create-project laravel/laravel example-app`
2. Install Cashier `composer require laravel/cashier`
3. Add `CASHIER_LOGGER=slack` to the .env file
4. Run `vendor/bin/phpunit --filter test_the_application_returns_a_successful_response`

https://github.com/Gnative/laravel-cashier 

Please see commits for these changes above

**Comment by driesvints** [comment]
In unit tests, it's wise to not use the slack logger and to just disable the logger with `CASHIER_LOGGER=null`.

**Comment by Gnative** [comment]
O.M.G why didn't think of that, humbled. 
Thanks @driesvints
