### ISSUE TITLE
CORS Missing Allow Origin / CORS header ‘Access-Control-Allow-Origin’ missing

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/cashier-stripe#1481]
- Cashier Version: 14.5.0
- Laravel Version: 9.43.0
- PHP Version: 8.1.7
- Database Driver & Version: MySQL 5.7.37

### Description:
i have successfuly integrated Stripe by following those 2 steps :
https://laravel.com/docs/9.x/billing#payment-methods-for-single-charges (<<< my checkout page)
https://laravel.com/docs/9.x/billing#simple-charge
And got the payment on the Stripe side.

Nonetheless, i sometime get javascript errors on my checkout page:

Error  [XHR]	POST	https://r.stripe.com/0		CORS Missing Allow Origin

		Headers:
			POST
				Status 			499 No Reason Phrase
				Version			HTTP/2
				Transferred		1,34 Ko (taille 0 o)
				Referrer Policy		strict-origin-when-cross-origin

			REQUEST
				POST /0 HTTP/2
				Host: r.stripe.com
				User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
				Accept: application/json
				Accept-Language: en-US,en;q=0.5
				Accept-Encoding: gzip, deflate, br
				Referer: https://js.stripe.com/
				Content-Type: application/x-www-form-urlencoded
				Content-Length: 600
				Origin: https://js.stripe.com
				DNT: 1
				Connection: keep-alive
				Sec-Fetch-Dest: empty
				Sec-Fetch-Mode: cors
				Sec-Fetch-Site: same-site

			RESPONSE
				HTTP/2 499 No Reason Phrase
				content-type: text/html; charset=utf-8
				expires: Mon, 04 Dec 1999 21:29:02 GMT
				cache-control: no-store, no-cache, must-revalidate, max-age=0
				pragma: no-cache
				content-length: 7636
				x-xss-protection: 0
				X-Firefox-Spdy: h2

and also this error :

	Cross-Origin Request Blocked:
	The Same Origin Policy disallows reading the remote resource at https://r.stripe.com/0
	(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
	Status code: 499.

i wonder if it come from Cashier or something deeper in Laravel ?
Maybe there's a step missing in the documentation > configuration ?

EDIT: I have contacted the support of Stripe, and they told me that everything work well on their side and that i should contact the Laravel side.

### Steps To Reproduce:
🤷‍♂️ if only i knew... it's happen sometime only... 😕

**Comment by Rhydium** [comment]
Having the same CORS issue over here, I have this 100% of the times.
![image](https://user-images.githubusercontent.com/25478879/207167323-fb30e074-8846-40e2-90b0-5795a8c5543d.png)

**Comment by driesvints** [comment]
I have no idea sorry. Maybe there's some things you need to change in your CORS settings? https://github.com/laravel/laravel/blob/9.x/config/cors.php

If your app is working properly then I wouldn't worry too much about it.

**Comment by Ronan-Lenor** [comment]
i tried this already without success.
i will investigate futhermore. and post here if i find something.

@Rhydium if you find something on your side, please post here 😅

**Comment by Rhydium** [comment]
I don't have any antivirus installed, but this only seems to be happening when using `route()` and not when manually entering the URL.
