### ISSUE TITLE
WebhookController > missingMethod() : should retunr a 501 "Not Implemented" HTTP status code

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/cashier-stripe#1482]
Hello,

i have notice that the ` missingMethod()` from `vendor\laravel\cashier\src\Http\Controllers\WebhookController.php` return an empty `new Response`.
Stripe consider it as a 200 successful request. Nonetheless, if the method is missing, that would be better to return either a `501 "Not Implemented"` OR a `405 "Method Not Allowed"` status code to be able to track such problem on Stripe's logs page.

Suggestion:
Replace `return new Response;` by `abort(405 , 'Method Not Allowed');`

**Comment by driesvints** [comment]
The current response is the correct one as not all events need to be implemented. We just tell Stripe all is okay because this app doesn't handle the type of event that's sent.

**Comment by Ronan-Lenor** [comment]
> is okay because this app doesn't handle...
this is contradictory. 🤷‍♂️ the other status codes was made for a such situation 🤔

it's just like a client requesting a page that doesn't exist (404). Technically the server handle it... to say it doesn't handle it 😅
it's good practice to get a clear feedback from the server on certain case.
