### ISSUE TITLE
Cancelled Subscription issue if cancelled while on Trial

### ISSUE THREAD

**Issue by NeboCode** [laravel/cashier-stripe#1483]
- Cashier Version: 14.4 (Stripe API version 2022-11-15)
- Laravel Version: 9.19
- PHP Version: 8.1.12
- Database Driver & Version: MySQL

### Description:

There appears to be an issue with the way Cashier handles trial subscriptions which get cancelled immediately.

I created a Stripe subscription programmatically with Cashier, then gave the user a 30 day trial upon which via Stripe website I used the `Cancel Immediately` option on the subscription.

Subscription is therefore immediately cancelled and no longer active nor accessible via Cashier interactions with Stripe API yet the `$user->subscribed('default')` call still returns `true`.

I am aware that the `subscribed` method will return `true` as long as user is on grace period however once a subscription is hard cancelled (immediate cancel) and no longer resumeable, this method returns `false` which is the correct behavior.

Docs explain the `subscribed` method as: 
![image](https://user-images.githubusercontent.com/17943735/208428045-e6697854-e408-435b-a4ba-0e6bda4e2c28.png)
However, the method itself will return `true` even if the subscription is no longer active as long as user is on trial which seems like a bug and unintended behavior.

This is caused by the `trial_ends_at` column in the database on the billable model.

**This behavior is very problematic, since if you are relying on the `subscribed` method to check if your user has an active subscription within your Laravel app and allowing the users to cancel or resume the subscription, the `cancel()` and `cancelNow()` calls will return an ERROR 404 since an active subscription can't be found but the user will remain `subscribed` until the already hard cancelled and "deleted" subscription's trial runs out. **

After reproducing the bug, it is also impossible to make a call to `endTrial()` method as well. I get the error message: `You cannot update a subscription that is canceled or incomplete_expired`.
I've also attempted to fix it on Stripe website directly I could not find a way to get rid of the trial itself, since the subscription is Cancelled and no longer resumeable.

### Steps To Reproduce:

1. Create a new user subscription:

3. Add trial to subscription programmatically :
```php
$user->subscription('default')->extendTrial(
    now()->addDays(30)
);
```

4.  Cancel the subscription on Stripe to trigger a webhook call or use the `cancelNow()` method. I've tested both and it is reproduceable.

**Comment by driesvints** [comment]
This was fixed for the next major version. Unfortunately this was a breaking change so we had to target the next major version. Right now we have no planned release date for it. You can overwrite the webhook for now if you want with the code from https://github.com/laravel/cashier-stripe/pull/1465. Thanks
