### ISSUE TITLE
Unable to call charge() method on customer simple charge.

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1484]
- Cashier Version: 14.5.0
- Laravel Version: 9.45.0
- PHP Version: 8.1.0
- Database Driver & Version: SQL

### Description:

I'm building an application where customers of my system can purchase "one-time" top-up credits. I figure a [simple charge](https://laravel.com/docs/9.x/billing#simple-charge) is best served for this.. To do this I need to create a customer if they don't already exist, and then charge their card.

I'm pulling through the `pm_XXX` as a `token` variable and passing this as a second argument, but when I call the `charge` method I get the following error:

> Call to undefined method Stripe\Customer::charge()

This is my current set up:

```php
$productPrice = Cashier::stripe()->prices->retrieve($productOption->stripe_id);

$user = Auth::user()->createOrGetStripeCustomer();
$user->charge(
    $productPrice->unit_amount, $request->input('token')
);
```

I can confirm that the customer was created in my Stripe account, but it can't be charged?

**Comment by driesvints** [comment]
You're performing the `charge` method on the Stripe customer, not the Eloquent model:

```php
$productPrice = Cashier::stripe()->prices->retrieve($productOption->stripe_id);

$user = Auth::user();
$user->createOrGetStripeCustomer();
$user->charge(
    $productPrice->unit_amount, $request->input('token')
);
```
