### ISSUE TITLE
invoiceFor unit_amount second argument is charging significantly higher

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1485]
- Cashier Version: 14.5.0
- Laravel Version: 9.45.0
- PHP Version: 8.1.0
- Database Driver & Version: SQL

### Description:

When setting additional options on the `invoiceFor` method, the amount charged is incorrect _(significantly higher)_. I need to be able to send some custom key/value pairs as the array key `metadata` as the third argument to handle my webook event.

As such, I'm specifying the second argument as the smallest value possible.

```php
$productPrice = Cashier::stripe()->prices->retrieve($productOption->stripe_id);

$user->invoicePrice(
    $productOption->stripe_id, $productPrice->unit_amount, [
        'metadata' => [
            'created_at' => Carbon::now(),
            'user_id' => $user->id,
            'api_key_uuid' => $apiKey->uuid,
            'quantity' => $productOption->quantity
        ]
    ]
);
```

In my example, my price should be £4.99, so 499 is passed as a second argument. But in my invoice I'm charged £2,490.01? What am I missing?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
