### ISSUE TITLE
Create subscription with both metered and regular prices

### ISSUE THREAD

**Issue by talelmishali** [laravel/cashier-stripe#1488]
- Cashier Version: 14.6.0
- Laravel Version: 9.46.0
- PHP Version: 8.2.0
- Database Driver & Version: MySQL

### Description:
When trying to create a new subscription with both metered and regular prices, Stripe will throw ``invalid_request_error - quantity``. It appears that when creating a new subscription and passing a price with no quantity, the builder will automatically add ``1`` as the default quantity, which results in an error. 

When calling ``meteredPrice()``, the quantity parameter is passing ``null``, which pushes the price correctly into ``items``. 

### Steps To Reproduce:
1. Setting up metered and regular prices on Stripe.
2. Creating a customer
3. Creating a new subscription with both metered and regular prices.

```php
$this->user
            ->newSubscription('default', $prices)
            ->trialDays($trialDays)
            ->create($paymentMethod);
```

#### What I push as prices
```php
array:2 [ 
  0 => "price_1MO063L7Q3I087mfWiVUvPnp",
  1 => array:2 [
    "price" => "price_1MO24mL7Q3I087mfNsfFjJ4H",
    "quantity" => 1
  ]
]
```
#### ⚠️ What the builder push to Stripe
```php
  #items: array:2 [
    "price_1MO063L7Q3I087mfWiVUvPnp" => array:2 [
      "price" => "price_1MO063L7Q3I087mfWiVUvPnp",
      "quantity" => 1
    ],
    "price_1MO24mL7Q3I087mfNsfFjJ4H" => array:2 [
      "price" => "price_1MO24mL7Q3I087mfNsfFjJ4H",
      "quantity" => 1
    ]
  ]
```

#### ✅ What the builder push when using ``meteredPrice()``
```php
  #items: array:2 [
    "price_1MO24mL7Q3I087mfNsfFjJ4H" => array:2 [
      "price" => "price_1MO24mL7Q3I087mfNsfFjJ4H",
      "quantity" => 1
    ],
    "price_1MO063L7Q3I087mfWiVUvPnp" => array:1 [
      "price" => "price_1MO063L7Q3I087mfWiVUvPnp"    -----------------> No quantatity on meterd price.
    ]
  ]
```

#### ⚠️ Stripe log for an incorrect request 
```bash
invalid_request_error - quantity
You cannot set the quantity for metered plans.

  "items": {
    "0": {
      "quantity": "1",
      "price": "price_1MO063L7Q3I087mfWiVUvPnp"
    },
    "1": {
      "quantity": "1",
      "price": "price_1MO24mL7Q3I087mfNsfFjJ4H"
    }
  },
```

#### ✅ Stripe log for a correct request
```bash
  "items": {
    "0": {
      "quantity": "1",
      "price": "price_1MO24mL7Q3I087mfNsfFjJ4H"
    },
    "1": {
      "price": "price_1MO063L7Q3I087mfWiVUvPnp"
    }
  },
```

### Tests

It looks like the test's assertions are incorrect. The test ``test_it_can_be_instantiated_with_both_normal_and_metered_prices`` 
Pass that to the builder:
https://github.com/laravel/cashier-stripe/blob/35bf8a5f3ecf2b785ec9c3faa61e9f96cf7f22b5/tests/Unit/SubscriptionBuilderTest.php#L14

And falsely asserting that as correct:
https://github.com/laravel/cashier-stripe/blob/35bf8a5f3ecf2b785ec9c3faa61e9f96cf7f22b5/tests/Unit/SubscriptionBuilderTest.php#L21

### The location of the issue
The builder checks if the ``quantity`` is not null, which in the case of passing metered and regular prices, evaluates as ``true``, which pushes default quantity ``1`` to the price.
https://github.com/laravel/cashier-stripe/blob/35bf8a5f3ecf2b785ec9c3faa61e9f96cf7f22b5/src/SubscriptionBuilder.php#L106
https://github.com/laravel/cashier-stripe/blob/35bf8a5f3ecf2b785ec9c3faa61e9f96cf7f22b5/src/SubscriptionBuilder.php#L107

Sorry ahead of time if anything is not clear. It's getting late, probably I'll PR tomorrow

**Comment by driesvints** [comment]
I tried this out in https://github.com/laravel/cashier-stripe/pull/1489 but unfortunately it is not possible to know up front which price is a recurring one and which one is a metered one.

Right now, people are using the builder like this:

```php
$this->user->newSubscription('default', 'price_xxx')->create($paymentMethod);
```

It's impossible to know if `price_xxx` is metered (quantity can be omitted) or recurring (quantity is required by the Stripe API). Therefor, you are required to use `meteredPrice` to add metered prices.

**Comment by talelmishali** [comment]
> I tried this out in https://github.com/laravel/cashier-stripe/pull/1489 but unfortunately it is not possible to know up front which price is a recurring one and which one is a metered one.
> 
> 
> 
> Right now, people are using the builder like this:
> 
> 
> 
> ```php
> 
> $this->user->newSubscription('default', 'price_xxx')->create($paymentMethod);
> 
> ```
> 
> 
> 
> It's impossible to know if `price_xxx` is metered (quantity can be omitted) or recurring (quantity is required by the Stripe API). Therefor, you are required to use `meteredPrice` to add metered prices.

Thanks for looking into it. Yeah, I realized that without a significant change to the API, there's no easy workaround to know which is metered a price without asking for some sort of a flag on the prices array. I think it's worth offering a method to instantiate a new subscription with only metered price, and chain additional prices on it. As well as correcting the test to indicate the real intention of the subscription builder. I will PR it, see how you like it. Again, thanks 🤙🏻.

**Comment by driesvints** [comment]
The current test actually reflects the desired behavior because right now the behavior is simply to expect that only regular recurring prices are added to the subscription builder while metered prices need to be added with `->meteredPrice`. To be honest, this behavior has long existed in Cashier and using `->meteredPrice` is not a big workaround. You can create a foreach on your array if you want.

**Comment by driesvints** [comment]
Ah yeah, the test name should be changed. I'll take care of that. 

I just don't feel a new `newMeteredSubscription` is wanted here tbh. Instead I'd more opt to remove the second argument for `newSubscription` so you're forced to use the `->price` and `meteredPrice` methods. But tbh I'd just leave it like this because besides this issue we've never had reports about this being difficult to understand.

**Comment by talelmishali** [comment]
Playing around with ``newMeteredSubscription`` felt awkward. I agree it is not the best, and a subscription is a subscription, so there is no need to be specific with ``newMeteredSubscription``. However, I did PR the ``prices()``; sorry for dragging it, lol #1490.
