### ISSUE TITLE
Support one time payments with storing of payment method

### ISSUE THREAD

**Issue by bloomlive** [laravel/cashier-stripe#1492]
Hey!

At the time of writing the documentation Stripe didn't support one-time payments via usage of a stored payment method. It's not the case any more. In our case, a customer is would be charged post-fact for services provided, however, we want the user to provide a payment method beforehand that we then can validate.

From the docs:
> Due to Stripe limitations, you may not use the stored default payment method of a customer for single charges.

Mostly we can estimate the cost of service, let's say $10, however, in some cases, we then reduce the amount by some percentage. This is now supported via Manual payment capture. This seems to be unsupported (sorry, if I missed that).

It seems, that you can now configure a payment intent for future use via Stripe as well.[ See Stripe documentation for developers here.](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-setup_future_usage)

Is this something Cashier could support in the future and be of any interest to the core team to code, or should I be looking to PR this, if I chew through this on my own?

**Comment by driesvints** [comment]
Heya. Thanks for your report. It seems to me the only thing needed is to remove that line from the docs? Not sure what changes are needed to Cashier?

**Comment by bloomlive** [comment]
It seems that pay() would accomplish this, yes. For the other case, adding capturing payment is required, which would require to receiving and storage of PayementIntent for future use.

**Comment by driesvints** [comment]
Could you please sketch the API of the methods you want to add?

**Comment by bloomlive** [comment]
Sure. I did some quick brainstorming in a branch and came up with something like this:

Something along the lines of
`$user->holdPayment(int $amount, array $params): PaymentIntentModel`
to create a payment intent and store it in database.

To cancel payment intent:
`$user->cancelPayment(PaymentIntentModel $paymentIntent): PaymentIntentModel;`

To capture payment fully or partially: 
`$user->capturePayment(PaymentIntentModel $paymentIntent, int $amount, array $params = []): PaymentIntentModel;`

To query user's payment intents:
`$user->paymentIntents()` as relationship.

**Comment by driesvints** [comment]
Thanks. Feel free to send in a PR which we can look at 👍
