### ISSUE TITLE
Payment method columns empty/null when using checkout

### ISSUE THREAD

**Issue by darkylmnx** [laravel/cashier-stripe#1493]
- Cashier Version: 14.7.0
- Laravel Version: 9.47.0
- PHP Version: 8.1.0
- Database Driver & Version: MariaDB 10.3.32

### Description:

When creating a subscription with Stripe checkout through Cashier like this:
```php
$request->user()
    ->currentTeam
    ->newSubscription('default', 'price_monthly')
    ->checkout([
        'success_url' => route('your-success-route'),
        'cancel_url' => route('your-cancel-route'),
    ]);
```

After the payment is done and webhook are called, the columns `pm_type`, `pm_last_found` are still null
on the billable model's table (in our case it's not the users table but an accounts table).

`currentTeam` represents my billable model.

### Steps To Reproduce:

1. create an entry in a billable model (user or whatever)
2. create a checkout url with that billable like the code above
3. go to the url, pay with the test card
4. check the database when the webhook are done

**Comment by driesvints** [comment]
Have you set up and are you running webhooks? https://laravel.com/docs/9.x/billing#handling-stripe-webhooks

**Comment by darkylmnx** [comment]
Are you refering to a specific webhook event?
If not, yes the webhooks have been set like the docs says.
Everything works, subscriptions and customers are created, but only the payment method columns are null.

**Comment by driesvints** [comment]
I think I know what's going on. This is expected because when you use a payment method through Stripe Checkout it does not get set as your default payment method, it just gets added to your customer. That's why these columns aren't updated. I am not immediately sure if you can control if a payment method used in Stripe Checkout can become your default payment method. You might need to check that with Stripe.

**Comment by darkylmnx** [comment]
@driesvints is there a way to get the payment method list and just set the first one as default if there's no default payment method?

I think it would be a rather interesting feature of cashier to has an option to set it.

**Comment by driesvints** [comment]
You can listen to the `WebhookHandled` event and check for the `customer.updated` event from Stripe to set a default payment method from the `->paymentMethods()` list if you want that behavior: https://laravel.com/docs/9.x/billing#handling-stripe-webhooks
