### ISSUE TITLE
Unknown column 'subscriptions.user_userId' when creating a subscription 

### ISSUE THREAD

**Issue by EmilChigu** [laravel/cashier-stripe#1501]
Hi, I have been struggling with this issue until I noticed that cashier is appending the primary key name of my user's table to user_* of the subscriptions table. So instead of looking for user_id in the subscriptions table, its is looking for user_userId (primary key of users table). Is there a way i can make it reference the user_id in the subscriptions table instead instead of appending the user tables primary key name?

**Comment by driesvints** [comment]
Please resubmit this with a filled out issue template.
