### ISSUE TITLE
 Unknown column 'subscriptions.user_userId' when creating a subscription

### ISSUE THREAD

**Issue by EmilChigu** [laravel/cashier-stripe#1502]
- Cashier Version: 13.16.0
- Laravel Version: 8.83.27
- PHP Version: 8.1.14
- Database Driver & Version: mySQL version 8.0.30

### Description:
Hi, I have been struggling with this issue until I noticed that cashier is appending the primary key name of my user's table to user_* of the subscriptions table. So instead of looking for user_id in the subscriptions table, its is looking for user_userId (primary key of users table). Is there a way i can make it reference the user_id in the subscriptions table instead instead of appending the user tables primary key name?

### Steps To Reproduce:
Run migrations as normal and in your custom user model, specify a primary key for the user that is not 'id' in my case, the user primary key is 'userId'. then try to create a subscription.

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this.
