### ISSUE TITLE
The Charge Method doesn't return Stripe/Collection

### ISSUE THREAD

**Issue by imran300** [laravel/cashier-stripe#1510]
- Cashier Version: 14.5
- Laravel Version: 9.19
- PHP Version: 8.2
- Database Driver & Version:

### Description:
Hi, I was using laravel Cashier version 13.8 and the method `$charge = $user->charge((int)$transaction_amount, $paymentMethod->id);` was returning  Stripe/Collection that contains some data about stripe charges.
Image is as follow.

![1](https://user-images.githubusercontent.com/7050400/223822781-3d83cdbf-c178-4f0c-a053-9da0acbb331c.PNG)
 

but the latest version of laravel cashier 14.5 doesn't return that. 
Is there any other way. I couldn't find in documentations.

**Comment by chriischambers** [comment]
I've just been looking at this exact issue.  This is a breaking change made within the `stripe-php` PHP package - see here - https://stripe.com/docs/upgrades#2022-11-15

You now need to do an additional API call to get the charge object.  The charge id is now stored in `latest_charge` on your  payment intent.

I did this with the following line (in my case this is in a trait which uses `Billable` trait from cashier).
```
self::stripe()->charges->retrieve($paymentIntent->latest_charge);
```

In my case I needed to get the Stripe fee.  If you need this too you will then need to do a further API call using the `balance_transaction` returned in your Charge object using the following - 

```
self::stripe()->balanceTransactions->retrieve($transactionId)
```

I hope this helps.

**Comment by driesvints** [comment]
Thanks @chriischambers.

@imran300 please see the above.
