### ISSUE TITLE
Duplication in Webhook Handling

### ISSUE THREAD

**Issue by AngadSethi** [laravel/cashier-stripe#1512]
- Cashier Version: 14.9.0
- Laravel Version: 10.1.1
- PHP Version: 8.1
- Database Driver & Version:

### Description:

I've created a `StripeEventListener` as described [here ](https://laravel.com/docs/10.x/billing#defining-webhook-event-handlers)to handle the `checkout.session.completed` event. The problem I'm facing is that whenever Stripe dispatches this event, the webhook is **hit once**, but the handling method is **called twice**.

I've managed to locate the cause of this duplication. Because I've enabled auto-discovery of listeners **and** added the listener to `$listen`, the handling method is called twice. **I feel like this should be mentioned in the documentation, as a disclaimer, because it could trip up a lot of developers, especially if the implementation is not idempotent**.

It's my first time filing an issue, so please let me know if anything's missing in the description and I'll add it. Thanks!

**Comment by driesvints** [comment]
Hi there, I don't feel like this is a cashier issue but rather something with your own app. If you both enable auto discovery and register the listener explicitly then yes that event will be handled twice. If that's not clear in the docs then we'd appreciate a PR, thanks.

**Comment by AngadSethi** [comment]
Will do @driesvints. Thanks!
