### ISSUE TITLE
Unable to access user class

### ISSUE THREAD

**Issue by mattrosenblatt** [laravel/cashier-stripe#1514]
- Cashier Version: v14.9.0
- Laravel Version: 10.4.1
- PHP Version: 8.2.4
- Database Driver & Version: 

### Description:
Stripe webhooks are failing as SOME webhooks are unable to access \App\Providers\User

Should this not be calling \App\Models\User?

I have not modified these files in any way, and all similar issues were for much older versions of Laravel that no longer apply.

### Steps To Reproduce:
Whenever Stripe sends webhook actions, it will throw the below error:

`[2023-03-28 08:04:51] production.ERROR: Class "App\Providers\User" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\User\" not found at /var/www/html/is-portal-main/vendor/laravel/cashier/src/Cashier.php:110)`

This doesn't happen on all webhook commands. For example, Invoice.* webhooks work. customer.* webhooks do not. 

`[2023-03-28 08:16:38] production.ERROR: Class "App\Providers\User" not found {"exception":"[object] (Error(code: 0): Class \"App\\Providers\\User\" not found at /var/www/html/is-portal-main/vendor/laravel/cashier/src/Cashier.php:110)
[stacktrace]
#0 /var/www/html/is-portal-main/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php(296): Laravel\\Cashier\\Cashier::findBillable()
#1 /var/www/html/is-portal-main/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php(68): Laravel\\Cashier\\Http\\Controllers\\WebhookController->getUserByStripeId()
#2 /var/www/html/is-portal-main/vendor/laravel/cashier/src/Http/Controllers/WebhookController.php(50): Laravel\\Cashier\\Http\\Controllers\\WebhookController->handleCustomerSubscriptionCreated()
#3 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Cashier\\Http\\Controllers\\WebhookController->handleWebhook()
#4 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#5 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#8 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /var/www/html/is-portal-main/vendor/laravel/cashier/src/Http/Middleware/VerifyWebhookSignature.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Cashier\\Http\\Middleware\\VerifyWebhookSignature->handle()
#11 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#13 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#14 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#15 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#16 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#17 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#18 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#20 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#21 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#23 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#24 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#26 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#28 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#30 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#32 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#34 /var/www/html/is-portal-main/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#35 /var/www/html/is-portal-main/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#36 {main}
"}`

**Comment by driesvints** [comment]
> `\App\Providers\User`

There is no such reference in Cashier. Most likely, this class was wrongly set using the `useCustomerModel` method.

**Comment by mattrosenblatt** [comment]
Hello,

Do you know where I should begin looking? This was a completely brand new installation of Cashier, configured following the directions within the Laravel documentation. I never once set "useCustomerModel".

considering the entire installation is still stock, it leads me to believe there might be a bug somewhere, or the documentation is missing information.
