### ISSUE TITLE
Unable to confirm Payment when using SEPA direct debit

### ISSUE THREAD

**Issue by thijskok** [laravel/cashier-stripe#1515]
- Cashier Version: 14.9.0
- Laravel Version: 10.4.1
- PHP Version: 8.1.17
- Database Driver & Version: MySQL 8.0.32

### Description:

I've set up a subscription using the SEPA direct debit payment method. When I try to swap (using swapAndInvoice) to another subscription, a payment failure is triggered - it needs additional confirmation. The failure is correctly handled by the `HandlesPaymentFailures` trait, but fails to handle the confirm payment action properly. You'll receive an `InvalidRequestException` saying:

```
When confirming a PaymentIntent with a `sepa_debit` PaymentMethod and `setup_future_usage`, `mandate_data` is required.
```

The exception is related to this line:

https://github.com/laravel/cashier-stripe/blob/f0051b595772d791663f521f3d4378e8cb2597f7/src/Concerns/HandlesPaymentFailures.php#L40

It appears the `mandate_data` field is required, but not submitted. This is also mentioned in https://github.com/stripe/stripe-php/issues/1269#issuecomment-1106522647.

I'd love to submit a PR adding the required data, but I fear I mess up other payment confirmations that might reject the mandata stuff. Any thoughts on solving this?

### Steps To Reproduce:

1. Create any subscription; use the "SEPA direct debit method".
2. Swap the subscription for another subscription using the `swapAndInvoice` method.
3. A payment failure will occur that `HandlesPaymentFailures` is unable to handle.

**Comment by driesvints** [comment]
@thijskok thank you. I sent in a PR which should hopefully help you out. Can you try it? https://github.com/laravel/cashier-stripe/pull/1516

**Comment by verybigelephants** [comment]
Exactly the same thing happened ot me now. i am running `"laravel/cashier": "^14.13",`, but from the look on this pull request it looks like it has been merged :/

**Comment by driesvints** [comment]
@verybigelephants did you actually use the `withPaymentConfirmOptions` method from that PR?

**Comment by verybigelephants** [comment]
@driesvints ohh my bad, i see now, the `withPaymentConfirmationOptions` allows us to pass additional data that are missing so tht the swapAndInvoice wouldn't throw the error with sepa cards.

However, i don't seem to understand where i get this mandate_data. I have read that stripe handles it automatically and i shouldn't be interacting with it. Should i just manually do somthing like this always before doing swapAndInvoice?

```
$paymentMethod = \Stripe\PaymentMethod::retrieve( $subscription->default_payment_method );
if ($paymentMethod->type == 'sepa_debit') {
    $mandateId = $paymentMethod->sepa_debit->mandate;
    $mandate = \Stripe\Mandate::retrieve($mandateId);
    $subscription->withPaymentConfirmOptions(['mandate_data' => $mandate])->swapAndInvoice('...some price...');
}else{
    $subscription->swapAndInvoice('...some price...');
}
```

But then, what if the mandate is not valid anymore? How would i receive another mandate from the user?

Can't i just redirect user to stripe panel with the intended plan+invoice upgrade, like when we can do with new subscriptions like `$user->newSubscription(name, price_id)->checkout([ 'success_url'=> ..., 'cancel_url'=>... ])`. I don't mind not invoicing the user in the background, and actually prefer user to re-verify the payment; as swapAndInvoice instantly invoices them and i think user should explicitly confirm it anwyays

Or do i understand this in a wrong way?

**Comment by driesvints** [comment]
@verybigelephants the different data that can be set here can be found https://docs.stripe.com/api/payment_intents/confirm#confirm_payment_intent-mandate_data (there's a link to it in the cashier docs). You'll have to consult the Stripe docs to know exactly how this works as I don't know it out of the top of my head, sorry.

**Comment by verybigelephants** [comment]
@driesvints  no matter what testing card i try from the docs, i never seem to be able to get this error in dev environment. What did you use to debug this?

**Comment by driesvints** [comment]
Honestly I don't know anymore. It's been too long ago.
