### ISSUE TITLE
Feature: optionally update trial_ends_at on User model when extending trials

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1519]
Hi, I'm using trials in my platform and need a way to update the `trial_ends_at` column when extending a trial for a user's default subscription. When referring to the [docs](https://laravel.com/docs/10.x/billing#extending-trials), the `extendTrial` method only ever appears to actually update the subscription's trial and never the `trial_ends_at` column for the user itself.

Would it be possible to optionally pass a boolean value to the `extendTrial` method that when set to **true** would also update the user's trial column?

**Comment by driesvints** [comment]
Heya, `extendTrial` is indeed only meant for the subscription. If you want to update the `trial_ends_at` method on the billable you can simply do:

```
$billable->update(['trial_ends_at' => $date]);
```
