### ISSUE TITLE
Metadata is not saved

### ISSUE THREAD

**Issue by Binternet** [laravel/cashier-stripe#1520]
- Cashier Version: 14.9.0 
- Laravel Version: 9.52.5
- PHP Version: 8.1.13
- Database Driver & Version: mysql

### Description:
Passing the metadata array to the cashier's subscription create method doesn't work:

```
        $metadata = [
            'custom_field_1' => 'value_1',
            'custom_field_2' => 'value_2',
        ];

        $response = $user->newSubscription('default', 'price_id')
            ->create(null, [
                'metadata' => $metadata,
            ]);
```

If I'm using this:
```
        $response = $user->newSubscription('default', 'price_id')
            ->withMetadata($metadata)
            ->create();
```
Then I see the metadata on the item level, but not on the subscription.

Since I need to read this metadata from the webhook, this is mandatory for me.

**Comment by Binternet** [comment]
Well, it seems that the `metadata` of the subscription is available at the `customer.subscription.created` webhook event, so that's something I can work with, but still - that value does not exist in the subscription itself.

**Comment by driesvints** [comment]
@Binternet doesn't the metadata appear if you retrieve the stripe subscription? 

```php
$subscription->asStripeSubscription()['metadata']
```

**Comment by Binternet** [comment]
@driesvints Well, it does appear there!
But it doesn't show in the `Metadata` section in Stripe's UI for that payment.
Maybe I'm confused between different sections?

In any event - as long as it appears in the `metadata` attribute of the subscription, I'm OK with it.

Thanks!

**Comment by de-raaf-media** [comment]
This is still an issue in 15.6.2? In don't see any meta data on the Stripe end but the subscription was successful.

```
$subscription = $request
            ->user()
            ->newSubscription("***", $plan)
            ->checkout([
                "success_url" => route("success"),
                "cancel_url" => route("cancel"),
                "metadata" => [
                    "entry_id" => $request->get("entry_id"),
                    "user_id" => $request->user()->id,
                ],
]);
```
