### ISSUE TITLE
`Cashier\Invoice::isDeleted()` method not working, Undefined constant `STATUS_DELETED`.

### ISSUE THREAD

**Issue by xiCO2k** [laravel/cashier-stripe#1521]
- Cashier Version: 14.9.0
- Laravel Version: 10.5.1
- PHP Version: 8.2.4
- Stripe PHP Version: 10.12.0

### Description:

After upgrading all my `composer` packages I got this error:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/823088/229573351-fb986ffd-7d51-46a7-9b11-e197d0685311.png">

Looks like Stripe SDK removed the constant `Stripe\Invoice::STATUS_DELETED`.

This issue was introduced in the `v10.12.0` release: https://github.com/stripe/stripe-php/releases/tag/v10.12.0

Cheers.

**Comment by driesvints** [comment]
Thank you. I submitted a bug report for this with them: https://github.com/stripe/stripe-php/issues/1474

**Comment by richardm-stripe** [comment]
We restored the enum value in https://github.com/stripe/stripe-php/releases/tag/v10.12.1. Sorry for the churn. We will remove this value in the next major version of `stripe-php`. The Stripe API doesn't actually return invoices with STATUS_DELETED though, so if you are relying on it you likely have dead code.

**Comment by driesvints** [comment]
I'll also deprecate this method on current cashier and remove it in the next version. Thanks all!
