### ISSUE TITLE
j

### ISSUE THREAD

**Issue by gaurangOneClickIt** [laravel/cashier-stripe#1528]
### Cashier Stripe Version

12.9

### Laravel Version

9

### PHP Version

8.2

### Database Driver & Version

MySql

### Description

Call to undefined method App\User::subscribedToPlan() {"userId":123,"exception":"[object] (BadMethodCallExcluminate/Support/Traits/ForwardsCalls.php:71)

### Steps To Reproduce

Select Plan.
Entered the card details

**Comment by ContactOneclick** [comment]
Hi @driesvints, Can you let me know about this? Because I have not get any proper solutions and got notification marked this as closed.

**Comment by gaurangOneClickIt** [comment]
Hi @driesvints , Can you please help me on this?

**Comment by driesvints** [comment]
I think you're on a newer version than 12.x and might have missed this part in the upgrade guide: https://github.com/laravel/cashier-stripe/blob/14.x/UPGRADE.md#renaming-plans-to-prices

**Comment by gaurangOneClickIt** [comment]
Okay @driesvints, Noted. Thank you for your quick response.
