### ISSUE TITLE
Metered billing amount not being set correctly

### ISSUE THREAD

**Issue by mikefrancis** [laravel/cashier-stripe#1532]
### Cashier Stripe Version

14.12.0

### Laravel Version

10.9.0

### PHP Version

8.2.6

### Database Driver & Version

sqlite homebrew

### Description

Hi there,

I'm hoping this is just me misunderstanding metered billing but I'm seeing an issue where I cannot seem to "set" the usage for a particular metered billing product.

I'm creating the subscription with no issue:

```php
$organisation->newSubscription(Config::get('billing.subscriptions.standard.id'))
  ->meteredPrice(Config::get('billing.subscriptions.standard.price'))
  ->create();
```

And when I use `$organisation->redirectToBillingPortal()` I can see the correct billing information in the Stripe portal, with 1x usage being reported.

* 1x usage shows as £3 ✅ 

When updating the usage using the 2nd parameter as described in the [docs](https://laravel.com/docs/10.x/billing#reporting-usage) to "set" rather than "increment":

```php
$total = $organisation->users->count();

$organisation->subscription(Config::get('billing.subscriptions.standard.id'))
  ->reportUsage($total, time());
```

I do not get the correct usage in Stripe (it is always way more than it should be):

* 2x usage shows as £9 ❌  (should be £6)
* 3x usage shows as £18 ❌  (should be (£9)

This is how my product is set up in Stripe:

<img width="391" alt="Screenshot 2023-05-14 at 12 37 02" src="https://github.com/laravel/cashier-stripe/assets/1672610/4de6fa79-6a3c-4782-a881-5eee8c4f9f61">

I have verified the correct quantity and "action" is being sent to Stripe by adding a log line above here:

https://github.com/laravel/cashier-stripe/blob/14.x/src/SubscriptionItem.php#L218

Please let me know if I can provide more info or debugging.

Thanks in advance!

### Steps To Reproduce

As above

**Comment by mikefrancis** [comment]
After playing around with the "Charge for metered usage by", I have achieved what I need to.

Closing this issue!

**Comment by driesvints** [comment]
How did you solve this? What went wrong?

**Comment by mikefrancis** [comment]
@driesvints The problem is summarised in the OP and the solution was updating the Stripe product setting I mentioned in the last comment.
