### ISSUE TITLE
Duplicate entry when swap()

### ISSUE THREAD

**Issue by arisdevx** [laravel/cashier-stripe#1535]
### Cashier Stripe Version

13.7

### Laravel Version

9.52

### PHP Version

8.2.5

### Database Driver & Version

5.7.25

### Description

i have duplicate entry issue when i use `swap()`.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1846-' for key 'subscription_items_subscription_id_stripe_plan_unique' (SQL: insert into `subscription_items` (`stripe_id`, `subscription_id`, `stripe_product`, `stripe_price`, `quantity`, `updated_at`, `created_at`) values (si_Nx3Edam0lVQdHm, 1846, prod_HBZUEjyL8zYfMQ, price_1ImDEVAysjaUmAKqaAdgs1Y2, 1, 2023-05-24 12:16:43, 2023-05-24 12:16:43))
```

in the previous version (laravel 8.x) i have no issue with  this method `swap()`

### Steps To Reproduce

User::subscription('premium')->skipTrial()->swap('price_new_price');

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
