### ISSUE TITLE
Feature request: custom key/value pairs for invoice as part of User model

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1536]
👋 Hi, I have already tried [posting something similar](https://stackoverflow.com/questions/76412610/laravel-cashier-create-subscription-with-additional-invoice-data-linked-to-custo) on Stackoverflow but this I believe is a feature request.

I know that there are [some things](https://laravel.com/docs/8.x/billing#syncing-customer-data-with-stripe) that can be customised for the billing details, but I've had quite a few requests in my platform for users wanting to add company details such as company tax information and/or company names **directly to their invoices** so that it's in their name.

I was hoping there could be a way to do this at subscription creation using:

```php
Auth::user()->newSubscription('default', $plan->stripe_id)
            ->withCoupon($coupon)
            ->create($request->input('token'), ['company_name' => 'Test]);
```

But this doesn't work, and equally, how would this work when updating?

Can there be some support for allowing key/value pairs to be put onto the invoice that can come from `User` model?

Maybe something like:

```php
/**
 * The "booted" method of the model.
 *
 * @return void
 */
protected static function booted()
{
    static::updated(queueable(function ($customer) {
        if ($customer->hasStripeId()) {
            $customer->syncStripeInvoiceDetails();
        }
    }));
}
```

Then `syncStripeInvoiceDetails` can look for defined key/value pairs on `User`

**Comment by driesvints** [comment]
From the docs: https://laravel.com/docs/10.x/billing#additional-details

```php
$subscription = $user->newSubscription('default', 'price_monthly')->create($paymentMethod, [
    'email' => $email,
], [
    'metadata' => ['note' => 'Some extra information.'],
]);

$note = $subscription->asStripeSubscription()->metadata['note'];
```

Unfortunately it's not possible to set metadata that will be applied to each recurring invoice for a subscription when that subscription is initially created. Also, because invoices can contain line items linked to different subscriptions it can be hard to retrieve the metadata of a specific subscription inside an invoice.

But you can add any additional details for an invoice you want: https://laravel.com/docs/10.x/billing#generating-invoice-pdfs

Override the invoice blade file with:

```bash
php artisan vendor:publish --tag="cashier-views"
```

And then edit `receipt.blade.php` with whatever you want. Pass details like:

```php
return $request->user()->downloadInvoice($invoiceId, [
    'custom-thing' => $request->user()->custom_thing,
]);
```

**Comment by sts-ryan-holton** [comment]
@driesvints Thanks for this, I'll have a play and report back if I have any other questions or behaviour queries

**Comment by sts-ryan-holton** [comment]
@driesvints Just checking, looks like your suggestion is working, can I check though that when publishing the views I only need to customise the receipt, if I delete the payment blade file will it then use the default one from vendor?

**Comment by driesvints** [comment]
@sts-ryan-holton yep you can delete that one and just use the one you need.
