### ISSUE TITLE
Problems with the proration of the first payment

### ISSUE THREAD

**Issue by xbfast** [laravel/cashier-stripe#1539]
### Cashier Stripe Version

^13.17

### Laravel Version

^10.10

### PHP Version

8.1

### Description

Good afternoon, I am creating a subscription web page. In which, the first time you subscribe you pay €7.90 and the other payments are €14.90.

To realize the difference in prices, I have created a subscription with two prices. When a person makes the first payment I modify their subscription and I change one price for the other

```
`$user->subscription($request->producto, $request->plan)->noProrate()->swap('price_1NIDmOFv7V7yZ8oEfZ11FYNj');`
//I cancel the apportionment , with noProrate()
```

My client needs the following payments to be made on the 30th of every month, so I did the following.

```
            $fecha = Carbon::now()->format('Y-m-30');
            $anchor = Carbon::parse($fecha);

            $user->newSubscription($request->producto, $request->plan)
                 ->anchorBillingCycleOn($anchor->startOfDay())
                 ->create($paymentMethod, ['proration_behavior' => 'none',]);
```

The problem is that the first payment is prorating me and I want the €7.90 to be charged.
What I can do? Talking to Stripe support they tell me to pass the parameter proration_behavior = 'none' but it still doesn't work.

Thanks and regards

**Comment by driesvints** [comment]
> Talking to Stripe support they tell me to pass the parameter proration_behavior = 'none' but it still doesn't work.

If this doesn't work then I'm afraid we can't do anything ourselves because that's exactly what `noProrate` does :/
Try bringing this back to Stripe's attention please.
