### ISSUE TITLE
Tracking of multiple Customers ids for 1 email

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/cashier-stripe#1540]
Hello,
i dunno if i should post this in the bug section or extra feature, so here it is. 

I've noticed that Stripe create multiple Customers ids for 1 email if you follow those steps :
1. create a (guest) checkout sessions and do a successful payment.
2. then do it once more, but in the checkout page logout & refill the fields with the same infos than before... But let's change the card holder name this time (not necessary, but make it easier to check in the Stripe Dashboard).
3. the result in the Dashboard should show 2 customers with the same email address but different names.

The problem here is that Cashier have a unique Customer `stripe_id` in the `users` table.
and if multiple subscription is on going on multiple customers then the `User` can't cancel a specific one. 😅

to get all the customers related to the `User`, something like this is needed :
```php
$stripeSearchResult = $stripe->customers->search(['query' => 'email:"user@example.com"']);

dump($stripeSearchResult->data); // return an array of \Stripe\Customer
```

soooo........ 🙄 what do you propose ? an entire package review or ... 🤷‍♂️ ?

**Comment by driesvints** [comment]
So, this is not how things work. Customers in Stripe are unique but can have multiple records for the same email address. Stripe doesn't considers that a unique field and neither does Cashier. Cashier just follows the same pattern as Stripe.

I would not suggest to start guest checkouts for subscriptions. These were only intended for loose one-time purchases, not subscriptions. I'd always make sure your customers have an account in your app before they get a subscription.

**Comment by Ronan-Lenor** [comment]
Ah indeed the `newSubscription()` don't let Stripe creating a new customer id. Thanks for the clarification on that point.

Nonetheless, if someone look at theses comments in the future, here is a concept idea:
In the case that a `User` is created after the purchase (in the webhook) to shorten the payment funnel, an option would be to create change the migration as mentioned here :
[https://laravel.com/docs/10.x/billing#billable-model](https://laravel.com/docs/10.x/billing#billable-model)
and create a `User` <> `Customer` (containing the Billable Trait) `HasMany` relationship and develop on that base.

Anyway, that would be great if `Cashier` could work on a such case. Accelerating the payment process is usually always welcomes.
