### ISSUE TITLE
Our database is updated together with Stripe

### ISSUE THREAD

**Issue by xbfast** [laravel/cashier-stripe#1542]
### Cashier Stripe Version

13.17

### Laravel Version

^10.10

### PHP Version

8.1

### Description

When we add a subscription from our app using Cashier, stripe receives this data. But for example, if a subscription has trial days, in our `subscriptions` DB we have a `stipe_status` field with the status of the subscription. But my question is, when the date arrives, will that field only be set to `active` or how to do it.

Like `subscriptions_items` if I'm not mistaken it is the payments, but this is not updated with the payments that stripe generates.

Do I have to do something to make them connect to each other?

Thank you

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by xbfast** [comment]
version of what? I think I have all the latest. And what does that have to do with knowing how to update the cashier database?
