### ISSUE TITLE
createOrGetStripeCustomer() don't return expanded fields

### ISSUE THREAD

**Issue by Ronan-Lenor** [laravel/cashier-stripe#1546]
### Cashier Stripe Version

14.12.3

### Laravel Version

9.52.9

### PHP Version

8.1.7

### Database Driver & Version

MySQL 5.7.37

### Description

When the method `createOrGetStripeCustomer(array $options = [])` is called with the intention of retrieving a `Customer`, it doesn't pass any array parameters to `asStripeCustomer(array $expand = [])`

could you replace in `createOrGetStripeCustomer()` the part that manage the "get" behavior ?
```php
// ManagesCustomer.php
if ($this->hasStripeId()) {
  return $this->asStripeCustomer( /*..if "expand" key exists, return the array value ...*/ );
}
```

### Steps To Reproduce

```php
// from
$stripe = \Laravel\Cashier\Cashier::stripe();
$stripeCustomer = $stripe->customers->retrieve($user->stripe_id, ['expand' => ['tax']]);

// to
$stripeCustomer = $user->createOrGetStripeCustomer(['expand' => ['tax']]);
```

**Comment by driesvints** [comment]
Yeah that would be useful indeed. Feel free to send in a PR 👍
