### ISSUE TITLE
How to add trial period when swap plan?

### ISSUE THREAD

**Issue by ks-dipeshc** [laravel/cashier-stripe#1552]
### Cashier Stripe Version

14.12

### Laravel Version

9.52.10

### PHP Version

8.2.3

### Database Driver & Version

psql (PostgreSQL) 10.23 (Ubuntu 10.23-0ubuntu0.18.04.2)

### Description

Hello, Currently my users is in active plan, I want to give them a 14 days trial when they swap the plan.
How Can I give them trial when swap the plan?

### Steps To Reproduce

Here is my code when swap plan:

`$user->subscription("basic")->swap($plan->stripe_plan_id);`

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
