### ISSUE TITLE
The payment attempt failed because additional action is required before it can be completed

### ISSUE THREAD

**Issue by bhagchandani** [laravel/cashier-stripe#1553]
### Cashier Stripe Version

14.12

### Laravel Version

10.10

### PHP Version

8.1

### Database Driver & Version

8.1.18

### Description

I have implemented the code according to the documentation and other resources. but when I try to complete the payment it shows me the following error "The payment attempt failed because additional action is required before it can be completed" When I try to handle it via Incomplete payment Exception the payment succeeded but the status of the payment does not update in the database.. it always shows Incomplete but I can see the payment success in stripe account. As the redirect routes do not return any additional parameter I am unable to update the status at local. 

### Steps To Reproduce

Controller code after entering card details. 
`try {
            $subscription = $user->newSubscription($planname, $stripe_plan)
                                    ->create($request->token);
        } catch (IncompletePayment $exception) {
            return redirect()->route(
                'cashier.payment',
                [$exception->payment->id, 'redirect' => route('dashboard')]
            );
        }`

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
