### ISSUE TITLE
Stripe Notice: Undefined property of Stripe\StripeObject instance: type

### ISSUE THREAD

**Issue by MattWiseParking** [laravel/cashier-stripe#1555]
### Cashier Stripe Version

14.12.3

### Laravel Version

10.4.1

### PHP Version

php 8.1.4

### Database Driver & Version

MySql 5.7.39 on MacOs Ventura 13.2.1

### Description

I keep receiving in the error logs the following error every time i refresh a page which outputs any cashier methods on the user object

`local.ERROR: Stripe Notice: Undefined property of Stripe\StripeObject instance: type`

### Steps To Reproduce

After adding a default payment method following the cashier documentation, any instances of calling any stripe methods on the user object automatically shows this error message.  Although stripe appears to be doing what it should do, im not too sure why I keep receiving this error messsage.

The code I am using to add a payment method:

```
public function addPaymentMethod(Request $request)
    {
        try {
            if(auth()->user()->hasStripeId() === false) {
                auth()->user()->createAsStripeCustomer();
            }
            $user = auth()->user();
            $user->addPaymentMethod($request->paymentMethodId);
            if($request->has('default')) {
                $user->updateDefaultPaymentMethod($request->paymentMethodId);
            }
            return redirect()->back()->with('success','Your card has successfully been added');
        } catch(\Exception $e) {
            Log::error('error when adding a new payment method: '.$e->getMessage());
            return redirect()->back()->withErrors(['errors' => 'Error adding a new payment method']);
        }
    }
```

**Comment by crynobone** [comment]
I believe you need to contact Stripe Support team as suggested in https://github.com/stripe/stripe-php/issues/1538#issuecomment-1655892073

You can contact them here: https://support.stripe.com/contact
