### ISSUE TITLE
Support for Stripe PHP v12

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1556]
:wave: Hi,

Just bumping the most recent [Stripe](https://github.com/stripe/stripe-php/releases/tag/v12.0.0) changes that have been released. Wondered if Cashier will try to support changes?

**Comment by driesvints** [comment]
Thanks for informing us! I'll have a look at this soonish.

**Comment by localheinz** [comment]
@driesvints 

Would it make sense to drop support for older versions of `stripe/stripe-php`, too?

**Comment by localheinz** [comment]
@driesvints 

For reference, also see https://github.com/stripe/stripe-php/blob/v12.0.0/CHANGELOG.md.

**Comment by driesvints** [comment]
@localheinz yeah I think so maybe. All of this has to go into master.

**Comment by sts-ryan-holton** [comment]
Great news! Any update when Stripe v12 will be supported or will this be Cashier v15 exclusive?

**Comment by driesvints** [comment]
Got this merged for a next v15 update. We're using the v13 version of the SDK now.

**Comment by localheinz** [comment]
Thank you. @driesvints!
