### ISSUE TITLE
Use service container to resolve StripeClient?

### ISSUE THREAD

**Issue by martinbean** [laravel/cashier-stripe#1559]
I’ve noticed in `Laravel\Cashier\Cashier`, the `StripeClient` instance is just manually instantiated:

```php
return new StripeClient(array_merge([
    'api_key' => $options['api_key'] ?? config('cashier.secret'),
    'stripe_version' => static::STRIPE_VERSION,
    'api_base' => static::$apiBaseUrl,
], $options));
```

Would it be possible to use the service container to build this `StripeClient` instance instead? As I’m having difficulty testing code that uses Cashier methods when I don’t have a `STRIPE_SECRET` set in my testing environment:

> The following exception occurred during the last request:
> 
> Stripe\Exception\InvalidArgumentException: api_key cannot be the empty string in /var/www/html/vendor/stripe/stripe-php/lib/BaseStripeClient.php:257

It would be nice if the `StripeClient` was instead resolved using the service container:

```php
return resolve(StripeClient::class, array_merge([
    'api_key' => $options['api_key'] ?? config('cashier.secret'),
    'stripe_version' => static::STRIPE_VERSION,
    'api_base' => static::$apiBaseUrl,
], $options)));
```

I would then be able to mock any `StripeClient` method calls in my tests:

```php
$this->mock(StripeClient::class, function (MockInterface $mock) {
    // Great expectations...
});
```

Or even just swap it out entirely for a fake:

```php
$this->swap(StripeClient::class, FakeStripeClient::class);
```

**Comment by driesvints** [comment]
Yeah I think we could maybe do this (use `app` instead of `resolve` though).

Does overwriting the `stripe` method on your billable help as well maybe?

**Comment by martinbean** [comment]
> Does overwriting the `stripe` method on your billable help as well maybe?

@driesvints Somewhat. It allows me to mock the immediate `StripeClient` call, but doesn’t help with deeper calls, such as to get or create customer.

**Comment by driesvints** [comment]
Okay. Can you send in a PR? We'll get that in then.
