### ISSUE TITLE
Stripe Processing fees

### ISSUE THREAD

**Issue by yormy** [laravel/cashier-stripe#1564]
When I subscribe a user to a plan of say 20 Euro, stripe charges 0.90 Euro for the payment handling. However in their webhooks there is no mentioning of these processing fees. Is there an easy way of getting these processing fees ?

The response of stripe to this question was:
```
What you can do is listen to the related event and use the ID to retrieve the object where Stripe fees are available.
Let's say in a PaymentIntent, you have to retrieve the charge details and get the balance transaction ID, then do a retrieve call using the txn_xxxxxxxxxxxxx where the Stripe fee will be returned in response.
Our event notification doesn't expand responses, so in order to get the data that you need, you will have to use expanding responses. https://stripe.com/docs/expand
```
I was wandering if cashier already supports this, as I could not find it in the docs

**Comment by driesvints** [comment]
Thanks. Right now we don't have any such functionality and don't plan to implement this ourselves. Cashier offers a way to define event handlers so it's easy to listen to any incoming event to get the data you need: https://laravel.com/docs/10.x/billing#defining-webhook-event-handlers

**Comment by yormy** [comment]
Oke, thanks for the speedy reply !

**Comment by clementmas** [comment]
For future reference, here's one way to retrieve the Stripe fees from the `setup_intent.succeeded` webhook:

```php
protected function handlePaymentIntentSucceeded(array $payload)
{
    $data = $payload['data']['object'];

    $charge = Cashier::stripe()->charges->retrieve(
        $data['latest_charge'],
        [
            'expand' => [
                'balance_transaction'
            ],
        ]);

    $fees = $charge['balance_transaction']['fee'];
}
```
