### ISSUE TITLE
On cancel subscription immediately from customer portal, ends_at column in the subscription table stays NULL

### ISSUE THREAD

**Issue by micos7** [laravel/cashier-stripe#1567]
### Cashier Stripe Version

14.12

### Laravel Version

10.10

### PHP Version

8.2.10

### Database Driver & Version

Mysql 8 smth Ubuntu

### Description

I create a subscription from the checkout
![image](https://github.com/laravel/cashier-stripe/assets/4460809/bcd6749b-857f-41af-9892-3861b020cb7a)
Then I cancel it from the customer portal 
![image](https://github.com/laravel/cashier-stripe/assets/4460809/1cc8c232-298c-4838-bc56-e0a2f2cff67a)
In my webhook all customer events are listened to 
customer.bank_account.created
customer.bank_account.deleted
customer.bank_account.updated
customer.card.created
customer.card.deleted
customer.card.updated
customer.created
customer.deleted
customer.discount.created
customer.discount.deleted
customer.discount.updated
customer.source.created
customer.source.deleted
customer.source.expiring
customer.source.updated
customer.subscription.created
customer.subscription.deleted
customer.subscription.paused
customer.subscription.pending_update_applied
customer.subscription.pending_update_expired
customer.subscription.resumed
customer.subscription.trial_will_end
customer.subscription.updated
customer.tax_id.created
customer.tax_id.deleted
customer.tax_id.updated
customer.updated

"api_version": "2023-08-16",

In customer portal subscription cancel is set to immediately

![image](https://github.com/laravel/cashier-stripe/assets/4460809/5d252a4e-747e-4249-a8c7-73535462b9a8)

After I click cancel i get 2 events in logs
![image](https://github.com/laravel/cashier-stripe/assets/4460809/b18b6915-b930-4bfc-8f4f-3a005b5edbce)

In subscription updated event I get the Json 
![image](https://github.com/laravel/cashier-stripe/assets/4460809/5d67099b-04da-430a-a582-c5fbee0b0bd2)

cancel_at is null but not canceled_at

So I changed in this snippet of code cancel_at in canceled_at in the function handleCustomerSubscriptionUpdated

```
if (isset($data['cancel_at_period_end'])) {
                if ($data['cancel_at_period_end']) {
                    $subscription->ends_at = $subscription->onTrial()
                        ? $subscription->trial_ends_at
                        : Carbon::createFromTimestamp($data['current_period_end']);
                } elseif (isset($data['canceled_at'])) {
                    $subscription->ends_at = Carbon::createFromTimestamp($data['canceled_at']);
                } else {
                    $subscription->ends_at = null;
                }
            }
```
I am in test mode. Am I missing something ,is this an issue in the latest version or what?
Thanks

### Steps To Reproduce

Just create a subscription from checkout and cancel from customer portal.It should be enough.

**Comment by driesvints** [comment]
Thank you. This has been fixed already for the upcoming Cashier v15 release. Right now we don't have an ETA for it, sorry.

**Comment by micos7** [comment]
Extending the webhook with those modification should be enough?

**Comment by driesvints** [comment]
@micos7 yeah that's a good one in the meantime 👍

**Comment by micos7** [comment]
Thanks.
