### ISSUE TITLE
`delete` method of `PaymentMethod` class returns `void` instead of `\Stripe\PaymentMethod`

### ISSUE THREAD

**Issue by jwjenkin** [laravel/cashier-stripe#1568]
### Cashier Stripe Version

12.17.2

### Laravel Version

8.83.27

### PHP Version

8.1.17

### Description

According to the docstring of `PaymentMethod::delete`, calling the function will return `\Stripe\PaymentMethod` regardless of result. However, the `ManagesPaymentMethods::removePaymentMethod` returns to void, leading to issues if you are validating the result of the `delete` function call.

This appears to still affect the latest Cashier version, as looking at the source code still has it in there.
https://github.com/laravel/cashier-stripe/blob/14.x/src/PaymentMethod.php#L51
https://github.com/laravel/cashier-stripe/blob/14.x/src/Concerns/ManagesPaymentMethods.php#L115

I suppose there are a few options:
* change the docstring of `PaymentMethod::delete` to have `@return void`
* change `ManagesPaymentMethods::removePaymentMethod` to return the `PaymentMethod`
* change `ManagesPaymentMethods::removePaymentMethod` to return a `bool` result and change the docstring of `PaymentMethod::delete` to `@return bool`

### Steps To Reproduce

```
$ php artisan tinker
Psy Shell v0.11.9 (PHP 8.1.17 — cli) by Justin Hileman
> $user = User::first();
[!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
= App\Models\User {#5488
...
}

> $user->paymentMethods()->first();
= Laravel\Cashier\PaymentMethod {#5545}

> $user->paymentMethods()->first()->delete();
= null

> $user->paymentMethods()->first();
= null
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by jwjenkin** [comment]
Howdy!

The "problem" should still exist, as the docs that cause the confusion are still in the latest 14.x blobs:
https://github.com/laravel/cashier-stripe/blob/14.x/src/PaymentMethod.php#L51
https://github.com/laravel/cashier-stripe/blob/14.x/src/Concerns/ManagesPaymentMethods.php#L115

Main point in here:
It isn't necessarily a bug in code, it's a documentation issue that causes confusion.

Thanks!
