### ISSUE TITLE
Issue with product prices having multiple currencies

### ISSUE THREAD

**Issue by edulazaro** [laravel/cashier-stripe#1570]
When a user has, let's say GBP as the default user currency and the product price has USD as base currency, but also values for other currencies, including GBP, we get this error:

The currency of the selected prices (usd) does not match the customer currency (gbp).

Added the `withCurrency($currency)` and `withUserDefaultCurrency()` methods for the `SubscriptionBuilderClass` to sort it, so if the user has GBP as a currency and the product has a USD pricing which also includes a GBP option, the GBP one will be used if specified.

**Comment by edulazaro** [comment]
@taylorotwell

This does not correct a bug as long as many currencies are not assigned to a price.

Providing further explanation, let's say that at Stripe we create a price and then assign an amount for each currency:

![image](https://i.ibb.co/87nMc55/currencies.jpg)

Let's assume there's a product called PlanA, it has 2 prices, one for monthly subscriptions and another for yearly, and each of them with GBP as base currency but that also with values for USD, SEK and EUR.

Now, let's say that a customer is on Sweden and already have a `stripe_id`, or in the same way, imagine the customer subscribes to the price using stripe elements directly, setting **SEK** as currency:

```php
new \Stripe\StripeClient(STRIPE_SECRET_HERE);

$stripe->subscriptions->create([
    'customer' => auth()->user()->stripe_id,
    'items' => [[
        'price' => PRICE_ID_HERE
    ]],
    'currency' => 'SEK',
    'payment_behavior' => 'default_incomplete',
    'payment_settings' => ['save_default_payment_method' => 'on_subscription'],
    'expand' => ['latest_invoice.payment_intent'],
    'metadata' => [
       'name' => HERE_THE_PLAN_A_NAME,
     ]
]);
```

This customer will have SEK as its main currency, or might have SEK assigned from before (the currency cannot be changed once subscribed).

Now, imagine that next month this customer wants to subscribe to PlanB. which also has a price in GBP as base currency but that also has a price for USD, SEK and EUR.

I will let the customer pay with the card which is already saved as the default payment method, so I will do:

```php
auth()->user()->newSubscription(PLAN_B_NAME, PRICEB_ID_HERE)->create(PM_ID);
```

This is what will happen:

![image](https://i.ibb.co/QN3W6fc/errr.jpg)

This is because it's not possible to specify the currency, so the default one will be used, which might no be the same as the customer currency. To sort it, it's enough with sending the currency to Stripe, so I just added the 2 methods above, so you can do:

```php
auth()->user()->newSubscription(PLAN_B_NAME, PRICE_ID_HERE)->withCurrency('SEK')->create(PM_ID);
```
The subscription will be successfully created.

Or also:

```php
auth()->user()->newSubscription(PLAN_B_NAME, PRICE_ID_HERE)->withUserDefaultCurrency()->create(PM_ID);
```
If it cannot be added, we can use a fork or extend some classes meanwhile.

Thanks for reading!

**Comment by driesvints** [comment]
Hi @edulazaro. You can already provide the currency with the third argument for the `create` method on the subscription builder. I don't have the bandwidth atm to think this through properly so I suggest you use that for now. Thanks
