### ISSUE TITLE
Error when refreshing database: "no such column: stripe_id"

### ISSUE THREAD

**Issue by ikmolbo** [laravel/cashier-stripe#1574]
### Cashier Stripe Version

14.12.6

### Laravel Version

10.10

### PHP Version

8.2.10

### Database Driver & Version

SQLite on MacOS on arm64

### Description

I installed Cashier with Laravel (SQLite). Migration up works fine. However, when refreshing the migration (`migrate:refresh`), the following error is triggered as the tables and columns are dropped:

 `SQLSTATE[HY000]: General error: 1 error in index users_stripe_id_index after drop column: no such column: stripe_id (Connection: sqlite, SQL: alter table "users" drop column "stripe_id")`

I tried this with a completely fresh installation of Laravel with Cashier - same result.

 2019_05_03_000001_create_customer_columns .................................................................................. 1ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[HY000]: General error: 1 error in index users_stripe_id_index after drop column: no such column: stripe_id (Connection: sqlite, SQL: alter table "users" drop column "stripe_id")

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:801
    797▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    798▕                 );
    799▕             }
    800▕ 
  ➜ 801▕             throw new QueryException(
    802▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    803▕             );
    804▕         }
    805▕     }

      +47 vendor frames 

  48  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

### Steps To Reproduce

composer create-project laravel/laravel stripe-app && cd stripe-app
... enable SQLite DB in .env ...
composer require laravel/cashier
php artisan migrate
php artisan migrate:refresh => error

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ikmolbo** [comment]
Thanks for your response but this looks to me like a (possible) bug with the library, given that a clean install of Laravel and Laravel Cashier results in the error I have described, making this the right place to post my issue.

**Comment by hcancelik** [comment]
@ikmolbo did you figure out the issue? I have a fresh Laravel 11 install and having this issue when I run `artisan migrate:refresh`
