### ISSUE TITLE
Checkout overwrites default `subscription_data` with `$sessionOptions`

### ISSUE THREAD

**Issue by edalzell** [laravel/cashier-stripe#1578]
### Cashier Stripe Version

14.12.7

### Laravel Version

10.25.2

### PHP Version

8.2.11

### Description

I was trying to create a Checkout Session with a trial period and not collect payment information.

According to the Stripe [docs](https://stripe.com/docs/billing/subscriptions/trials#configure-free-trials-without-payment-methods-to-cancel), you need to set the payload to something like this:

```php
                'payment_method_collection' => 'if_required',
                'subscription_data' => [
                    'trial_period_days' => 14,
                    'trial_settings' => [
                        'end_behavior' => ['missing_payment_method' => 'cancel'],
                    ],
                ],
```

However, if you pass that in to the `checkout` method, the `array_merge` gets rid of the "default" payload, including:

```php
                    'metadata' => ['name' => 'default'],
```

I believe what's needed is [`array_merge_recursive`](https://www.php.net/manual/en/function.array-merge-recursive.php) instead of `array_merge` [here](https://github.com/laravel/cashier-stripe/blob/5c831f122b1e27d63862495653761421e512ff0d/src/SubscriptionBuilder.php#L364)

### Steps To Reproduce

Try to create a checkout session using:

```php
            ->checkout([
                'payment_method_collection' => 'if_required',
                'subscription_data' => [
                    'trial_period_days' => 14,
                    'trial_settings' => [
                        'end_behavior' => ['missing_payment_method' => 'cancel'],
                    ],
                ],
            ]);
```

And you'll see the metadata is missing from the Stripe request.

**Comment by edalzell** [comment]
The work-around is to add the default fields:

```php
            ->checkout([
                'payment_method_collection' => 'if_required',
                'subscription_data' => [
                    'metadata' => ['name' => 'default'],
                    'trial_period_days' => 14,
                    'trial_settings' => [
                        'end_behavior' => ['missing_payment_method' => 'cancel'],
                    ],
                ],
            ])->redirect();
```

**Comment by driesvints** [comment]
Hey @edalzell. Thanks for this. I believe you're right. I've sent in a PR for this: https://github.com/laravel/cashier-stripe/pull/1579
