### ISSUE TITLE
Call to a member function cancel on null on test

### ISSUE THREAD

**Issue by handhikadj** [laravel/cashier-stripe#1584]
### Cashier Stripe Version

14.12.8

### Laravel Version

10.22.0

### PHP Version

8.1.4

### Database Driver & Version

MySQL 8

### Description

I have this on my test:
```php
public function test_user_can_cancel_subscription()
    {
        $this->stripeSubscribe();

        $response = $this->postJson(route('api.subscription.cancel'));

        $response
            ->assertOk()
            ->assertJson(['message' => 'Successfully cancelled subscription']);
    }
```

my Api controller:
```php
public function cancelSubscription(Request $request)
    {
        $request->user()->subscription()->cancel();

        return response()->json(['message' => 'Successfully cancelled subscription']);
    }
```

I'm getting `Call to a member function cancel() on null` . The `subscription()` is null here on test.
On postman, the cancel works fine
How do I solve this?

### Steps To Reproduce

just code the code above and run test

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.
