### ISSUE TITLE
Cashier support for Stripe 'embedded checkout'

### ISSUE THREAD

**Issue by joshembling** [laravel/cashier-stripe#1590]
Stripe has recently released a new embedded option for Stripe Checkout. Will Cashier be supporting this addition anytime soon?

https://embedcheckout.com/
https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=embedded-checkout

**Comment by driesvints** [comment]
Could definitely be cool. Would love to get a PR for this.

**Comment by driesvints** [comment]
Gonna close this one since https://github.com/laravel/cashier-stripe/pull/1605 got merged.
