### ISSUE TITLE
Multiple payment providers

### ISSUE THREAD

**Issue by AlastairDewar** [laravel/cashier-stripe#1591]
Hello,

I wondered if there was a reason why Cashier had a separate repo for Stripe and Paddle (as well as Braintree and Mollie previously)?

I am working on a project which has multiple payment providers (Stripe, Apple In-App Purchase, Roku Pay, Google Pay, etc.), and I would have thought the 'Laravel way' would be to add 'drivers' for each of these providers similar to Storage for example.

I would be happy of course to contribute a PR towards the restructuring to support this, but it feels like a large fundamental (and potentially breaking) change that would need more discussion first.

Thanks,
Ally

**Comment by driesvints** [comment]
Payment providers each have very different concepts and ways of how they handle payments. Each having a vastly different API and core concepts, there's no way to unify them into a single package and at the same time be as thorough and flexible as each Cashier package is.
