### ISSUE TITLE
Prorate not working properly with swap price as i tried many time but still it exist.

### ISSUE THREAD

**Issue by shahbaz161013** [laravel/cashier-stripe#1592]
### Cashier Stripe Version

14.12

### Laravel Version

10.10

### PHP Version

8.1

### Description

Prorate not working properly with swap price as i tried many time but still it exist.
sometime it simply swap price in invoice with no proration but mostly it applied

### Steps To Reproduce

        $user = User::find(auth()->user()->id);
        $user->subscription('6')->noProrate()->swapAndInvoice('price_1O4plQKOzN03UPxzKJVf3JpB');
        dd('ok');

Total: $10.00
Applied balance: ($8.93)
Amount due: $1.07
sometime it behave like

Next invoice
Total: $10.00
Applied balance: ($10.00)
Amount due: $0.00

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
