### ISSUE TITLE
Cashier findBillable can't find soft deleted users

### ISSUE THREAD

**Issue by clementmas** [laravel/cashier-stripe#1598]
I'm running into an issue when subscribed users delete their accounts. The Stripe webhook can't find users that are [soft deleted](https://laravel.com/docs/10.x/eloquent#soft-deleting), so it can't cancel the subscription record.

So far I've been overriding the `WebhookController`:

```php
protected function getUserByStripeId($stripeId)
{
    // return Cashier::findBillable($stripeId);

    return User::withTrashed()->where('stripe_id', $stripeId)->first();
}
```

But that doesn't work if I follow the documention on [Defining Webhook Event Handlers](https://laravel.com/docs/10.x/billing#defining-webhook-event-handlers).

So we could either detect if the `Cashier::$customerModel` uses the `SoftDeletes` trait, or support passing an Eloquent query to `Cashier::useCustomerModel(User::withTrashed())`.

I can PR this change but I'd like to know if you would accept it first.

I understand this is not a common scenario. But soft deleting is a core Laravel feature and it's very useful to propose a recovery mecanism before everything is erased/pruned.

Thanks!

**Comment by driesvints** [comment]
@clementmas I think you always want to retrieve a user here, even if it's soft deleted so `withTrashed` by default sounds good to me. I've sent in a fix for this: https://github.com/laravel/cashier-stripe/pull/1599

Thanks for reporting 👍
