### ISSUE TITLE
Automatically cancel recurring subscriptions when a User is deleted

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1603]
:wave:

Hi, I came across [this](https://github.com/laravel/cashier-stripe/issues/317) from a few years ago and wondered if this is up for discussion now. Essentially, customers of my platform that have subscribed to a plan then proceed to delete their account, they then have no way of cancelling their subscription since their account is soft deleted in my platform, I have no easy way of identifying this resulting in troublesome customers.

Can Cashier automatically cancel any active subscriptions when a user is deleted / soft deleted so that the frustrations of customers don't arrise? The [docs](https://laravel.com/docs/10.x/billing#cancelling-subscriptions) for cancelling subscriptions doesn't mention much about this.

For context, here's how I'm deleting a user's account via my controller.

```php
/**
 * Remove the specified resource from storage.
 *
 * @param  int  $id
 */
public function destroy(User $account, Request $request)
{
	try {
		$user = Auth::user()->delete();
		return new ApiSuccessResponse(null, [], 204);
	} catch (\Exception $e) {
		return new ApiErrorResponse($e, [
			'message' => 'Unable to delete your account, please try again later.',
		]);
	}
}
```

**Comment by driesvints** [comment]
Hi there. No we consider this an app-level decision and not something the package should decide for you. I've added a note about this in the docs: https://github.com/laravel/docs/pull/9144

**Comment by sts-ryan-holton** [comment]
Ah right, thanks.
