### ISSUE TITLE
Cashier support for no-cost orders via Checkout

### ISSUE THREAD

**Issue by jakecausier** [laravel/cashier-stripe#1610]
Stripe has launched a [new feature](https://stripe.com/docs/payments/checkout/no-cost-orders) through their Checkout which allows for no-cost orders to be placed when the Checkout session is set to `payment`. However, attempting to create a checkout session with Cashier when the line items total to zero brings up the following error:

```The Checkout Session's total amount due cannot be zero in `payment` mode.```

Our website depends on Stripe webhooks to confirm a user has completed and paid for an order (even free orders, like subscriptions) so having to work around this would be complicated (and frankly, annoying).

The feature is on Stripe's API version 2023-08-16 which is quite far ahead of the current API version locked for Cashier, is this potentially being looked into being changed soon or would it be worth implementing a workaround myself for this using Stripe's PHP API directly?

**Comment by driesvints** [comment]
I'm gonna work on a new Cashier Stripe version very soon to support their latest API updates so I'll also have a look at this one, thanks.

**Comment by jakecausier** [comment]
Great to hear, thanks!

**Comment by driesvints** [comment]
I guess this will be supported once Cashier v15 is released with the new version. The release is almost ready.

**Comment by cerberusmaster** [comment]
@driesvints this problem solved already?
I am encountering same issue when I use 100% discount coupon, I don't want collect any payment from customers.

**Comment by driesvints** [comment]
@cerberusmaster I can't comment on that. We're using the version that has this feature. If things don't work like you expect then you should contact Stripe support.
