### ISSUE TITLE
Add support for Embeddable Pricing Tables

### ISSUE THREAD

**Issue by scalaxofaiur** [laravel/cashier-stripe#1622]
Hello i found that Cashier currently doesn't work with Embeddable Pricing Tables

https://stripe.com/docs/payments/checkout/pricing-table

Currently, when the user creates a subscription with pricing tables, Stripe creates a new customer.

Customer.subscription.created webhook doesn't seem to be able to connect the new customer to laravel user.

Stripe gives the chance to attach a "client-reference-id" that could be used to pass the authenticated user id (or better an encrypted string that identify the user) back to cashier with checkout.session.completed webhook

https://stripe.com/docs/payments/checkout/pricing-table#track-subscriptions

**Comment by driesvints** [comment]
Ah sorry that's something else. I'll have a look.

**Comment by driesvints** [comment]
Right now I don't see an immediate way to make this work with Cashier. We solely rely on the customer.subscription.created and/or customer.subscription.updated webhooks to create the subscription and attach it to the user. There doesn't seems to be a way to let checkout attach this `client_reference_id` to the subscription as well. Therefor, from what I can tell, this isn't possible. 

I don't have the time at the moment to deep dive into this to find workarounds but would appreciate PR's or other insights if there are any. Thanks

**Comment by scalaxofaiur** [comment]
Thanks @driesvints, at the moment i decided to avoid using Embeddable Pricing Tables and have implemented one on my own by reading products data directly from Cashier facade.

Should i have more updates i will surely write them here.

Thanks.

**Comment by driesvints** [comment]
Going to close this one as it's not likely this can be resolved.

**Comment by virgildotcodes** [comment]
Hey @driesvints, I just came across this today and figured out a way to make it work in my own project. Essentially, we just need to pass a CustomerSessionClientSecret to the component as outlined here:

https://docs.stripe.com/payments/checkout/pricing-table#customer-session

So in the controller that renders your Store page you can do something like this:

```php
    public function index(Request $request)
    {
        // Set Stripe API key
        Stripe::setApiKey(env('STRIPE_SECRET'));

        // Get the authenticated user's stripe_id
        $user = $request->user();
        $stripeId = $user->stripe_id;

        if (!$stripeId) {
            // Fallback: create a customer if none exists
            $user->createAsStripeCustomer();
            $stripeId = $user->stripe_id;
        }

        // Create a Customer Session
        $customerSession = CustomerSession::create([
            'customer' => $stripeId,
            'components' => [
                'pricing_table' => ['enabled' => true],
            ],
        ]);

        // Pass the client_secret to the frontend
        return inertia('Store/Index', [
            'auth' => [
                'user' => $user,
            ],
            'customerSessionClientSecret' => $customerSession->client_secret,
        ]);
    }
```

I'm not sure if this type of functionality is in the scope of what you'd like to support with Cashier. If so, I'd be happy to put together a PR, maybe we could do something like this?

```php
<?php

namespace Laravel\Cashier;

use Stripe\CustomerSession as StripeCustomerSession;

trait Billable
{
    /**
     * Create a Stripe Customer Session for the billable model with pricing table support.
     *
     * @param  array  $options  Additional options for the Customer Session
     * @return \Stripe\CustomerSession
     * @throws \Stripe\Exception\ApiErrorException
     */
    public function createPricingTableSession(array $options = [])
    {
        // Ensure the model has a Stripe customer ID
        if (!$this->stripe_id) {
            $this->createAsStripeCustomer();
        }

        // Default configuration enables the pricing table component
        $defaultOptions = [
            'customer' => $this->stripe_id,
            'components' => [
                'pricing_table' => ['enabled' => true],
            ],
        ];

        // Merge user-provided options with defaults
        $sessionOptions = array_merge_recursive($defaultOptions, $options);

        // Create and return the Customer Session
        return StripeCustomerSession::create($sessionOptions);
    }
}
```

Then usage in the controller would look like:

```php
public function index(Request $request)
{
    $user = $request->user();
    
    // Generate the Customer Session
    $customerSession = $user->createPricingTableSession();

    // Pass the client secret to the frontend
    return inertia('Store/Index', [
        'customerSessionClientSecret' => $customerSession->client_secret,
    ]);
}
```

Let me know if this looks okay, if so I can put together a PR and I'd be happy to also add a section to the docs to explain the functionality.

**Comment by driesvints** [comment]
Thanks @virgildotcodes. Although your solution definitely seems smart I think right now we're not going to adopt it in Cashier.
