### ISSUE TITLE
Undefined error appears after updating to 15.0

### ISSUE THREAD

**Issue by mkismy** [laravel/cashier-stripe#1627]
### Cashier Stripe Version

15.0.0

### Laravel Version

10.38.2

### PHP Version

8.2.11

### Description

After updating cashier to 15.0.0 from 14.14.0, the error below started to appear.

```
 Call to undefined method Laravel\Cashier\Cashier::ignoreMigrations()
```

The only change I made to the codebase was adding this migration https://github.com/laravel/cashier-stripe/blob/15.x/UPGRADE.md#renamed-name-column-to-type

### Steps To Reproduce

- `composer install laravel/cashier`
- Add `Cashier::ignoreMigrations();` to register method on AppServiceProvider

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier-stripe/pull/1626 and the upgrade guide.
