### ISSUE TITLE
Embedded Checkout without a redirect not working 

### ISSUE THREAD

**Issue by lowbits** [laravel/cashier-stripe#1629]
### Cashier Stripe Version

14.14

### Laravel Version

10.10

### PHP Version

8.2

### Description

Currently, it is not possible to create an embedded checkout without a redirect. Cashier sets a default value for ``return_url`` when ``ui_mode = 'embedded'``. Stripe throws an error when `return_url` is set although `redirect_on_compltition` is set to `never`.  It expects to not have a return_url parameter. 

It should be possible to set ``ui_mode = 'embedded'`` and `` 'redirect_on_completion' => 'never'``.

A quick fix in `Checkout.php` would be:

```php

if (isset($data['ui_mode']) && $data['ui_mode'] === 'embedded') {
            $data['return_url'] = $sessionOptions['return_url'] ?? route('home');

            if(isset($data['redirect_on_completion']) && $data['redirect_on_completion'] === 'never') {
                unset($data['return_url']);
            }

        }

```

### Steps To Reproduce

$builder->checkout([
            'ui_mode' => 'embedded',
            'redirect_on_completion' => 'never',
        ]);

**Comment by driesvints** [comment]
Thanks for sending in the PR! Let's continue with that.
