### ISSUE TITLE
3D-Secure Card - Always Authenticate : Not Working when user try to Purchase a Subscription.

### ISSUE THREAD

**Issue by ShreyTandel09** [laravel/cashier-stripe#1644]
### Cashier Stripe Version

14.12

### Laravel Version

10.0

### PHP Version

8.1

### Description

When a user try to purchase the Subscription created through the cashier using a 3D secure Card. 
The payment Intent is created but the confirm payment is not created.
which causes the payment to fail.
The stripe is doesn't return the authenticate link to authenticate the payment and so the payment fail.  

### Steps To Reproduce

1. create subscription.
2. try purchase it with 3D secure card.
3. the payment intent is generated but confirm payment intent is no initiated.
4. So the payment fail in 3D secure card.

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!

**Comment by ShreyTandel09** [comment]
So i need to upgrade my Cashier version
