### ISSUE TITLE
Add support for quote

### ISSUE THREAD

**Issue by carlosaleaga88** [laravel/cashier-stripe#1652]
This feature should allow to manage quotes as has been done for invoices.
[How quotes work] (https://docs.stripe.com/quotes/overview)

**Comment by driesvints** [comment]
Thanks. right now we don't have plans to work on this ourselves. If you send in a PR we could look at the code involved and maybe merge in the feature. Thanks!

**Comment by carlosaleaga88** [comment]
Thank you @driesvints i will consider to send a PR.
