### ISSUE TITLE
Use of  anchorBillingCycleOn() for subscription checkout

### ISSUE THREAD

**Issue by ybert** [laravel/cashier-stripe#1658]
I would like to change anchor billing cycle date for a new subscription.

I tried this simple one : 
```php
$checkoutBuilder = $user
            ->newSubscription('default', ['price_yearly'])
            ->anchorBillingCycleOn(Carbon::tomorrow())
            ->checkout();
```

In the checkout  post data of stripe I can't see any subscription_data[billing_cycle_anchor] parameter as it's shown here : https://docs.stripe.com/payments/checkout/billing-cycle?ui=stripe-hosted#create-session

Am I missing something ?

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ybert** [comment]
@driesvints I think it is a bug as Cashier doesn't send the parameter at all to stripe.

**Comment by driesvints** [comment]
@ybert please fill out the issue template when reporting bugs
