### ISSUE TITLE
Method hasPaymentMethod returns false if Stripe Link is enabled

### ISSUE THREAD

**Issue by jonathanroy** [laravel/cashier-stripe#1663]
### Cashier Stripe Version

14

### Laravel Version

10

### PHP Version

8.3

### Description

When a client adds a payment method via the Stripe billing portal, he is prompted whether to enable Stripe Link (https://stripe.com/en-ca/payments/link).

If he accepts, the payment method works, but the method `hasPaymentMethod()` returns `false`.

However, the `hasDefaultPaymentMethod()` method works fine and returns `true`.

### Steps To Reproduce

Create a user
Redirect to the Stripe billing portal
Add a payment method and enable "Link"
Test: `$user->hasPaymentMethod()`

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
