### ISSUE TITLE
Bug finding payment method causing error on payment.blade.php

### ISSUE THREAD

**Issue by logtivity** [laravel/cashier-stripe#1665]
### Cashier Stripe Version

v15.2.2

### Laravel Version

10.46.0

### PHP Version

8.3.3

### Database Driver & Version

MySQL8

### Description

Hi there,

Just upgraded to Laravel 10/cashier v15.2.2 and had a report from a customer that the confirm payment page isn't working upon their renewal payment needing confirming due to their card being expired. The payment.blade.php view is not published/overridden  in our application.

Error message in console tab: 

```
vue.min.js:6 TypeError: Cannot read properties of undefined (reading 'element')
    at wn.configureStripeElements
```

Line of code causing the error:

```
// Create the Stripe element based on the currently selected payment method...
if (this.paymentMethod.element) {
```

After debugging I've found that it isn't setting their payment method in this line:

```
this.paymentMethod = this.paymentMethods.filter(
    paymentMethod => paymentMethod.type === type
)[0];
```

The reason for this is that the type variable is returning bacs_debit which for some reason was enabled.

Doing a console log of the following line:

```
const paymentMethodTypes = paymentIntent.payment_method_types;
```

returns ['bacs_debit', 'card', 'link']

As a result the following code snippet was looking for a payment method with a type of 'bacs_debit' and so returned null because it's only searching for paymentMethodTypes[0] which according to the above is 'bacs_debit'.

```
const type = this.paymentMethod === null
    ? ('{{ $paymentMethod }}' ? '{{ $paymentMethod }}' : paymentMethodTypes[0])
    : (((this.paymentIntent || {}).payment_method || {}).type ?? paymentMethodTypes[0]);

this.paymentMethod = this.paymentMethods.filter(
    paymentMethod => paymentMethod.type === type
)[0];
```

I have removed bacs_debit from our settings but think this could technically still cause an error if 'card' is the value of 'type' but the customer only has a 'link' payment method. Shouldn't the above search for any matching 'type' not just paymentMethodTypes[0])?

Cheers

Ralph

### Steps To Reproduce

Any cashier installation. Have multiple payment methods enabled. Test 3DS payment confirmation page with customer that doesn't have a payment method equal to the 'type' variable in the following payment.blade.php code snippet.

```
const type = this.paymentMethod === null
    ? ('{{ $paymentMethod }}' ? '{{ $paymentMethod }}' : paymentMethodTypes[0])
    : (((this.paymentIntent || {}).payment_method || {}).type ?? paymentMethodTypes[0]);

this.paymentMethod = this.paymentMethods.filter(
    paymentMethod => paymentMethod.type === type
)[0];
```

**Comment by driesvints** [comment]
Sorry, I didn't get to this this week. Will follow up next week.

**Comment by driesvints** [comment]
Hi there. Sorry it took this long for me to get back. Unfortunately the payment page currently does not support this payment method. We'd appreciate any PR's for it to be added! See https://laravel.com/docs/11.x/billing#handling-failed-payments

I'm not sure how Link should be integrated here, sorry.

**Comment by codewise-nicolas** [comment]
We came across this bug ourselves when running on test stripe mode.
Our payment methods where returning the array
```
"payment_method_types" => array:2 [▼
    0 => "acss_debit"
    1 => "card"
  ]
```
Exactly the problem from the original bug poster. The code was picking the 0th item and failing since the payment page doesnt support acss_debit.

The paymentMethods() function in payment.blade.php already handles filtering out the types that the page supports with the payment methods passed in from the payment intent. There is no need to re-filter them in the configurePayment code.

The fix we ended up with changing the logic to just using the first item of the list from paymentMethods().

Around line 241 of payment.blade.php
```
// If the previously set payment method isn't available anymore,
// update it to either the current one or the first available one...
if (this.paymentMethod === null || ! paymentMethodTypes.includes(this.paymentMethod.type)) {
    /*const type = this.paymentMethod === null
        ? ('{{ $paymentMethod }}' ? '{{ $paymentMethod }}' : paymentMethodTypes[0])
        : (((this.paymentIntent || {}).payment_method || {}).type ?? paymentMethodTypes[0]);

    this.paymentMethod = this.paymentMethods.filter(
        paymentMethod => paymentMethod.type === type
    )[0];*/

    //Grab the first payment method from the possible payment_method_types that this page supports.
    this.paymentMethod = this.paymentMethods[0];
}
```

I hope this helps other people coming from google search for this bug/problem.
