### ISSUE TITLE
Trait method 'allowPromotionCodes' will not be applied because it collides with 'PerformsCharges'

### ISSUE THREAD

**Issue by best-username** [laravel/cashier-stripe#1670]
### Cashier Stripe Version

15.3.2

### Laravel Version

10.48.4

### PHP Version

8.2

### Description

After upgrading from php 7.4 and laravel 8 to PHP 8.2 and laravel 8.2 I got next error in PHPStorm:

Trait method 'allowPromotionCodes' will not be applied because it collides with 'PerformsCharges'
<img width="828" alt="Screenshot 2024-04-19 at 16 30 43" src="https://github.com/laravel/cashier-stripe/assets/35339682/94a0e705-a583-4fed-a78e-8b125d418c3b">

### Steps To Reproduce

I did not changed anything in the code but error appeared

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!
