### ISSUE TITLE
Support for additional important Stripe signals for fraud detection

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1672]
Stripe fraud detection is important for the performance of Stripe's radar detection. Data such as billing address can be passed, but according to Stripe, the **IP address actually has some significance.** However, some applications, such as mine don't by default capture the user's IP address since my Laravel application serves as an API to a Nuxt JS front-end, so the ability to pass this through would be useful:

See https://docs.stripe.com/radar/integration#important-signals-to-send-to-stripe

**Comment by driesvints** [comment]
If you use Stripe Checkout this is done for you. I'm also not sure which actions in Cashier you want to add this to? You're always free to send in a PR we can have a look at.
