### ISSUE TITLE
Make card default for subscriptions via Stripe checkout

### ISSUE THREAD

**Issue by sts-ryan-holton** [laravel/cashier-stripe#1674]
Hi, this is a feature suggestion. I've just migrated over to the Stripe checkout flow. I'm using the new subscription method and sending the user to the Stripe checkout, but after filling in their payment methods it doesn't look like there's a default payment method attached so they likely won't be auto charged the next month?

**Comment by driesvints** [comment]
The payment method is set on the subscription directly which will be used for the recurring payments.

<img width="520" alt="Screenshot 2024-05-03 at 15 48 48" src="https://github.com/laravel/cashier-stripe/assets/594614/6b02fecc-e9e1-4960-b9ea-1cca7f6d7f54">

**Comment by sts-ryan-holton** [comment]
Ah right. So when calling `newSubscription()->checkout()` and sending the user to the Stripe checkout, upon entering payment details it will automatically charge that card each billing cycle?

**Comment by driesvints** [comment]
yeah, stripe adds that to the subscription rather than the customer.
