### ISSUE TITLE
Support for new usage Meters

### ISSUE THREAD

**Issue by obrunsmann** [laravel/cashier-stripe#1677]
There is a new feature called "Meters" which seems to be the new way to report usage to stripe:

https://docs.stripe.com/api/billing/meter-event

This is some sample implementation which I now use.
```php
<?php

$payload = [
    'event_name' => 'meter_name',
    'payload' => [
        'value' => $event->count,
        'stripe_customer_id' => $event->user->stripe_id,
    ],
];

$stripe = Cashier::stripe();
$stripe->billing->meterEvents->create($payload);
```

Usage records seems to get deprecated. For now we could implement a method like

```php

public function createMeterEvent(
  string $eventName,
  int $value = 1,
  string $eventPayloadKey = 'value',
  string $identifier = null,
  \DateTimeInterface|int|null $timestamp = null,
) : \Stripe\UsageRecord {}
```

**Comment by driesvints** [comment]
Yeah I'd love to see support for this in Cashier. Welcoming PR's!

**Comment by jigarhalani** [comment]
Is this deployed in new version of cashier?

**Comment by driesvints** [comment]
No, we haven't gotten a PR yet
