### ISSUE TITLE
paymentMethods not returning bank accounts

### ISSUE THREAD

**Issue by azazulia** [laravel/cashier-stripe#1681]
### Cashier Stripe Version

15.3.2

### Laravel Version

10.48.13

### PHP Version

8.3.4 

### Description

I'm attempting to pull all of a stripe user's associated payment methods, which include credit cards and ACH bank accounts. This method will return cards is called paymentMethods('card'), but will not return just bank accounts through paymentMethods('us_bank_account') or all associated payment methods using just paymentMethods(). 

### Steps To Reproduce

Call paymentMethods() on a billable model instance with both associated credit cards and associated bank accounts.

**Comment by driesvints** [comment]
Hi @azazulia. That's strange as I'd also expect this to return bank accounts. Unfortunately this isn't something I can help with as we use the https://docs.stripe.com/api/payment_methods/list endpoint behind the scenes. If that API endpoint isn't returning this then this is something for Stripe Support so please contact them. Please do let me know what they respond so I can help you and others better in the future. Thanks
