### ISSUE TITLE
Migrate from the legacy metered billing system to use the new stripe event meters

### ISSUE THREAD

**Issue by Bark-fa** [laravel/cashier-stripe#1687]
https://docs.stripe.com/api/billing/meter-event/object?lang=php

**Comment by driesvints** [comment]
As said in https://github.com/laravel/cashier-stripe/issues/1677, we'd love to receive PR's for this.

**Comment by Bark-fa** [comment]
we're writing an internal service for now, we'll try to integrate it into your codebase

**Comment by liamseys** [comment]
@Bark-fa Any news on this?

**Comment by Bark-fa** [comment]
@liamseys @driesvints PR issued
