### ISSUE TITLE
No tax is calculated for single charges or single charge checkouts

### ISSUE THREAD

**Issue by travisobregon** [laravel/cashier-stripe#1688]
The docs mention that [No tax is calculated for single charges or single charge checkouts.](https://laravel.com/docs/master/billing#tax-configuration:~:text=No%20tax%20is%20calculated%20for%20single%20charges%20or%20single%20charge%20checkouts.)

A method was added in this [PR](https://github.com/laravel/cashier-stripe/pull/1206) to prevent this. My understanding is that this was introduced as a temporary fix and is no longer needed?

**Comment by driesvints** [comment]
Errr I actually don't know 😅 Is that possible now? If so can you point to some Stripe docs about it?

**Comment by travisobregon** [comment]
I haven't tested myself, but a colleague was doing [automatic tax calculation using Stripe's API ](https://docs.stripe.com/api/checkout/sessions/create#create_checkout_session-automatic_tax)and they said it was working. For checkout, the docs mention one time purchases [here](https://docs.stripe.com/tax/checkout#:~:text=You%20can%20create%20sessions%20for%20one%20time).

**Comment by driesvints** [comment]
Thanks! I've sent in a PR to remove the limitation: https://github.com/laravel/cashier-stripe/pull/1690
