### ISSUE TITLE
Cashier routes should have "web" middleware

### ISSUE THREAD

**Issue by dansleboby** [laravel/cashier-stripe#1695]
### Cashier Stripe Version

15.4.1

### Laravel Version

11.15.0

### PHP Version

8.3.5

### Description

https://github.com/laravel/cashier-stripe/blob/15.x/src/CashierServiceProvider.php#L105

I think it should have like 
```
'middleware' => 'web'
```

In the group since it load the as web.php in laravel witch load this default middleware group

### Steps To Reproduce

Not required

**Comment by crynobone** [comment]
Hi there,

Thanks for reporting the problem you are encountering, but it looks like this is a question which may be better suited for a support channel. We only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repository you can try one of the following channels:

* [Laracasts Forums](https://laracasts.com/discuss)
* [Laravel.io Forums](https://laravel.io/forum)
* [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
* [Discord](https://discordapp.com/invite/KxwQuKb)
* [Larachat](https://larachat.co/)
* [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by dansleboby** [comment]
An inconsistency in the way middleware is applied across different Laravel packages. In the Laravel Passport package, middleware is included in the route definitions:

https://github.com/laravel/passport/blob/11.x/routes/web.php#L14C5-L14C27
```php
'middleware' => 'web',
```

and 

https://github.com/laravel/passport/blob/11.x/routes/web.php#L19C1-L19C26
```php
Route::middleware(['web', ...]);
```

However, in the Laravel Cashier package, specifically in the `registerRoutes` method, the middleware is missing:

https://github.com/laravel/cashier-stripe/blob/15.x/src/CashierServiceProvider.php#L102C24-L102C38

This is the issue I encountering. To maintain consistency and ensure proper functionality, it might be worth considering adding the `web` middleware in the Cashier routes. This would align it with the practices seen in other Laravel packages, such as Passport.
