### ISSUE TITLE
Stripe Webhook using /stripe/webhook returning 301 in stripe dashboard

### ISSUE THREAD

**Issue by mikefl1986** [laravel/cashier-stripe#1696]
### Cashier Stripe Version

14.7

### Laravel Version

9.19

### PHP Version

8.4

### Description

Using default Cashier webhook as per docs, {APP_URL}/stripe/webhook, 301 errors returned on all webhook attempts from Stripe when in production/live, works as intended in development using CLI

### Steps To Reproduce

N/A

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? If so, please open up a new issue and we'll help you out.

Thanks!
