### ISSUE TITLE
stripe/webhook post route points to Laravel\Paddle\WebhookConttroller

### ISSUE THREAD

**Issue by kikky7** [laravel/cashier-stripe#1710]
### Laravel Version

11.15

### PHP Version

8.3

### Description

I use Stripe, but have both cashier and cashier-paddle packages installed.
The webhook post route points to WebhookController in cashier-paddle:

POST stripe/webhook .................................................. cashier.webhook › Laravel\Paddle › WebhookController

Both packages can't work on same app by default?

Path is `stripe/webhook` for Stripe and Paddle? Why route name is not `stripe.webhook` and `paddle.webhook`? Because one overrides the other using the same route name.

### Steps To Reproduce

Install cashier and cashier-paddle.
Test webhooks via stripe-cli.

**Comment by driesvints** [comment]
You can't combine these packages.

**Comment by kikky7** [comment]
Challenge accepted
