### ISSUE TITLE
Use `createPreview` method

### ISSUE THREAD

**Issue by edalzell** [laravel/cashier-stripe#1716]
### Cashier Stripe Version

15.4.3

### Laravel Version

11.23.4

### PHP Version

8.3

### Description

I would like to use the `createPreview` invoice method but that's in a more current version of the Stripe PHP library.

Apologies if this has been asked/answered elsewhere, but when do you folks upgrade major versions of the PHP library?

### Steps To Reproduce

Try to call `createPreview`:

```php
Cashier::stripe(["stripe_version" => "2024-06-20"])->invoices->createPreview([
  "preview_mode" => "recurring",
  "subscription" => "sub_1123
]);
```

**Comment by driesvints** [comment]
Should be coming in Cashier v16 but unfortunately we cannot share an ETA atm. Hoping to do that sooner rather than later though.
