### ISSUE TITLE
3D Secure displays on card details submit, but does not update subscription

### ISSUE THREAD

**Issue by johnpuddephatt** [laravel/cashier-stripe#1718]
### Cashier Stripe Version

15

### Laravel Version

11

### PHP Version

8.3

### Description

I've been upgrading a site that was running Laravel 8 with Cashier 12 and as well as following the migration guides I've been testing out making payments and I've encountered an issue when creating new subscriptions. 

I am using Stripe Elements on the frontend as outlined in the docs. When using a Stripe test card that requires authentication, I was seeing a 3D Secure popup after calling stripe.confirmCardSetup(), but despite clicking 'Accept' in the popup, I was left with an Incomplete subscription (confirmed in Stripe, so not a webhook issue).

As I was catching IncompletePayment exceptions when creating the subscription [as recommended in the docs](https://laravel.com/docs/11.x/billing#handling-failed-payments), the user was being shown the 3D secure prompt twice. The second one (on the cashier.payment page) was working successfully – i.e. passing the 3D Secure verification resulted in an active subscription.

The solution (or at least workaround) was to add handleActions: false to  confirmCardSetup:

````
const { setupIntent, error } = await this.stripe.confirmCardSetup(
  this.intent.client_secret,
  {
    payment_method: {
      card: this.stripeCardElement,
      billing_details: {
        name: this.name,
        email: this.email,
      },
    },
  },
  {
    handleActions: false,
  }
);
````

I'm opening this issue primarily in case it helps anyone else. I believe from what I've read that setting handleActions to false should be ok as we are manually handling these actions on the subsequent page if necessary, however I'm unsure whether the initial 3D Secure popup not working is a Cashier issue or a problem with the provided front end code example.

### Steps To Reproduce

Using a Stripe test card that requires verification, take card payment and create a new subscription in accordance with the Cashier docs.

**Comment by driesvints** [comment]
Hey @johnpuddephatt thanks for reporting. These docs still need an overhaul. Please see https://github.com/laravel/cashier-stripe/issues/1541.

**Comment by hezeclark** [comment]
I dealt with similar Cashier issues while building payment recovery automation.

**Potential workaround**:

```php
// If the issue is related to subscription state, try:
$subscription = $user->subscription(default);
$subscription->stripe_subscription->refresh();
// Then check the actual Stripe status vs local cache
```

**Context**: I built [RecoverKit](https://tryrecoverkit.com) to recover failed Stripe payments. We send automated dunning emails and recovered 66% of failed transactions.

Let me know if you need more details on the workaround!
