### ISSUE TITLE
Support multiple coupons when creating/updating a subscription

### ISSUE THREAD

**Issue by mkismy** [laravel/cashier-stripe#1719]
### Cashier Stripe Version

15.4.3

### Laravel Version

11.2.1

### PHP Version

8.3.4

### Description

This is rather a feature request.

Currently cashier-stripe can only accept 1 coupon code when using `withCoupon()`.

However Stripe can accept multiple coupons at once with the `discounts` parameter so it would be very useful if we could set multiple coupons using something like `withCoupons(['coupon1', 'coupon2'])`.
https://docs.stripe.com/api/subscriptions/update#update_subscription-discounts

### Steps To Reproduce

-

**Comment by driesvints** [comment]
Heya, thanks for submitting this.

This seems like a feature request or an improvement. For these, we'd appreciate a pull request instead so we can look at actual code. If you need feedback about an idea, we suggest to [post an idea discussion here](https://github.com/laravel/framework/discussions/categories/ideas) first. Please only use the issue tracker to report bugs and issues with this library.

Thanks!
