### ISSUE TITLE
Multiple BIllable Models

### ISSUE THREAD

**Issue by jmurphy45** [laravel/cashier-stripe#1720]
### Cashier Stripe Version

15.4

### Laravel Version

11.9

### PHP Version

8.2

### Database Driver & Version

MYSQL 

### Description

No way to have multiple billable models besides the default user or other defined model in providers. Could I submit a pr to change the migrations and Manages Customer Trait to allow for multiple billable models?

### Steps To Reproduce

Follow Laravel doc for insulation.

**Comment by crynobone** [comment]
I don't think there much demand to have this feature for most applications but you are free to make PR.

**Comment by driesvints** [comment]
There were requests for this in the past but the migration path would be so big that we decided to hold off on this for the foreseeable future.
