### ISSUE TITLE
Illuminate\Database\Eloquent\MissingAttributeException The attribute [phone] either does not exist or was not retrieved for model

### ISSUE THREAD

**Issue by SlyDave** [laravel/cashier-stripe#1728]
### Cashier Stripe Version

15.2

### Laravel Version

11.23

### PHP Version

8.2

### Description

When using `Model::preventAccessingMissingAttributes();` and your Billable model doesn't contain `name` and/or `email` and/or `phone`

and you use the `syncStripeCustomerDetails` method

You get an exception

```
Illuminate\Database\Eloquent\MissingAttributeException
The attribute [phone] either does not exist or was not retrieved for model [App\Models\Vessel].
```

This is because `Concerns/ManagesCustomer::syncStripeCustomerDetails()` calls `$this->stripeName()`, `$this->stripeEmail()` and `$this->stripePhone()` these in turn are simple `$this->name ?? null` etc. the act of calling `$this->name` when name doesn't exist as an attribute on the model triggers the Exception.

I believe changing `$this->name` to `$this->hasAttribute('name') ? $this->name : null;` fixes the problem.

The work around is to override these methods and use the hasAttribute check, or simply return null if you do not implement those columns.

### Steps To Reproduce

* Enabled `Model::preventAccessingMissingAttributes();` in your project
* call  `$this->syncStripeCustomerDetails()` on a Billable model

**Comment by driesvints** [comment]
We'd appreciate a PR with these adjustments. Thanks!
