### ISSUE TITLE
Plans wrapper

### ISSUE THREAD

**Issue by rossjcooper** [laravel/cashier-stripe#329]
Has it ever been considered to add a wrapper in cashier for the Plans interface so we can get plans for example easily in our apps, say using a facade?
If so I would mind giving it a go in a PR

**Comment by Francismori7** [comment]
You can get the plans already very easily using Stripe's API (which of course is part of your application when using cashier)

**Comment by driesvints** [comment]
We're currently removing all Plans functionality from Cashier as it's been deprecated by Stripe in favor of the new Prices API.
