### ISSUE TITLE
Allow quantity of 0 when creating new subscriptions

### ISSUE THREAD

**Issue by VirtualDesignFactory** [laravel/cashier-stripe#373]
Would it be possible to update the buildPayLoad() function in SubscriptionBuilder.php to allow for quantities of 0 to be passed back? Stripe allows for subscriptions with a quantity of 0 to be created.

``` php
    /**
     * Build the payload for subscription creation.
     *
     * @return array
     */
    protected function buildPayload()
    {
        return array_filter([
            'plan' => $this->plan,
            'quantity' => $this->quantity,
            'coupon' => $this->coupon,
            'trial_end' => $this->getTrialEndForPayload(),
            'tax_percent' => $this->getTaxPercentageForPayload(),
            'metadata' => $this->metadata,
        ], 'strlen'); // Allows for 0 but not anything else evaluating to false
    }
```

**Comment by richartkeil** [comment]
+1

**Comment by flyrmyr** [comment]
Could really use this too... No movement after over a year and a half? Seems like a relatively straightforward PR, was it rejected?

**Comment by driesvints** [comment]
Subscriptions with a quantity of 0 don't really make sense. Stripe will generate 0 dollar invoices when this happens. It's best to only allow subscriptions with quantities.

**Comment by pierrocknroll** [comment]
Since it's possible to set 0 in the Stripe Dashboard, Cashier should handle it.

**Comment by millman2394** [comment]
I'm in a situation where I think it makes sense (but I suppose I could refactor how I'm doing things).

Basically, I'm doing price per "location" added. When they sign up, they won't have locations until they create themselves. They still enter payment info and subscribe to a price plan before accessing the app, but they don't have a location initially, so it would be quantity 0.

**Comment by driesvints** [comment]
I'm gonna revisit this soon after talking to Stripe directly about this.

**Comment by driesvints** [comment]
Realized that with all the latest changes from the past months this is now actually possible.
