### ISSUE TITLE
Calculate prorate amount

### ISSUE THREAD

**Issue by alexbowers** [laravel/cashier-stripe#45]
Is there any part of the current API which helps to calculate the prorate amount.

For example, if you are upgrading from a monthly to a yearly plan, then the difference gets paid immediately (Say, from $10 to $100), then there would be a $90 fee taken immediately. Is there a way already built in which calculates this based on Stripe plans?

**Comment by mateo2181** [comment]
there is a way to get the price with prorate before the user has subscribed to plan? I'm using cashier 9.3.5

**Comment by shanka12** [comment]
> This is how I solved this issue - hope this helps, open to better suggestions.
> 
> ```
> use Stripe\Invoice as StripeInvoice;
> ```
> 
> ```
>     /**
>      * @param  string  $plan_id
>      * @param  \App\User $user
>      * @return string
>      */
>     private function previewProrate(string $plan_id, $user) {
> 
>         $proration_date = time();
>         $subscription = $user->subscription('main')->asStripeSubscription();
> 
>         $items = [
>             [
>                 'id' => $subscription->items->data[0]->id,
>                 'plan' => $plan_id,
>             ],
>         ];
> 
>         $invoice = StripeInvoice::upcoming([
>             'customer' => $subscription->customer,
>             'subscription' => $subscription->id,
>             'subscription_items' => $items,
>             'subscription_proration_date' => $proration_date,
>         ],['api_key' => $user->getStripeKey()]);
> 
>         $cost = 0;
>         $current_prorations = [];
>         foreach ($invoice->lines->data as $line) {
>             if ($line->period->start == $proration_date) {
>                 array_push($current_prorations, $line);
>                 $cost += $line->amount;
>             }
>         }
> 
>         return number_format((float)$cost, 2, '.', '');
>     }
> ```

This is not work with during subscription cancel.
I got this error
```
Stripe\Exception\InvalidRequestException
You cannot preview the upcoming invoice for a canceled subscription.
```
