### ISSUE TITLE
subscription()->cancel() throws Exception

### ISSUE THREAD

**Issue by jopacicdev** [laravel/cashier-stripe#47]
I'm using `dev-master` to pull in Cashier, and when I try to cancel the subscription using
`$user->subscription()->cancel()` I get:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Call to a member function cancel() on a non-object
```

I also tried the `cancelNow()`, but not working.

Just note that when I use `~1.0` for Cashier, this works, but doesn't update `subscription_ends_at` field in the database.

**Comment by sayeed958** [comment]
I am using php api library V 2.2.0 
I am going to cancel subscription using following code:
$customer = \Stripe\Customer::retrieve({CUSTOMER_ID});
$customer->subscriptions->retrieve({SUBSCRIPTION_ID})->cancel();
But its throwing me following error.
Fatal error: Call to a member function retrieve() on a non-object ...
can you assist me, I need to update api library ?

**Comment by sayeed958** [comment]
For now, I have tried with new version of php library, but still not working , still throwing following error
    Fatal error: Call to a member function retrieve() on a non-object ...
