### ISSUE TITLE
Billable::cards does not return bank accounts

### ISSUE THREAD

**Issue by ColinLaws** [laravel/cashier-stripe#507]
As you can see below, when pulling the sources back it's being filtered by ['object' => 'card']. This means that it will not return bank accounts. The issue with this method is that it is consumed by the deleteCards() method. This means that bank accounts are not removed by the deleteCards method, and if a customer deletes an association to a bank account, and attempts to re-add it, an exception is thrown that the bank account already exists for that customer.

``` php
    $stripeCards = $this->asStripeCustomer()->sources->all(
        // Only cards are returned here, bank accounts are not pulled
        ['object' => 'card'] + $parameters
    );
```

**Comment by ColinLaws** [comment]
We should probably add something to Cashier for explicitly removing bank accounts. Add a bankAccounts method to the Billable trait, and add a deleteBankAccounts method.

**Comment by ColinLaws** [comment]
You could also remove the filtering and handle all objects as an ExternalAccount instead of handling them as the typical StripeCard class. You still have all the same data and functions available, they abstracted the concept of a payment method to an abstract class called ExternalAccount. The only difference is the data coming back from Stripe, but that can be parsed out using the object type of either 'card' or 'bank_account'. I hope I'm making some sense here.

**Comment by driesvints** [comment]
I don't really know how this problem can happen with Cashier itself as you only add cards and not bank accounts. Do you add bank accounts yourself through the Stripe API?

**Comment by driesvints** [comment]
Ah ok so this is more of a feature request. At the moment Cashier indeed only supports cards but I can see that bank accounts might be of use to more people as well. I'll mark this as a feature request. 

If you could manage to implement this in a clean way for the next major version then we could consider merging a PR in.

**Comment by driesvints** [comment]
Small update: we've moved to the Payment Methods API in Cashier. Support for different methods is planned by Stripe but not available atm: https://stripe.com/docs/payments/payment-methods

**Comment by ColinLaws** [comment]
It looks like whoever posted a question here may have taken it down, but I'll include this just to help anyone out in the future. Throughout Cashier, when interacting with multiple payment sources on a customer, Cashier specifies that the type of object to retrieve from the sources list is of type 'Card'.

Instead of pulling payment sources through Cashier, I wrote my own code in user land to pull a list of sources including bank accounts. Below is an example (in cashier\src\Billable.php) of the 'cards' function on the billable trait. Instead of using this method to pull payment sources, I wrote my own functions on my Billable model to pull bank accounts as well. 

```php
/**
     * Get a collection of the entity's cards.
     *
     * @param  array  $parameters
     * @return \Illuminate\Support\Collection
     */
    public function cards($parameters = [])
    {
        $cards = [];

        $parameters = array_merge(['limit' => 24], $parameters);

        $stripeCards = $this->asStripeCustomer()->sources->all(
            ['object' => 'card'] + $parameters
        );

        if (! is_null($stripeCards)) {
            foreach ($stripeCards->data as $card) {
                $cards[] = new Card($this, $card);
            }
        }

        return new Collection($cards);
    }
```

Also, thanks for the update @driesvints

**Comment by lsmith77** [comment]
FYI https://stripe.com/docs/payments/payment-methods was just updated.

following payment methods are not supported via the new API
* iDEAL
* SEPA Direct Debit

**Comment by driesvints** [comment]
@lsmith77 don't you mean "now" instead of "not"?

**Comment by lsmith77** [comment]
yes .. sorry for the typo. fixed it in the comment

**Comment by ZiIMoIN** [comment]
Would it be a clean way to add the possibility for other payment methods by passing the type as parameter to the functions?

For example in the [`paymentMethods`](https://github.com/laravel/cashier-stripe/blob/12.x/src/Concerns/ManagesPaymentMethods.php#L54) function replace ...
```php
$paymentMethods = StripePaymentMethod::all(
    ['customer' => $this->stripe_id, 'type' => 'card'] + $parameters,
    $this->stripeOptions()
);
```
... with ...
```php
$paymentMethods = StripePaymentMethod::all(
    ['customer' => $this->stripe_id] + $parameters + ['type' => 'card'],
    $this->stripeOptions()
);
```
so if you pass `['type' => 'sepa_debit']` it won't be replaced by type card.

Of course you would have to adjust the other functions as well.

**Comment by driesvints** [comment]
@ZiIMoIN I'm more thinking of passing a second parameter to that method in an upcoming release like so:

```php
    public function paymentMethods($parameters = [], $type = 'card')
```

But we'd need to make sure that the rest of the methods indeed would still work. Like `updateDefaultPaymentMethodFromStripe` & `fillPaymentMethodDetails`.

**Comment by simonhir** [comment]
@driesvints would try to implement these in the coming days did you start already with that?

**Comment by driesvints** [comment]
I'm happy to say that the next version of Cashier will support all possible payment methods. All current methods on a billable will support a `$type` parameter that can be passed to reference specific payment method types. 

At the moment we're still looking at updating the `payment.blade.php` view to also support more payment types.
