### ISSUE TITLE
Stripe Checkout 

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-stripe#637]
The new Stripe Checkout product provides an easy for to get started with payments without having to do a manual setup. The trade-off is that the payment process is completely styled and moved over to Stripe. 

~We'll only implement this in v10 if it gets a stable release soon. Otherwise can pick this up later.~ Checkout is out of beta so it'll probably make it into the new release.

https://stripe.com/docs/payments/checkout

**Comment by aldovincenti** [comment]
Thanks. Do you plan to implement this feature before September 14? As from that date, Cashier would not be available for a [business based in the EEA](https://stripe.com/docs/strong-customer-authentication), without this feature.

**Comment by driesvints** [comment]
@aldovincenti we're aware and it's the whole reason we're now working on v10. See the milestone: https://github.com/laravel/cashier/milestone/1

If Checkout gets a stable release soon it'll probably make it into v10 and otherwise before September.

**Comment by driesvints** [comment]
Checkout is out of beta so it'll probably make it into the new release.

**Comment by driesvints** [comment]
Progress: https://github.com/laravel/cashier/pull/652

**Comment by driesvints** [comment]
Since Stripe still hasn't updated their API with the necessary changes in order to let this move forward we're taking this out of the next release. We'll have to wait and see when Stripe makes the necessary changes listed in the PR.

**Comment by NeoMarine** [comment]
Is there a way for me to begin using Stripe Checkout with Laravel Cashier currently? It would save me a lot of time worrying about building an on-site form, handling the 3D secure stuff, etc.

You can quite easily redirect to the Stripe Checkout - it just appears there's just no webhook set for "checkout.session.completed" - is there a lot more that needs to be added?

It seems that perhaps if I added my own webhook for "checkout.session.completed" I would be able to then call something like _**$user->newSubscription('main', 'premium')->create($token);**_ - currently when I use the Stripe Checkout, it returns to the success_url as I define it, but no subscription is added.

I'd appreciate any help here. If I need to simply not use checkout then I suppose I have no choice, but it would be great...

**Comment by driesvints** [comment]
@NeoMarine No. Please see the concerns on the WIP PR for Checkout in Cashier on why Checkout is currently incompatible with Cashier: https://github.com/laravel/cashier/pull/652

**Comment by driesvints** [comment]
PR was closed for now. We can later pick up the work from the closed PR.

**Comment by cihantas** [comment]
Any chance this will ship in v12?

**Comment by driesvints** [comment]
At the moment we have no plans to work on this ourselves but we're still open to PRs.

**Comment by m1guelpf** [comment]
I managed to get Checkout _kind of_ working with Cashier (as in, it has been in production for months and it works, but I'm not 100% confident it works cause you never know). Here's a very short guide:

https://miguelpiedrafita.com/snippets/stripeCheckout/

**Comment by driesvints** [comment]
FYI, we've started working on this again: https://github.com/laravel/cashier-stripe/pull/1007

**Comment by mellester** [comment]
` public function succes(Request $request)
    {
        $session_id = $request->input('session_id');
        $stripe = new \Stripe\StripeClient(
            env("STRIPE_SECRET")
        );
        $session  = $stripe->checkout->sessions->retrieve(
            $session_id,
            []
        );
        $subscription  = $stripe->subscriptions->retrieve(
            $session['subscription'],
            []
        );

        //dump($user->subscription);
        //dump($subscription);
       // dd($session);
        $user = User::findOrFail($session['client_reference_id']);
        $user->newSubscription(
            'default', $subscription['plan']['id']
        )->create($subscription['default_payment_method']);
        //dump($user->subscriptions);
        return view('billing.succes');
    }`
This is how I got it to work.
Setting my 
`'success_url'  => url('/billing/succes?session_id={CHECKOUT_SESSION_ID}'), `

**Comment by blakekrone** [comment]
@mellester how are you preventing duplicate subscriptions in the stipe dashboard? I'm using checkout and added your success function but what happens is it creates a second subscription entry in stripe for the customer.

**Comment by driesvints** [comment]
@blakekrone @mellester can you please use a support forum so we can focus the discussion here at the PR at hand?

**Comment by driesvints** [comment]
PR is merged and will be in next week's release!

**Comment by komalraja** [comment]
I've added a stripe payment method and it works well. After adding the **SAME** stripe_key and stripe_secret to .env in 2 different projects. Both the projects gives this error

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'

```
I've not added any column to `subscription table`. 
The error is in this line of code.

  ```
 public function userDetails(Request $request)
     {
       $user = auth()->user();

       $paymentMethod = $request->paymentMethod;

       $user->update([
         'line1'        => $request->line1,
         'line2'        => $request->line2,
         'city'         => $request->city,
         'state'        => $request->state,
         'country'      => $request->country,
         'postal_code'  => $request->postal_code,
        ]);
        $plan = Plan::where('stripe_id', $request->plan)->first();
        // The error lies here
        $user->newSubscription($plan->stripe_name, $request->plan)->create($paymentMethod);
        return redirect()->route('products');
 }
  Could someone please help ?

Thanks

**Comment by driesvints** [comment]
@komalraja did you do this step when upgrading to v15? https://github.com/laravel/cashier-stripe/blob/15.x/UPGRADE.md#renamed-name-column-to-type

**Comment by komalraja** [comment]
@driesvints 
Thanks for your reply.
No, I didnt did this step before. But, now I've the added the below rename column to my **subscriptions table**

```
Schema::table('subscriptions', function (Blueprint $table) {
    $table->renameColumn('name', 'type');
});
```
I got this error:
```
   Illuminate\Database\QueryException 

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'subscriptions' (Connection: mysql, SQL: alter table `subscriptions` rename column `name` to `type`)
```
