### ISSUE TITLE
Stripe Subscription Schedules

### ISSUE THREAD

**Issue by ronlinet** [laravel/cashier-stripe#693]
Stripe has a subscription schedule feature which allows to charge a user for a predefined time frame. 
This is something that fits into booking systems, product rental or online education where users can pay for their products in advance. 
You have to ask stripe dev support to get access to these API calls because this feature is till in beta version but otherwise then that there should not be a reason to not have this in Cashier. 

![cashier](https://user-images.githubusercontent.com/2538315/60517623-009c5a00-9cae-11e9-92cf-9ac3942b9202.png)

Thank you for your work guys. 
Regards,

**Comment by ronlinet** [comment]
@driesvints I am in communication with Stripe dev guys to include this feature into standard Stripe API calls. I will keep you posted.

**Comment by ronlinet** [comment]
Just got a feedback from stripe support. The "Stripe Subscription Schedules" will be part of standard stripe API by the second half of 2019.

**Comment by mehrancodes** [comment]
I plan to use the scheduling on our educational app for installment payments. After that, I can help to bring this ability to the Cashier as well.

**Comment by driesvints** [comment]
I'm closing this as we don't have plans to implement this ourselves any time soon. If someone wants to PR this in a very clean that doesn't requires too many code changes we could consider it.

**Comment by Ronan-Lenor** [comment]
i'm just writing here some breadcrumbs of conception that need further work regarding Cashier.

```php
$user = Auth::user();
$stripe = Cashier::stripe();
$stripeSubscription = $user->subscription('default')->asStripeSubscription();

if ($stripeSubscription->schedule != null)
{
    // Cancel a Schedule at the end of the (Last Phase) billing period
    $stripe->subscriptionSchedules->update($stripeSubscription->schedule, ['end_behavior' => 'cancel']);

    // cancelAt($endsAt) case would require to do the same thing than above + go through each Phases to :
    // 1. find the one that have its range start/end date that match the $endsAt
    // 2. change the end_date attritube
    // 3. remove all Phases beyond the modified Phase

    // Resuming a Schedule
    $stripe->subscriptionSchedules->update($stripeSubscription->schedule, ['end_behavior' => 'release']);

    // Cancel now
    $stripe->subscriptionSchedules->cancel($stripeSubscription->schedule);
    // or (no resume possible once released)
    $stripe->subscriptionSchedules->release($stripeSubscription->schedule);
    $user->subscription('default')->cancelNow();
}

// other method to review : ...GracePeriod
```

The advantage of schedule management is that new methods could be developed later to facilitate the process of downgrading (& upgrading) a subscription at the end of its renewal period.
