### ISSUE TITLE
Update Customer Information

### ISSUE THREAD

**Issue by aaronhuisinga** [laravel/cashier-stripe#9]
Cashier now nearly has all the functionality that I've needed to use where I could stop needing to use the Stripe library. However, there is no way currently to edit customer information, or update/change their credit card. Both of these methods are a part of the Stripe API, so Cashier would just need some new classes to perform them.

The Stripe API support both updating the card information (such as the customer name) or removing and adding a new card. I suppose this would have to be taken into account when creating and naming different methods.

I'm not sure how everyone thinks the naming conventions would go for them, but it could be something along the lines of:

``` php
// Update existing card information
$user->updateCard(['name' => $user->name]);

// Create new card. 
// Bool for removing other card or setting this as default payment method?
$user->newCard($creditCardToken, true);

// Fetch the User's billing information
$user->getBillingInfo();

// Update the User's billing information
$user->updateBillingInfo(['name' => $user->name]);
```

These are all pretty rough proposals, but the added functionality would be great!

**Comment by DannyFeliz** [comment]
+1
