### ISSUE TITLE
Check into alternative card setup

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-stripe#929]
In some cases, double card confirmation is requested through the current flow as documented. The current way is needed to prevent additional SCA checks etc on subscriptions when recurring charges are made. 

I know some people have been investigating this as well so appreciating feedback here.

**Comment by martinbean** [comment]
Hi, @driesvints. I’ve integrated Stripe and subscriptions a few times outside of Cashier.

When [collecting card details on the front-end using Stripe Elements][1], Stripe uses the `createPaymentMethod` to, well, create a payment method 😄 That payment method’s then used to [create a subscription][2]. The subscription at this point can either be `active`, or `incomplete` if the payment requires additional authorisation. Stripe says to [check the status of the latest invoice payment intent][3].

What I’ve done in the past is, when I’m submitting the payment method ID from the front-end to an endpoint that calls `$user->newSubscription()`, to check if an error is thrown from the endpoint and then use that to trigger `confirmCardPayment` in my Stripe card element. But this error message isn’t easily distinguishable from other errors without doing some nasty string comparison on the error message, and obviously this would then fail if the error message every changes.

I think what would be better would be to just return the subscription from the `newSubscription` method whether it’s `active` or `incomplete`, and let developers to inspect the subscription’s latest invoice status to determine whether they need to trigger additional authorisation using `confirmCardPayment`. The developer would also have the subscription object to hand to do any redirects or whatever once the subscription’s been activated. This would also have the caveat that the a Stripe customer would need to be created before `newSubscription` is called, as the payment method needs attaching to the customer before a subscription is created for them.

[1]: https://stripe.com/docs/billing/subscriptions/cards#web-collect-card-details
[2]: https://stripe.com/docs/billing/subscriptions/cards#create-subscription-code
[3]: https://stripe.com/docs/billing/subscriptions/cards#manage-sub-status

**Comment by driesvints** [comment]
@martinbean heya, sorry for keeping you waiting for 2 years 😅 We haven't had many reports anymore in the last two years about this payment method flow so unsure if this is still an issue.

> I think what would be better would be to just return the subscription from the newSubscription method whether it’s active or incomplete

Right now, when a payment fails when it's incomplete, an `IncompletePayment` exception gets thrown. This exception contains a `Payment` object that wraps a payment intent. This payment intent from stripe contains a reference to the invoice which subsequently  contains a reference to the subscription it belongs to. So technically it's possible to retrieve the subscription if needed. We could make this easier though with some better API's.

> This would also have the caveat that the a Stripe customer would need to be created before newSubscription is called, as the payment method needs attaching to the customer before a subscription is created for them.

This is already happening when you pass the payment method to the `create` method of the subscription builder. A customer will be created and the payment method will be attached as their default.

I'm going to close this one but feel free to follow up with any more remarks and questions if you have them 👍

**Comment by martinbean** [comment]
@driesvints Hey! In all honestly, I’ve forgotten the context around this and what problem I was having or I was trying to solve. It’s become a bit of a non-issue as I’ve started just using Stripe’s hosted Checkout for subscriptions and one-off purchases instead of building my own Elements-based payment pages.

Thanks for following up after all this time nonetheless, though!

**Comment by driesvints** [comment]
Re-opening this one as I've recently spoken to Stripe Support about using setup intents vs confirming payment intents for setting up card for future payments. I'm going to investigate what alternative flows would be possible.

Related: https://stripe.com/docs/api/subscriptions/create#create_subscription-payment_settings-save_default_payment_method

**Comment by mehmetcansahin** [comment]
@driesvints I have the same problem(0€ amount) in the subscription process. Stripe recommends https://stripe.com/docs/payments/save-during-payment-cards-only as an alternative way. How can we solve this on cashier side.

**Comment by driesvints** [comment]
@mehmetcansahin that guide seems to not be recommended by Stripe anymore (See the note on top).

**Comment by mehmetcansahin** [comment]
Interesting stripe support suggested this to me. So how can I solve the 0€ amount problem with 3d secure?

**Comment by driesvints** [comment]
There's a link in that note to the new guide: https://stripe.com/docs/payments/save-during-payment

**Comment by driesvints** [comment]
I've been looking into https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements&card-or-payment-element=payment-element#create-subscription which basically describes the scenario to first create the subscription as incomplete, then collect payment details and use that to pay and activate the subscription.

However, I find this counterintuitive. It's more reasonable to first collect payment details, save that to the customer and use that to pay for the subscription (which we're doing now in Spark). 

I think for now, I'm going to close this one. The €0 amount isn't a real issue anyway as you're simple authenticating the card to be used for future off session payments.

**Comment by driesvints** [comment]
Re-opening this again because it does seem that it'd be wise to follow what Stripe's doing here. This will require a thorough exercise to see what the consequences are for Cashier and Spark.

**Comment by driesvints** [comment]
Moved this to an internal backlog.

**Comment by mpapado3** [comment]
Hello, is there any update on this issue?
I am having exactly the same problem, product has the correct price, bank is charged with correct amount and transferred to Stripe, but the 3D notification shows 0 as price.
When contacted Stripe support they told me that this is because the card is saved before the charge is implemented.

I have a live site which faces this problem.

**Comment by driesvints** [comment]
@mpapado3 the new version of Cashier Stripe should not have this issue. If you create a new subscription then it will start a new subscription as `incomplete`, then confirm the payment intent on it. However, it may be that older subscriptions from before the change still have this.

**Comment by driesvints** [comment]
Actually, this is more of a documentation issue. When starting new subscriptions you should adopt a flow to first create the subscription and only then attach a card. Cashier already provides to do this.

See https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements#create-subscription for more info.

**Comment by ralphmorris** [comment]
Hey @driesvints, we're experiencing this issue as well as we're using createSetupIntent and then confirmCardSetup to store the payment method, followed by creating the subscription as per the docs.

Is the documentation going to be updated to include the steps for creating the subscription first with an `incomplete` status and then attaching a payment method after? I'm not sure how this could be achieved cleanly in our situation. We currently take card details on the registration page and only at the point of registration creating the customer, subscription etc. I'm not sure how to create a subscription without a currently authenticated user.

Cheers

**Comment by driesvints** [comment]
@ralphmorris I still plan to tackle this at some point but unfortunately haven't found the time yet. Would appreciate a PR to kickstart it.

**Comment by ralphmorris** [comment]
Hey @driesvints Thanks for the reply here. I'm going to have a think about the best way to approach it for us. I spoke to Stripe support and they said the same thing as you above:

> This is expected behaviour if you're using a SetupIntent.

> We would never recommend integrating this way where you complete a SetupIntent and then immediately do a payment(in your case payment of the first invoice of a Subscription). It causes issues/confusion like the one you're raising here. It also can lead to the customer having to do 3D Secure twice, as you also mention. You should only use SetupIntents for use cases where you're saving a card without payment and then charging it hours/days later.

> The recommended way to integrate, which will also resolve the issue you face since the 3D Secure action will be run on the actual initial Invoice payment's amount, is to create the Subscription and then use the latest_invoice.payment_intent on the frontend to complete the first payment and save the payment method all in one call. See the guide https://stripe.com/docs/billing/subscriptions/build-subscriptions?ui=elements and re-design your integration in line with that instead.

I'm not sure that will work for our current signup process as we take payment on the registration page so we may have to weigh up refactoring it to create the subscription and then give users a second step to then make payment.

Cheers

**Comment by clementmas** [comment]
> We would never recommend integrating this way where you complete a SetupIntent and then immediately do a payment

That's what the Cashier documentation recommends.

Some of my clients are confused when they see a price of 0€ so they back out.

@driesvints can we reopen this issue to discuss the PR needed to fix this?

**Comment by driesvints** [comment]
I’m still planning on looking into this as soon as I get the chance.

**Comment by michaelanthonyfeather** [comment]
Thankyou @clementmas, you are a life saver. I can confirm that your method works. This definitely needs mentioning in Cashier's documentation.
