### ISSUE TITLE
Update Stripe SDK to new recommended syntax

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-stripe#939]
https://github.com/stripe/stripe-php/pull/771

https://github.com/stripe/stripe-php/wiki/Migration-to-StripeClient-and-services-in-7.33.0

**Comment by sonja-turo** [comment]
Was thinking of tackling this, but the Stripe documentation still uses the old way, so I'm wondering if this new model is an encouraged thing from Stripe? (although I do think it is better)

**Comment by driesvints** [comment]
I'd rather tackle this one myself at some point as it's a pretty delicate one. Also: not sure what you mean but I see the new syntax in their API docs.

**Comment by sonja-turo** [comment]
That's fine. Oddly, their API docs show the new syntax, but their standard docs show the old way (which was what I was initially referencing).
