### ISSUE TITLE
Refactor internals to products and prices

### ISSUE THREAD

**Issue by driesvints** [laravel/cashier-stripe#956]
Stripe has rolled out their new products and prices APIs which replace the concept of subscription plans. Even though things will continue to keep on working properly, it's probably best that we rewrite the internals eventually and update the docs.

Also check for webhook events (switch from plan key to price key).

Rename stripe_plan database columns to stripe_price?

Docs: https://stripe.com/docs/billing/prices-guide
Migration guide: https://stripe.com/docs/billing/migration/migrating-prices

Multi-plan -> multi-product: https://stripe.com/docs/billing/subscriptions/multiple-products
Replace `$stripeSubscription->plan` and `$stripeSubscription->quantity` calls
Remove subscription quantity & stripe_plan columns?

**Comment by driesvints** [comment]
Already did a small update for the docs: https://github.com/laravel/docs/pull/6165

Atm this issue isn't urgent since everything will keep on working as is. If we ever do a new major version again we can revisit.

**Comment by sebdesign** [comment]
@driesvints I'm using products and prices for a new project, and I'm willing to implement these features. Is there any plan on how should this refactored?

I have defined a price with `metered` billing which means when I create a subscription I need to pass an empty array for the `$plans` parameter, and and manually pass a `price` instead of a `plan` without a `quantity` to the `$subscriptionOptions`.

```php
$user->newSubscription('default', [])->create($paymentMethod, [], [
    'items' => [
        [
            'price' => 'price_HGd7M3DV3IMXkC',
        ],
    ],
]);
```

Now this fails because when Cashier is creating the subscription item in the database it needs the `quantity`, so I've override the `subscription_items` migration like this:

```php
$table->integer('quantity')->nullable();
```

**Comment by driesvints** [comment]
@sebdesign this PR is only as a reminder to rename some of the internals from "plans" to "prices", variable names, method arguments etc. I don't think any big changes are needed as everything already works. 

Metered billing in general isn't supported by Cashier yet and has its own separate issues here: https://github.com/laravel/cashier-stripe/issues/555

**Comment by fkraefft** [comment]
> @driesvints I'm using products and prices for a new project, and I'm willing to implement these features. Is there any plan on how should this refactored?
> 
> I have defined a price with `metered` billing which means when I create a subscription I need to pass an empty array for the `$plans` parameter, and and manually pass a `price` instead of a `plan` without a `quantity` to the `$subscriptionOptions`.
> 
> ```
> $user->newSubscription('default', [])->create($paymentMethod, [], [
>     'items' => [
>         [
>             'price' => 'price_HGd7M3DV3IMXkC',
>         ],
>     ],
> ]);
> ```
> 
> Now this fails because when Cashier is creating the subscription item in the database it needs the `quantity`, so I've override the `subscription_items` migration like this:
> 
> ```
> $table->integer('quantity')->nullable();
> ```

Can you elaborate how did you manage to make the metered billing? Thanks!

**Comment by sebdesign** [comment]
@fkraefft I used this guide to get started: https://stripe.com/docs/billing/subscriptions/metered
In step 6 I added the snippet above to create the subscription.

**Comment by benjamindoe** [comment]
Just a small question relating to this, will ad-hoc pricing also be considered during the refactor? It essentially just creates an archived price on a specified product. You can currently do this just fine with the Stripe SDK but it was be nice to just be able to use the `swap` method on a subscription.

This is a useful feature when either migrating to Stripe from another payment system or migration from single plan subscriptions to multiplan subscriptions. I'm sure there are other use cases for this but only these come to mind.

https://stripe.com/docs/billing/prices-guide#ad-hoc

**Comment by driesvints** [comment]
@benjamindoe out of scope for this PR but you can technically already do that. Just overwrite the `items` key through the `$subscriptionOptions` argument:

```php
$user->newSubscription('default', [])->create($paymentMethod, [], [
     'items' => [['price_data' => ['unit_amount' => 1000, 'currency' => 'USD']]],
]);
```

**Comment by benjamindoe** [comment]
True, although it's not the most elegant solution. I'll create a fresh issue.
