### ISSUE TITLE
Trying to get property 'payment_intent' of non-object

### ISSUE THREAD

**Issue by jeffreyzant** [laravel/cashier-stripe#958]
- Cashier Version: 12.0.0
- Laravel Version: 6.18.18
- PHP Version: 7.4.6

### Description:
When swapping a subscription without a latest_invoice the swap errors. When creating a subscription with proration_behavior => none there is no first invoice.

```
  ErrorException  : Trying to get property 'payment_intent' of non-object

  at /vendor/laravel/cashier/src/Subscription.php:602
    598|         $this->items()->whereNotIn('stripe_plan', $items->pluck('plan')->filter())->delete();
    599| 
    600|         $this->unsetRelation('items');
    601| 
  > 602|         if ($stripeSubscription->latest_invoice->payment_intent) {
    603|             (new Payment(
    604|                 $stripeSubscription->latest_invoice->payment_intent
    605|             ))->validate();
    606|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
      vendor/laravel/cashier/src/Subscription.php:602

  2   Laravel\Cashier\Subscription::swap()
      app/Console/Commands/StripeUpdateCommand.php:75

```

### Steps To Reproduce:
Looks like the solution would be to alter the if statement to:

 ```
if ($stripeSubscription->latest_invoice && $stripeSubscription->latest_invoice->payment_intent) {
```

**Comment by driesvints** [comment]
I can't seem to replicate this with the following test (which passes for me):

```php
    public function test_no_prorate_on_subscription_create()
    {
        $user = $this->createCustomer('no_prorate_on_subscription_create');

        $subscription = $user->newSubscription('main', static::$planId)->noProrate()->create('pm_card_visa');

        $this->assertEquals(static::$planId, $subscription->stripe_plan);
    }
```

We'll need some more info here why the error is triggered. Afaik there's always a latest invoice. Please share the exact code needed to recreate this as well as how you've set up your subscription and prices.

**Comment by jeffreyzant** [comment]
I'm using the following code to create the subscription:
```
$client->newSubscription('default', $stripePlan)->create(null, [], [
    'collection_method' => 'send_invoice',
    'days_until_due' => 30,
    'backdate_start_date' => Carbon::now()->addDays(90)->subYear()->startOfDay()->unix(),
    'billing_cycle_anchor' => Carbon::now()->addDays(90)->startOfDay()->unix(),
    'proration_behavior' => 'none',
]);
```

Afterwards i'm trying to swap the subscription like so:
```
$client->subscription('default')->swap(self::ENTERPRISE_YEARLY);
```

Both plans are a standard yearly pricing configuration.

**Comment by driesvints** [comment]
Ah okay, you said:

> When creating a subscription with proration_behavior => none there is no first invoice.

So I tested that and that wasn't the case (there was one). I'll try again with the info from above.

**Comment by driesvints** [comment]
I get: 

> Stripe\Exception\InvalidRequestException: billing_cycle_anchor cannot be later than next natural billing date (1594546977) for plan

So we'll need even more info on how exactly you set up the plans. Please share all the data you used to set them up.

**Comment by jeffreyzant** [comment]
Did you use a yearly or monthly stripe plan? For testing im adding the 90 days to the billing_cycle_anchor. When you are using a monthly plan this won't work, because it then should be within the month. You could also set the addDays to 5 or so.

![image](https://user-images.githubusercontent.com/913317/84489592-34e00f00-aca2-11ea-8a22-8af9c3adfb63.png)

**Comment by driesvints** [comment]
Think I cracked it: https://github.com/laravel/cashier/pull/959

Thanks for reporting!

**Comment by jeffreyzant** [comment]
I've tried the code in my situation and it indeed works! Thanks for the quick response and i'll wait for it to be merged! :)

**Comment by jeffreyzant** [comment]
I've just continued my developing and saw another issue arising. There is still an error when using:

```
$client->stripeSubscription('default')->swap(self::ENTERPRISE_YEARLY, [
    'proration_behavior' => 'always_invoice',
]);
```

```
 Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Laravel\Cashier\Payment::__construct() must be an instance of Stripe\PaymentIntent, null given, called in app/StripeSubscription.php on line 78

  at vendor/laravel/cashier/src/Payment.php:24
    20|      *
    21|      * @param  \Stripe\PaymentIntent  $paymentIntent
    22|      * @return void
    23|      */
  > 24|     public function __construct(StripePaymentIntent $paymentIntent)
    25|     {
    26|         $this->paymentIntent = $paymentIntent;
    27|     }
    28| 

  Exception trace:

  1   Laravel\Cashier\Payment::__construct()
      app/StripeSubscription.php:78

  2   App\StripeSubscription::swap()
      app/Console/Commands/StripeUpdateCommand.php:81
```

**Comment by jeffreyzant** [comment]
I'm guessing the old check isn't wrong and should be combined with the new check. As there is a last invoice when using the always_invoice method. But this one does not have a payment_intent yet.

```
if ($this->hasIncompletePayment() && $stripeSubscription->latest_invoice->payment_intent) {
```

**Comment by driesvints** [comment]
I think a lot of the problems that are surfacing here is because of Stripe's new "collection_method: send_invoice" method which we don't officially support yet. But it's good that we're tackling these now. 

I've sent a support question to Stripe to ask about this particular case because it's weird to me that the invoice after this scenario is in "draft" and that the subscription is "past due".

**Comment by driesvints** [comment]
Gonna re-open this until Stripe has gotten back to me.

**Comment by driesvints** [comment]
Just pasting in here the failing test for this for future reference:

```php
    /** @group NoProrate */
    public function test_always_invoice_after_no_prorate()
    {
        $user = $this->createCustomer('always_invoice_after_no_prorate');

        $subscription = $user->newSubscription('main', static::$planId)->noProrate()->create('pm_card_visa', [], [
            'collection_method' => 'send_invoice',
            'days_until_due' => 30,
            'backdate_start_date' => Carbon::now()->addDays(5)->subYear()->startOfDay()->unix(),
            'billing_cycle_anchor' => Carbon::now()->addDays(5)->startOfDay()->unix(),
        ]);

        $this->assertEquals(static::$planId, $subscription->stripe_plan);
        $this->assertTrue($subscription->active());

        $subscription = $subscription->swapAndInvoice(self::$otherPlanId);

        $this->assertEquals(static::$otherPlanId, $subscription->stripe_plan);
        $this->assertTrue($subscription->active());
    }
```

**Comment by driesvints** [comment]
Stripe confirmed the behavior is a bug. Moved this to "needs more info" until Stripe has gotten back to me with a fix.

**Comment by driesvints** [comment]
Stripe has fixed the above behavior now. I've added a new test to cover this scenario: https://github.com/laravel/cashier-stripe/commit/3347f933bf63e021bf710e517cf244a309c009ed

Basically it boils down that any invoicing is delayed because of the draft invoice from the beginning of the subscription.
