### ISSUE TITLE
Allow cancelNow() to prorate

### ISSUE THREAD

**Issue by tpavlek** [laravel/cashier-stripe#974]
When calling `cancelNow()` it would seem, at least from our use case that you _always_ want to prorate the remaining time on the subscription, but it does not take any options.

Is there a design reason why we can't pass a `$prorate` or `$refund` option to `cancelNow()` (or have something like `cancelNowWithProration()`)?

Would a pull request for something like this be something the team is amenable to? Don't want to build it if it'll be rejected out of hand.

**Comment by driesvints** [comment]
I'll pr something
