### ISSUE TITLE
No such PaymentMethod: tok_1H7fkhAll20s9AXvm4QL6Xw9

### ISSUE THREAD

**Issue by Nayan20** [laravel/cashier-stripe#977]
- Cashier Version: ^12.1
- Laravel Version: 6.2
- PHP Version: 7.2
- Database Driver & Version:

### Description:
Hello

I am using stripe with Laravel Cachier.

I got the "No such PaymentMethod: tok_1H7fkhAll20s9AXvm4QL6Xw9" issue.

Could any one let me know the solutions of this issue.

Let me know if any query

Thanks
Nayan

**Comment by driesvints** [comment]
A `tok_` key indicates the old token based API. You need to migrate to the new payment method API.
