### ISSUE TITLE
Cashier Pagseguro - Brazilian Payments Gateway

### ISSUE THREAD

**Issue by fredroo** [laravel/cashier-stripe#978]
Hello, in Brazil I need to use this project but don't use because don't have a payment method called in Brazil by Boleto

if i create a project called by cashier-pagseguro i can send for someone with admin access to put here in Laravel official repository as a Brazilian option to many user can use too?

can ask for the community this project can be very useful

**Comment by driesvints** [comment]
Heya sorry but we have no plans for that. Feel free to release it as a package.

**Comment by fredroo** [comment]
as a package contribution to Laravel repositories, i can't? only in my personal account? You mean this?

**Comment by driesvints** [comment]
Yes

**Comment by fredroo** [comment]
ok thanks
