### ISSUE TITLE
Update billing details for an existing card

### ISSUE THREAD

**Issue by DevelTwist** [laravel/cashier-stripe#979]
Hi, I need to know if the update payment method for cashier is implemented.

https://stripe.com/docs/api/payment_methods/update this API Call.

I was reviewing the official documentation and saw nothing about it, I would appreciate your help.

https://prnt.sc/tq73zg

**Comment by driesvints** [comment]
Every payment method has a method called `asStripePaymentMethod` to access the underlying Stripe object. If you feel the docs can be improved, we're open to prs. Thanks.

**Comment by DevelTwist** [comment]
Thanks @driesvints but Sorry, I got an error trying to implement it.

https://prnt.sc/tqndlg -> **Code implementation**

https://prnt.sc/tqneqi-> **Api test**

This is my log, It does not detect the API key. The payment method returns it to me without any problem.

[laravel.log](https://github.com/laravel/cashier-stripe/files/4995992/laravel.log)

**Comment by driesvints** [comment]
@DevelTwist please try a support channel. This issue tracker is only for reporting bugs, sorry.
