### ISSUE TITLE
Support to add payment method by attach source Plaid - Stripe

### ISSUE THREAD

**Issue by DevelTwist** [laravel/cashier-stripe#980]
Hello recently I have been adding ACH payment method via Plaid, this in order to add a verified bank account instantly, however by using the `addPaymentMethod` to add the token that returns plaid for example `ba_1HCthnAUQkF4Bji6egcGBfDN` does not take it as valid.

I had to add it using the api method 
https://stripe.com/docs/api/sources/attach

The detail is when I use the `paymentMethods`  method to list all of the payment methods associated with a user, it does not list this added method. 

![p1](https://user-images.githubusercontent.com/22015495/89551307-d1251e80-d7d8-11ea-8bb0-3c02983e6bba.png)
![p2](https://user-images.githubusercontent.com/22015495/89551314-d3877880-d7d8-11ea-9f28-316b419cb648.png)
![p3](https://user-images.githubusercontent.com/22015495/89551328-d6826900-d7d8-11ea-8ae8-399a2a9790ef.png)

**Comment by driesvints** [comment]
ACH isn't supported yet by Stripe's Payment Methods API so we can't support it in Cashier yet. We'll need to wait until Stripe rolls out support for it.

https://stripe.com/docs/payments/payment-methods#supported-payment-methods

In the meantime you'll have to work around this yourself I'm afraid.

**Comment by DevelTwist** [comment]
Ok thanks.
