### ISSUE TITLE
3D secure problems with off_session=true 

### ISSUE THREAD

**Issue by garygreen** [laravel/cashier-stripe#988]
Currently cashier forces [`off_session = true`](https://github.com/laravel/cashier-stripe/blob/12.x/src/SubscriptionBuilder.php#L326) which is causing issues with 3D Secure payments for subscription creations when user is on site.

According to Stripe, if you set `off_session=true` this means you are telling Stripe the *initial* subscription setup is being conducted with the user offsite. This means Stripe will favour non-request of 3D secure checks, unless absolutely required.

This has been confirmed by one of Stripe's senior engineers and they recommend to not use `off_session=true` if the user is on site when the subscription is being created.

## Steps to reproduce

This can be replicated by having your radar rules configured to require 3d secure (see below screenshot) and using a "supported" 3d card testing number (4000000000003055) with `off_session=true` - you'll notice it won't request for 3d secure. However it WILL request for it if `off_session=false`

![image](https://user-images.githubusercontent.com/1702638/91866666-ab215b80-ec6a-11ea-9abe-a6878256f1e0.png)

## Solution

Could we have a way of configuring this value in Cashier? Would it make sense to have the default value to be `off_session=false` ? I think there maybe some overlap/confusion between `setup_future_usage = off_session` on payment intents.

**Comment by driesvints** [comment]
Can you please resubmit this with a filled in issue template?

**Comment by garygreen** [comment]
Are you serious? I did use the template. What did I miss?

**Comment by driesvints** [comment]
https://github.com/laravel/cashier-stripe/issues/new?template=1_Bug_report.md

<img width="955" alt="Screenshot 2020-09-01 at 16 54 48" src="https://user-images.githubusercontent.com/594614/91867354-dd838680-ec73-11ea-9f40-454cc3a1ab22.png">

**Comment by garygreen** [comment]
There https://github.com/laravel/cashier-stripe/issues/989

**Comment by driesvints** [comment]
thanks
