### ISSUE TITLE
invoiceFor() error when passing quantity

### ISSUE THREAD

**Issue by bradders** [laravel/cashier-stripe#993]
- Cashier Version: 10.0
- Laravel Version: 7.10.3
- PHP Version: 7.4.10
- Database Driver & Version: MySql

### Description:
Following along with the docs, I'm trying to use `invoiceFor()` to create a charge. If I pass in only the description and amount, it works. But as soon as I pass in a third parameter with quantity I get the following error: `You may only specify one of these parameters: amount, quantity.` This even happens when I use the exact code from the docs.

### Steps To Reproduce:
This creates a charge in Stripe:
```
Auth::user()->invoiceFor('Stickers', 500);
```

This throws an error:
```
Auth::user()->invoiceFor('Stickers', 500, ['quantity' => 50]);
```

**Comment by driesvints** [comment]
Hey there,

Unfortunately we don't support this version anymore. Please check out [our support policy](https://laravel.com/docs/releases) on which versions we are currently supporting. Can you please try to upgrade to the latest version and see if your problem persists? We'll help you out and re-open this issue if so.

Thanks!

**Comment by bradders** [comment]
Woah, didn't realize I was so far behind latest! I'll just update and fix my own problem! 😄

Thanks, @driesvints
