### ISSUE TITLE
Laravel\Cashier\Concerns\ManagesSubscriptions references incorrect subscription

### ISSUE THREAD

**Issue by danielbachhuber** [laravel/cashier-stripe#994]
- Cashier Version: 12.3.1
- Laravel Version: 7.28.2
- PHP Version: 7.4.10
- Database Driver & Version: MariaDB

### Description:

We have an application state where an older Stripe subscription is restarted and marked active:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/36432/93487374-0cc40580-f8ba-11ea-8ebc-4a3f7f754d0f.png">

In this scenario, `Laravel\Cashier\Concerns\ManagesSubscriptions::subscribed()` returns false because subscription#740 is the newer subscription.

I'd expect `::subscribed()` to return true because subscription#640 is `stripe_status=>active`

### Steps To Reproduce:

I'm not 100% positive how this is happening (I'm maintaining a legacy application) but I think Churnbuster is restarting the subscription independent of the Laravel application. When the subscription is restarted, Stripe sends a webhook to the application and we enter this erred state (the end user still sees their subscription as canceled).

**Comment by driesvints** [comment]
This shouldn't happen indeed. You should only ever change the lastly added subscription, never an older one. Those are only kept in the database for historical purposes. 

I'm not sure what Churnbuster is or why it does that but it indeed shouldn't. We could look into patching the webhook though to prevent a status change but then the subscription would be out of sync from Stripe and you don't want that either. So bit torn on what we should do here.

**Comment by danielbachhuber** [comment]
> This shouldn't happen indeed. You should only ever change the lastly added subscription, never an older one. Those are only kept in the database for historical purposes.

I figured as much.

> I'm not sure what Churnbuster is or why it does that but it indeed shouldn't. We could look into patching the webhook though to prevent a status change but then the subscription would be out of sync from Stripe and you don't want that either. So bit torn on what we should do here.

Yeah, I don't have a great suggestion either. I was able to work out a solution for my need (i.e. overloading `subscribed()`) but it seems Cashier wasn't architected with this use case in mind.

[Churnbuster](https://churnbuster.io/) is a churn recovery service.

**Comment by driesvints** [comment]
Ok thanks. I'm gonna close this one as a nofix because I think it's important that Cashier stays in sync with Stripe. I'll try to send in an update to the docs to make it obvious that we only consider the lastly created subscription as the current "active" one.

**Comment by driesvints** [comment]
Ref: https://github.com/laravel/docs/pull/6403
