### ISSUE TITLE
Cashier still assumes App\User despite Laravel 8's new App\Models\User

### ISSUE THREAD

**Issue by sunlight** [laravel/cashier-stripe#995]
- Cashier Version: 12.3.1
- Laravel Version: 8.3.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL / MariaDB 10.5.5

### Description:
According to the Laravel docs:

> Cashier assumes your Billable model will be the App\Models\User class that ships with Laravel.

However config/cashier.php contains this line:

```php
'model' => env('CASHIER_MODEL', App\User::class),
```

I realise this is an easy fix with an _.env_ entry, but would contradict expected behaviour. I'm ignorant of the inner workings of this package, but oddly several of the functions worked without the _.env_ entry, and the _App\User not found_ exception was only thrown when calling `$user->subscription('default')->cancel();`

### Steps To Reproduce:

Assuming `$user` is an instance of `App\Models\User`, `STRIPE_PRICE_PREMIUM_PLAN` is the price id and `$setupIntent` has come from sending card details to Stripe:

```php
$user->createOrGetStripeCustomer();
$user->newSubscription('default', env('STRIPE_PRICE_PREMIUM_PLAN'))->create($setupIntent['payment_method']);
$user->subscription('default')->cancel();
```

**Comment by driesvints** [comment]
Thanks. We're aware. We can't change this for the current stable release because it's a breaking change. You'll need to update the env value for now. We'll update the default for the next major version.

**Comment by fylzero** [comment]
Just noting this was recently fixed:  https://github.com/laravel/cashier-stripe/commit/9024107f51bcdd69607395dc5606fdcd35498f85
