### ISSUE TITLE
CASHIER_MODEL in config/cashier.php is not defaulted to App\User as documentation suggests

### ISSUE THREAD

**Issue by fylzero** [laravel/cashier-stripe#997]
- Cashier Version: 12.3.1
- Laravel Version: 8.6.0
- PHP Version: 7.4.10
- Database Driver & Version: MySql 8.0.21

### Description:
In the Laravel 8 documentation for Cashier it says the default model is set to App\Models\User but in the config/cashier.php it is defaulted to App\User still.  Not sure if this is a cashier disconnect or a documentation issue otherwise I'd submit a PR.

### Steps To Reproduce:
Install Laravel 8, install Cashier, look at the config/cashier.php setting for Cashier Model.

**Comment by driesvints** [comment]
Please see https://github.com/laravel/cashier-stripe/issues/995

**Comment by fylzero** [comment]
Just noting this was recently fixed:  https://github.com/laravel/cashier-stripe/commit/9024107f51bcdd69607395dc5606fdcd35498f85
